### ISSUE TITLE
Provide binary distributables for Dolphin 7

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/Dolphin#10]
See [forum request](https://groups.google.com/d/msg/comp.lang.smalltalk.dolphin/Bz43AGRP7VI/UABBtb7OCAAJ).

**Comment by fxgallego** [comment]
I've tested a dumb setup at [AppVeyor](https://ci.appveyor.com).
Setup detail:

1. New Project
2. General Setup
 * Selected the GitHub repo (Dolphin)
 * Default branch "master"
 * Branches to build => Only specified below => " master" (this is to avoid build on feature branches)
3. Build
 * Select **SCRIPT**
 * Use this tiny script "call BootAll.cmd"
4. Artifacts
 * Added an 2 artifact paths: "*.img7" and "*.chg" (added on 2 different rows)

When build the following output is produced

```text
Build started
git clone -q --branch=master https://github.com/fxgallego/Dolphin.git C:\projects\dolphin
git checkout -qf e2c9e842e650e60de8dc6b829ff4c470df61effd
call BootAll.cmd
Discovering tests...OK
Packaging artifacts...OK
Uploading artifact DBOOT.chg (9.8 MB)...OK
Uploading artifact DBOOT.img7 (1.3 MB)...OK
Uploading artifact DCE.chg (194 bytes)...OK
Uploading artifact DCE.img7 (7.3 MB)...OK
Uploading artifact DCORE.chg (194 bytes)...OK
Uploading artifact DCORE.img7 (6.1 MB)...OK
Uploading artifact DPRO.chg (194 bytes)...OK
Uploading artifact DPRO.img7 (9.2 MB)...OK
Build success
```

We can add support to Dolphin to run tests from command line, make deployments (Lagoon or other). A custom st runner is OK. All output should be redirected to **stdout**.
It'll be nice to have output formaters providing integration with other CI servers like TeamCity or Jenkins. Usually this servers works interpreting text from stdout stream.

All this setup could be as useful for Dolphin as the applications developed with it.

**Comment by objectarts** [comment]
Hi,

Yes, following suggestions in the forum, I also have AppVeyor running for the Dolphin and DolphinVM repos (it seems really easily to get AppVeyor going for use with GitHub). I was going to do something similar to what you have above, perhaps creating a zip artifact and uploading this via FTP to the OA downloads site. We could do this on every tag (rather than every commit) I think.

There are a bunch of Dolphin SUnits available. I'll get these into the Dolphin repo and we can try and make them callable from the command line so they can be added to the AppVeyor tests.

**Comment by fxgallego** [comment]
I suggest you to build on each commit-push.
To handle the thing about releases you should manage different branches, one for develop and one for release (master). On master each release gets tagged.
Read this: http://nvie.com/posts/a-successful-git-branching-model/
This other appears to be a [polished version](http://danielkummer.github.io/git-flow-cheatsheet/) but I've learned all from the first link. Note that we use this model with a little variation from 2+ years and with total success.
This allows to have a very active and up to date branch for developers to work on and a stable branch with confidence to build production releases. And it allows to introduce patches that can be merged upstream.
In my work we have a different branch for each version, for example, in a Dolphin world, it means having develop, 7.0, 6.0, 5.0, ... branches and we don't use "master" as the link recommends but it depends on the needs. That's because we have different versions in production. I'm sure in Dolphin will be enough with "master + tags".
Note that tools that provides "git flow" features are only wrappers on normal git commands. Currently SourceTree supports git-flow, at least the last version I've used.
Sorry if you know all this stuff but maybe is useful to other smalltalkers no used to git world.

**Comment by objectarts** [comment]
For the OA repo at least, I hadn't intended to follow that branching model but rather the simpler flow model described in [GitHub Flow](https://guides.github.com/introduction/flow/). Note that GitHub-Flow is confusingly not the same as Git-Flow. Basically, in this there is no "development", "release" or "hot-fix" branches. Branches are only created temporarily for new feature development and then merged back to the master trunk when done. Then the branch is deleted. Every so often when we have a stable master (note, the master should always be stable) that is worthy of a release we can tag it with a new version number as you suggest. At that point new image binaries can be built into an "end-user" release - either a zip file or EXE setup program.

**Comment by fxgallego** [comment]
OK, it's simpler but IMO doesn't handle all stages. For example, hopefully you are about to release Dolphin 8 and don't want more features to be merged in development so you need a branch to stabilize the release while development continues for 9.0. So a new branch release/8.0 is created  to handle this.

But, at the end, is a matter of branches only and we don't need to be worried about this just now. As I always said, and one of the reasons I love Dolphin, respect the KISS law.

**Comment by objectarts** [comment]
There is now an AppVeyor build that uploads a [GitHub Release](https://github.com/dolphinsmalltalk/Dolphin/release) for every tag created.
