### ISSUE TITLE
Float infinity * 0 raises Invalid operation

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#1009]
**Describe the bug**
`Float infinity * 0` raises invalid operation while it works for non 0. In Pharo, same operation returns nan.

**To Reproduce**
Evaluate `Float infinity * 0`

**Comment by blairmcg** [comment]
This isn't a bug, it's expected. Multiplying infinity by anything other than 0 results in infinity, but the operation isn't defined for multiplication by zero, hence the NaN result when the exception is masked. In Dolphin invalid FP operation exceptions from the CPU are not masked by default. If you want them to be then change the DefaultFpControl mask to remove the _EM_INVALID. You can do this globally, or per process, or for the duration of some operation. See the Float tests for examples.

**Comment by fxgallego** [comment]
OK I understand.
Is it correct and enough to change it globally modify the value of Process.DefaultFpControl ?

**Comment by blairmcg** [comment]
Well, it will work as it is tested with and without for many operations (although ironically not for multiplying infinity by zero, but the underlying code is common and you will definitely get a NaN if you mask out the exceptions). Whether or not it is "correct" depends on what you want. 
If you change the default it will be picked up by all newly forked processes. You can change the mask in the current process using Float class>>exceptionMask: (or just kill the UI process). It will persist in saved images.

**Comment by fxgallego** [comment]
OK I understand. I'm a bit curious here about why this was changed from older versions. In previous versions infinity * 0 returned NaN as well -1 sqrt. I tested the same in Pharo, Ruby and JavaScript and all return NaN for infinity * 0, but signaled an error for -1 sqrt. And also found some [references to IEEE 754](https://wiki.analytica.com/index.php/INF,_Nan,_Zero_and_IEEE/SANE_arithmetic) saying that it should return  NaN. I do not want to bother you with this. I am asking because I want to understand better if I should change the current Dolphin behavior or change the way we have been doing some calculations in order to avoid this problems.

**Comment by blairmcg** [comment]
Without doing a lot of research to establish it, if the behaviour has changed it is probably due to a fix from either the move to SSE2, or a change in the C compiler, or the CRT. In earlier versions of Dolphin all FP exceptions (except "inexact") were unmasked and you couldn't reliably get a continuation value. At some point in 7 I rewrote the primitives and some supporting code so that you could resume an FP exception and get the IEEE754 continuation value appropriate for the circumstance. Like this:
```smalltalk
[Float infinity * 0] on: FloatingPointException do: [:ex | ex resume] "=> Float.NaN"
```
It might be OK to wrap a large block of calculations like this if the error is only expected occasionally, but the performance is going to be poor otherwise.

At the time I also changed the default exception mask so that most exceptions were masked. Zero divide and invalid operation were left unmasked to try and help catch logic errors. Later I changed the build to compile for SSE2, and this did change the behaviour with respect to FP exceptions, but I think it is probably more correct now in that it is consistent.
Again without re-reading it all, my memory of IEEE754 is that any invalid operation (including taking the square root of a negative number) should ultimately result in some kind of continuation value (a NaN or infinity value), and the intention is that this is what you should get in Dolphin if you either mask all the exceptions, or continue from them. Both are tested, although there may (of course) be gaps in the tests.

It's not really consistent  to raise an error for `-1 sqrt` but not `∞*0` - both are undefined. It may be that the environments you mention have masked all exceptions but are specifically checking for negative square root, for example, or perhaps are using underlying libraries that behave that way. IEEE754 also says that -1 sqrt should return a NaN.

The exceptions can be temporarily masked:

```
"Evaluate as one block"
mask := Float exceptionMask: OS.CRTConstants._MCW_EM.
["Some calculations that would otherwise raise an Invalid Operation or zero divide"
1.0/0*0] ensure: [Float exceptionMask: mask] "Float.NaN"
```

This is how the Float tests turn the masks on and off to verify both exception raising and continuation value modes. However, I have noticed there is a bug with changing the exception mask of a process and I suspect that the save/restore of floating point state that is done when switching processes is supplanting the fpControl word setting stored in an instance variable in the Process. Hence the need to kill the active process in the script below. I'll raise an issue for that.

If you want the full IEEE754 behaviour in Dolphin you can just set the exception mask to _MCW_EM. This will give you NaNs for invalid operations, and also infinity for division by zero. Or you can leave divide by zero unmasked if you wish (as in the script below).

```smalltalk
"Invalid operation exceptions with standard settings - evaluate statement by statement"
Process addClassConstant: 'DefaultFpControl'
		value: OS.CRTConstants._RC_NEAR | OS.CRTConstants._IC_PROJECTIVE | OS.CRTConstants._DN_SAVE
				| OS.CRTConstants._PC_64
					| (OS.CRTConstants._MCW_EM maskClear: OS.CRTConstants._EM_ZERODIVIDE | OS.CRTConstants._EM_INVALID).
"Make the main process pick it up"
Processor activeProcess fpControl: Process.DefaultFpControl. Processor forkMainIfMain.
"Test cases - expect Floating point errors"
Float infinity * 0.
-1 sqrt.
1.0/0.0.

"No invalid operation exceptions, although zero divide left unmasked here. Again, evaluate statement by statement"
Process addClassConstant: 'DefaultFpControl'
	value: OS.CRTConstants._RC_NEAR | OS.CRTConstants._IC_PROJECTIVE | OS.CRTConstants._DN_SAVE
			| OS.CRTConstants._PC_64 | (OS.CRTConstants._MCW_EM maskClear: OS.CRTConstants._EM_ZERODIVIDE).
Processor activeProcess fpControl: Process.DefaultFpControl. Processor forkMainIfMain.
"Test cases - expect return continuation values, except divide-by-zero here"
Float infinity * 0. "Float.Nan"
-1 sqrt. "Float.NaN"
1.0/0.0. "Division by zero as we left it unmasked above, comment out or remove the maskClear: to mask that too"
Float infinity/0.0. "Float.NaN (not division by zero)"
```

**Comment by fxgallego** [comment]
Thanks for the details Blair. I think that this is enough information to decide which path we should follow.
