### ISSUE TITLE
FetchVM.cmd and ps1 scripts fail to download VM

### ISSUE THREAD

**Issue by vince-refiti** [dolphinsmalltalk/Dolphin#1011]
**Describe the bug**
Running FetchVM cmd and ps1 scripts fail to download VM. Version info inside scripts are incorrect (?). The ps1 script has v7.1.4, but it should be 7.1.14. The cmd script has v7.1.15.

**To Reproduce**
1. Go to clone or update Dolphin repo
2. Run either script.
3. Get an error message saying "Unable to fetch DolphinVM.zip v7.1.4" or "Unable to fetch DolphinVM.zip v7.1.15"

**Additional context**
I tried this after a new clone at 21:37 10/09/2020 Australian EST

**Comment by brunobuzzi** [comment]
Did you try to run from PowerShell:
`.\FetchVM.ps1 v7.1.14`

**Comment by vince-refiti** [comment]
Yes, I got it working after I looked in the PowerShell script for the source of the error.

**Comment by brickviking** [comment]
Isn't this supposed to get its own version due to "git describe --tags --abbrev=0" being run in the .cmd script just before FetchVM.ps1 is executed? That's what I understand to be the case.

i.e. on my system, running the above git command gives me an output of v7.1.13, which then gets fed to FetchVM.ps1 as an argument.

**Comment by blairmcg** [comment]
That is correct. There is nothing wrong with the script. The issue is that the release does not exist on github. The release build no longer fires correctly on tags, so the binaries for v7.1.15 were never published.
I'll take a quick look, but unless it is a easily addressed I will simplify things by removing the whole thing. It's easy to build the VM with VS2019, the community edition of which is free. This is also a development tool so it shouldn't be a big deal for its developer users to build it themselves, or to go to appveyor and download the binaries from there.

**Comment by blairmcg** [comment]
Fortunately it was easy to fix - an appveyor build can't be configured to trigger on tags, **and** be restricted to certain branches. If the branch restriction is in place it simply doesn't fire when tags are pushed.
