### ISSUE TITLE
Folder>>parent error with unicode pathnames

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#1022]
**Describe the bug**
There is a problem with Folder>>parent when the pathname contains some unicode chars.
I got this error using the latest version. It doesn't happens in 7.1.14. I traced the problem to 8bcdd09ce6817a668cd2a007074de21593ab6614 with the addition of `UtfEncodedString>>first:` but the problem seems to be related to the `#parent` method itself which sends `size` to split the path.

```smalltalk
parent
	"Answer a <Folder> representing the receiver's parent, or nil if a root.
	Note that this will be a new object each time as currently implemented,
	but they will be equal."

	| path |
	^(path := self pathname) isEmpty 
		ifFalse: [self class pathname: (File splitPathFrom: (path first: path size - 1))]
```

You can solve this changing `size` by `length` which seems correct to me.

**To Reproduce**
We can reproduce this trying to create a new package inside a folder named `'Camión'` causing a stack overflow. The real problem can be observed evaluating in a workspace: `(Folder pathname: 'camión\camión') parent`

**Comment by blairmcg** [comment]
In the 7.2 branch I have changed this to:

```
parent
	"Answer a <Folder> representing the receiver's parent, or nil if a root.
	Note that this will be a new object each time as currently implemented,
	but they will be equal."

	| path |
	^(path := self pathname) isEmpty
		ifFalse: [self class pathname: (File splitPathFrom: (path copyFrom: 1 to: path size - 1))]
```

The method is just trying to strip the trailing path separator. It shouldn't be using `first:` any more, because that is expecting a code-point count, not a code-unit count. Changing `size` to `length` would fix it, because it means that `first:` is passed the correct count, but the above is more efficient since we know that the path separators can only ever be one code-unit in size.
