### ISSUE TITLE
Deprecated message sent from TextAndImageButton

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#1037]
`TextAndImageButton>>wmLButtonDown:wParam:lParam:` is sending the deprecated message `WindowsEvent class>>message:handle:wParam:lParam:`. This causes an MNU error when clicking a button with a drop-down menu if the deprecated package is not present (e.g. in a deployed app).

Needs changing to `window:message:wParam:lParam:`

**Comment by blairmcg** [comment]
That seems to have been deprecated since the original github commit, so I'm not sure when that came in.

We should add a `PackageClosureTest` for something using this and your other widget enhancements John; maybe the `EditableListViewDemo` if it covers enough (or could be easily changed to do so), as that will help picking up such breaks in future. Its not 100% reliable as the actual image stripping is difficult to completely replicate logically with `BrowserEnvironment`s, but it's pretty good at finding things that will definitely be missing. Based on an experiment of adding such a test (as below) and removing the manual pre-requisite on the 'SSW Widget Development' package (is that needed?) I get the following unimplemented messages in the theoretical app deployment:

`'Expected: #() Actual: #(#defineField:type:offset: #message:handle:wParam:lParam: #productRegistryKey).'`

As you can see, `#message:handle:wParam:lParam:` is among them.

Here is the test:

```smalltalk
PackageClosureTest>>testEditableListViewDemo
	"Tests predicted unimplemented messages in EditableListViewDemo"

	self verifyPackageClosure: (self environmentForAppDeployment: {EditableListViewDemo owningPackage})
		missing: #(#defineTemplate #evaluate:)
```

**Comment by rko281** [comment]
Thanks for the advice Blair.

Looking at D7.0 I see `WindowsEvent class>>message:handle:wParam:lParam:` was already deprecated, but the application I'm dealing with had an implicit dependency on 'Dolphin MVP (Deprecated)' so it wasn't an issue in deployment. The dependency is gone in the D7.1 version so I've only started hitting the problem now.  

Re: the manual prerequisite of 'SSW Widget Development', I think this was just an easy way to ensure all packages were installed by loading just the Demo package.

**Comment by blairmcg** [comment]
As a test for #1042, PR #1043 adds the test as above and removes the manual pre-req.
