### ISSUE TITLE
ListView with very large number of items shows unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#1066]
A ListView with at least one auto-sized column and enough items to be >`2**16` pixels high (a little over 1500 items for a `ListView new showShell` with default font etc) acts as though it shouldn't have a vertical scrollbar, thus making the auto-size column too wide and ending up with a *horizontal* scrollbar as well.

This is because `LVM_APPROXIMATEVIEWRECT` returns its answer as a pair of 16-bit integers packed into the 32-bit return value, so at a certain point it overflows and wraps around. I can see two basic approaches:

We could just assume that if we have over, say, 1000 items, the vertical scrollbar will be needed, and don't even bother sending LVM_APPROXIMATEVIEWRECT. Or, as a refinement, calculate the height of a single item (with `itemRect:`), multiply by the number of items, and if this exceeds a conservative value (say `2**15`), again assume a vertical scrollbar.

Or, we could calculate an exact required height by using the difference between the `itemRect:` of the first and last item. For this to work, we also need to account for the column header (it looks like `LVM_APPROXIMATEVIEWRECT` does so internally). The code to do this directly (by querying the unmanaged view that represents the header) exists, but it's in SSW ListView Extensions, not core. But we could also take advantage of the fact that `LVM_APPROXIMATEVIEWRECT` accounts for it: Ask for the height required to display 0 items, then add that to the difference of `itemRect:`s.

Any thoughts on which approach to take?

----

Two minor related details:

`autoResizeColumns:` doesn't specify whether the argument is a client width or full frame width, and the two callers are inconsistent in which they pass. The implementation actually expects a full frame width, but as a comment notes, the adjustment it performs to get a client width is arbitrary and only correct for some combinations of `hasBorder`, `hasStaticEdge`, `hasClientEdge`. This can be replaced by `calcClientRectangleFromRectangle:`, which is correct in all cases AFAICT. I'd tend to make the argument always a proper client width and change `onPositionChanged` to do the calculation.

Well, except that if the view *in fact* has one or both scrollbars, `calcClientRectangleFromRectangle:` does not account for their presence, even though they do affect the answer from `clientRectangle`. For our purposes here (responding to position changes before the view has had a chance to update its scrollbars) this is a good thing, but it seems wrong in general? Or, since this comes straight from the behavior of WM_ADJUSTWINDOWRECTEX, perhaps this is a Win32 gotcha that's nonetheless expected behavior?

**Example **
```Smalltalk
lv := ListView new showShell.
lv viewMode: #report.
lv list: (1 to: 1600).
"Resize the shell just a little bit, observe that both scrollbars appear"
```

**Comment by blairmcg** [comment]
> We could just assume that if we have over, say, 1000 items, the vertical scrollbar will be needed, ...
> ...
> Or, we could calculate an exact required height by using the difference between the `itemRect:` of the first and last item. ...

If the correct value can be calculated simply and at relatively low cost, then that would always be preferable. Whatever is done, care needs to be taken not to code in too many assumptions about any particular usage, or dependencies on the current Windows control visual design. 

As this relates to auto-sizing columns, I assume you are intending that any intervention would affect report mode only. In the other modes the relative position of items is not just a vertical stack, so trying to calculate the geometries by reference to the position of first and last items will not always work.

> For this to work, we also need to account for the column header (it looks like `LVM_APPROXIMATEVIEWRECT` does so internally). The code to do this directly (by querying the unmanaged view that represents the header) exists, but it's in SSW ListView Extensions, not core. But we could also take advantage of the fact that `LVM_APPROXIMATEVIEWRECT` accounts for it: Ask for the height required to display 0 items, then add that to the difference of `itemRect:`s.
> 
> Any thoughts on which approach to take?

Definitely better to use the more abstract approach of asking LVM_APPROXIMATEVIEWRECT to provide a minimum size because it avoids depending on any (probably undocumented) specifics of the current design that Microsoft might change in future.

Accounting for the presence/absence of scrollbars in layout can be tricky given the chicken and egg nature of the problem. It is all too easy to create an unstable layout. The terminology associated with `calcClientRectangleFromRectangle:` (and the AdjustWindowRectEx API underlying it) is perhaps a bit over-simplified (or conflated) as depending on need it may be useful to think of client area including the area for the scrollbars, or it may not, and there is no clear distinction in the Windows APIs, nor necessarily a lot of consistency as to which approach is taken by the implementation of different controls, or even different functions of the same control.

**Comment by daniels220** [comment]
Alright, see associated PR using the "LVM_AVR-for-0-items plus itemRect:" strategy. And yes, only for report mode.
