### ISSUE TITLE
VM dump report cut off on encountering Unicode character

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#1089]
Evaluate, for instance:

```
VMLibrary default
	dump: 'abc' , (String with: Character dolphin)
	path: nil
	stackDepth: 0
	walkbackDepth: 1
```

The `.errors` file cuts off right where the dolphin symbol would have appeared. Characters that are representable in the ANSI codepage are no problem, even if the actual string passed to the VM function is UTF-8 encoded—try replacing the dolphin with the `½` symbol for instance. Looks like the VM is writing everything using the ANSI encoding and failing as soon as it encounters a character it can't represent. It would be a worthwhile improvement if it simply replaced it with a `?` instead, as when calling `asAnsiString` in the image, but ideally it would switch over to writing everything using UTF-8.

**Comment by blairmcg** [comment]
Good find. The strings are passed into the VM as UTF-16 by the FFI primitive (the arg type is lpwstr), so they arrive intact.
The problem is the way the C++ wofstream (wide-char output file stream) is being opened - it needs to be imbued with correct encoder but is left with the default, which apparently doesn't behave sensibly (like inserting the replacement char as you suggest).

**Comment by daniels220** [comment]
Nice, thanks. Out of curiosity, does the fix result in UTF-8 output, or just ANSI-but-with-replacement-chars-rather-than-breaking?

**Comment by blairmcg** [comment]
UTF-8, as demo'd by the test
