### ISSUE TITLE
Unable to deploy with latest

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#1102]
With cd550703cfbaeed148a67d2c7a15ed3674de1e04 (15-Feb-2021), I'm unable to deploy. It puts up an error dialog reporting circular references (though I can't find any) and the deployment progress dialog has a line reporting that the ImageStripper hierarchy does not define #developmentMethodCategoryNames. 

![Screen Shot 2021-02-16 at 11 43 21 PM](https://user-images.githubusercontent.com/1577872/108171769-de3c9780-70b0-11eb-8723-23681fd5663c.png)

**Comment by jgfoster** [comment]
Also unable to deploy with 7.2.8.

**Comment by blairmcg** [comment]
Please see the emboldened note at the top of [the readme](https://github.com/dolphinsmalltalk/Dolphin/blob/release/7.1/README.md) - I would not expect application deployment to work in master at present. Much of it is not covered by automated tests, so it is bound to be broken while the 7.2 development is in progress. It should work in `release/7.1` (which is currently the default github branch). I did start fixing some basic problems with it in master last night while testing deployment of the MVP examples, having renamed them into namespaces, so will keep the issue open to associate with that.

BTW, the only reason that I am tagging 7.2 versions is so that there are downloadable VM binaries for the fetchvm script. Each of the tags corresponds to an incompatible VM change. None of them will ever be anything other than pre-release versions.

**Comment by blairmcg** [comment]
You should find that most issues blocking deployment are fixed by a8bfa279, although I expect there will be further issues in the deployed application.
