### ISSUE TITLE
Gdiplus.Image & Gdiplus.Bitmap broken class example methods 

### ISSUE THREAD

**Issue by FBek055** [dolphinsmalltalk/Dolphin#1109]
**Describe the bug**
**_Graphics.Gdiplus.Image_** and **_Graphics.Gdiplus.Bitmap_** have a number of broken Class Examples, '_exampleGdiplxx_' due to missing resourcee, e.i., **_pafEye.jpg_**  & **_pafRgb0000FF_100x100bmp_** & **_pafSeattleNightJpg_** & **_fish32x32pngBytes_** & **_pafWinXP32x32ico_** ...

**To Reproduce**
1. Starting with _Graphics.Gdiplus.Image >> exampleGdipIFlags_
2. See error in status line '**_Warning undefined selector #pafEye.Jpg_**'
3. note: there seem to be other errors as well purely due to the new namespace, e.g., "_Error: undeclared 'RichTextPresenter'"_ in the same example. 
4. Other broken methods in _Image_ class include: exampleGdipIInterpMode, exampleGdipIJPEGCompression, exampleGdipILosslessRotation, etc... 
5. Broken methods in _Bimap_ class start from: exampleGdipBFromByteArray, exampleGdipBFromXPIcon, etc...

**Expected behavior**
Restore or replace missing resources to ensure all class examples will execute without errors.
A system wise auto-testing of class examples would also be handy.

**Please complete the following information):**
 - OS: Windows 10

**Additional context**
Class examples are very valuable, it would really be handy to include as many as possible, in a systematic way, to showcase the various features, especially given the limited availability of other forms of documentation. Could this be a valid alternate form of built-in comprehensive documentation? (I presume most of them are written anyway, at an early stage of a class development, as a first means to check the functionality).
If all class examples could be made to follow a unified protocol, finding and testing them could be easily automated.

**Comment by blairmcg** [comment]
If you look in the Transcript, you should see this message:
```
GdiplusTests package needs to be installed for this example to work.
```
Which hopefully is self explanatory, although it should be an error rather than a notification, or it is liable to be overlooked.

> A system wise auto-testing of class examples would also be handy.

They are [all tested](https://ci.appveyor.com/project/dolphinsmalltalk/dolphin-db22v/builds/38047821?fullLog=true#L3111). The original authors who contributed the package decided to package the resources this way in order to take advantage of SUnit resources as part of also testing the examples. Given that these particular examples don't work without the tests it might have been better that they were put in the test package, or alternately that the resources were not, but it is more inconvenient than broken. I would recommend always loading the tests (see readme), as one of their uses is as a source of examples.

**Comment by FBek055** [comment]
Thanks for the quick response and clarifications, fair enough. 

I may have missed a beat, as a beginner, are you referring to running TestDPRO.cmd which presumably loads all test packages? I could not find any reference to a GdiplusTests package otherwise.

**Comment by blairmcg** [comment]
Just 'File/File in...' the `RegressionTestsLoad.st` script file, or open the script that is run by TestDPRO.cmd, `RegressionTestsRun.st`, and evaluate this bit:

```
 SourceManager default fileIn: 'RegressionTestsLoad.st
```

**Comment by FBek055** [comment]
OK, I had to rebuilt Dolphin to ensure a clean setup, run TestDPRO.cmd to ensure all is checked, then File in `RegressionTestsLoad.st`  using _Source Browser_. The broken resource issue is now resolved. 
Thanks for the support
