### ISSUE TITLE
"Debug Assertion Failed!" when compiling method

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#1190]
Compiling or viewing this method causes a Microsoft Visual C++ Runtime Library error. I am running Windows 11 on Arm, so this might be an issue with the i386 emulation.

<img width="742" alt="Screenshot 2023-08-28 at 7 25 15 AM" src="https://github.com/dolphinsmalltalk/Dolphin/assets/1577872/f723023e-a393-4e8f-9fb9-62ba01da27e3">

**Comment by blairmcg** [comment]
This is probably another case of #533, or is at least strongly related. There are some longstanding issues with the generation of the text maps used to remap from optimised method IPs to debug method IPs. As such it may potentially affect debugging, but otherwise can be ignored as it is not involved in normal execution.

**Comment by jgfoster** [comment]
As mentioned, I was using a debug version. Thanks again for your help.
