### ISSUE TITLE
Stack overflow computing #hash of various self-referencing objects

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#123]
I think that the proper solution is to have a new hash function that takes as an argument a collection of visited objects to avoid the recursion. I can work up something but before spending much time on it I'd welcome some input/guidance.

| array |
array := Array new: 1.
array at: 1 put: array.
array hash.

| assoc |
assoc := Association new.
assoc key: assoc.
assoc hash

**Comment by frank-lesser** [comment]
I don't thing that it is a good idea to change any of these very basic things to handle self reference.
	If you look at implementors of hash allmost all of them will fail in case of self reference.
	I would regard it as a "programming error" if you have such self references & use hash on those objects.
		
	Either you define subclasses with special hash functions or forbid self references.

	The special implementation of Collection >> #printOn: - dealing with self reference is for development purpose - 
	as you would normally not explect to see a print of a self referencing Array at runtime.

**Comment by blairmcg** [comment]
I agree with Frank. The traditional Smalltalk implementations do not handle this case. The performance
impact of maintaining a visited set would preclude doing this at such a basic level.

**Comment by jgfoster** [comment]
Okay then. How about a new suite of cyclic-safe enhanced hash-based classes (Dictionary, Set, etc.)?

**Comment by blairmcg** [comment]
@jgfoster, If you need this, take a look at PluggableSet and PluggableLookupTable as these can probably already support what you want. These delegate the hash and comparison operations to a policy object that implements the <searchPolicy> protocol - if you open the protocol browser and locate the searchPolicy protocol in the list, you'll be able to see both the selectors in the protocol that are sent by PluggableSet/PluggableLookupTable and also the implementing classes (all under the abstract SearchPolicy). You could provide a searchPolicy that used a custom #hash of your own invention that is cyclic-ref safe, or just use the PluggableSearchPolicy and provide the two blocks it needs for hash and comparison purposes. 
It would probably be better if the basic hashed classes were pluggable in this way, in much the same way that years ago I decided to re-implement the base SortedCollection class to abstract out the sort algorithm. The main reason they aren't is that MethodDictionary has to use the same hash algorithm as the VM. However, this class could easily be moved so as to be self-sufficient without needing to live under IdentityDictionary. There would be some perf hit in the extra level of indirection through the searchPolicy over direct sends of #hash and #=, so that would need to be considered given the pervasive use of these classes in the system.

**Comment by jgfoster** [comment]
@blairmcg, thanks very much. That is helpful advice. I'll see how I get along...
