### ISSUE TITLE
Errors during boot process

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#158]
Do I need to be concerned about these errors during BootPRO?

Loading boot script...
Reloading BCL constants pools...
Reloading BCL class definitions...
Error: VMLibrary class>>registryKeys at line 4: undeclared 'RegistryKeys'
Error: VMLibrary class>>initialize at line 77: undeclared 'RegistryKeys'
Error: VMLibrary>>onStartup at line 6: undeclared 'RegistryKeys'
Error: VMLibrary>>registryAt:put: at line 5: undeclared 'RegistryKeys'
Error: VMLibrary>>registryAt: at line 4: undeclared 'RegistryKeys'
Error: Float class>>denormalized at line 5: undeclared '_EM_DENORMAL'
Error: Float class>>setExceptionMask: at line 5: undeclared '_MCW_EM'
Reloading BCL classes...

**Comment by blairmcg** [comment]
No, you don't. Changes to the definitions of classes that remove variables and pool references may cause some methods to fail to recompile. As long as these methods are not required by the boot process itself this is not a problem since they will be replaced, or deleted if they are no longer defined. IOW errors in the "Reloading BCL class definitions" section can be ignored if they do not cause issues during the boot process itself, as they will not persist. Errors after the "Reloading BC classes..." are indicative of a problem that will likely persist in the booted image.

**Comment by jgfoster** [comment]
Okay. Thanks!
