### ISSUE TITLE
Unrecognized virtual key 'Num *'

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#159]
View: 'Debugger.Basic debugger'
MenuBar, 'Debug' menu, 'Show Next Statement' menu command, accelerator key

| x |
x := AcceleratorTable keyStringFromCode: 8810. " 'Alt+Num *' "
AcceleratorTable keyCodeFromString: x.

10:25:39 AM, Tuesday, March 15, 2016: 'Unrecognised virtual key: ''Num *'''
Keyboard class(Object)>>error:
[] in Keyboard class>>virtualKey:
LookupTable>>at:ifAbsent:
Keyboard class>>virtualKey:
AcceleratorTable class>>keyCodeFromString:
UndefinedObject>>{unbound}doIt

**Comment by blairmcg** [comment]
Hmmm, it works fine for me, but I suspect it may be locale sensitive. I get:

```
| x |
 x := AcceleratorTable keyStringFromCode: 8810. "'Alt+NUMMULT'"
 AcceleratorTable keyCodeFromString: x.

```
The mapping of the VK_XXX virtual key code to a scan code is performed by a call to the Win32 API MapVirtualKey.  Which is then translated to a key name by a call to another Win32 API, [GetKeyNameText](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646300(v=vs.140).aspx). The msdn page says that the format of the result depends on both the keyboard layout, and the locale, although actually it seems that changing the default locale does not affect it, whereas changing the default keyboard input locale does. I get "NUMMULT" for a UK Keyboard, and 'Num *' for a US one.

The key names are effectively hardcode in the Keyboard class during class initialization. This needs to be changed to re-initialize on image start, and ideally to respond to changes to the users keyboard layout. However, it is not a suitable mechanism to use to retrieve readable key names to store in code, if that is what you want it for, since you can't rely on it being stable.

**Comment by blairmcg** [comment]
Actually, it's a bit more complex than that. The key names stored in Keyboard are deliberately using an invariant locale (UK English) specifically in order to support being able to use a standardized name for programming purposes, with that name not intended to be displayed to the user. The methods in AcceleratorTable should be able to work with the locale specific names in both directions. The keyStringFromCode: method is doing the right thing in creating a locale sensitive string, as this is displayed on the menus, but keyCodeFromString: is using the invariant locale whereas it should be using the configured keyboard locale.
