### ISSUE TITLE
Intermittent local failures in MemoryMappedFileTest>>#testMaximumSize

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#164]
When I re-run it the test often (but not always) passes. Any suggestions on how to make this test more consistent or provide evidence to help debug?

**Comment by blairmcg** [comment]
Yes, I have seen this problem intermittently. I think the parts of the test that are checking that unmapping takes effect are unreliable, or there is a bug and the file is not actually unmapped successfully so the memory remains accessible. I don't think it is the latter because the test initializes the memory to a certain pattern that is not then present. My theory is that due to object memory or process stack allocations that the just-released 64kb page gets reallocated.
It would be reasonable to move it to the known failing tests package for now and then leave this issue open to track fixing it. I'm about to push some stuff, so I'll do that.

**Comment by blairmcg** [comment]
Fixed - the assertions that reading/writing off the end of the allocated space would cause access violations were invalid. It could always be the case that some other memory had been mapped at these locations, and this seems to occur commonly when the tests are launched manually as part of a run of all tests in the test runner. Subsequently debugging the test individually then usually passed. Anyway the offending assertions are removed, and the test reinstated.
