### ISSUE TITLE
IDB Goodies: Only package "IDB Method History" is loaded into default DPRO image

### ISSUE THREAD

**Issue by bernhardkohlhaas** [dolphinsmalltalk/Dolphin#18]
After building the most recent image with BootAll.cmd, I've noticed that the only IDB Goodies package that is installed into the DPRO image by default is the package "IDB Method History", even though I do see a lot more of the IDB Goodies under /Core/Contributions/IDB

Any reason, why those other Goodies are not installed into the image?

**Comment by objectarts** [comment]
Bernhard. My thoughts exactly, and you'll see I've just checked in a new master that loss the most important IDB tools (with some fixes to find resources etc). Note, that some of (what I consider to be) the less important packages are not loaded by default.

**Comment by bernhardkohlhaas** [comment]
Nice, a lot more goodies now. :)

What I am wondering is, if the packages that aren't installed by default should go in to a separate directory structure, say "Optional". The reason I am saying this is that I didn't expect that there would be packages in the /Core directory structure that aren't installed into the image by default, when it is booted up.

I'm actually not not that a separate directory structure is the best solution, I am just wondering, what would be a good way to show folks that there are other packages coming with the project that are available, but have to be installed manually.

**Comment by objectarts** [comment]
The current scheme is:

 1) Use Core/Contributions for third party packages that are pre-loaded into the booted images. Either the authors wish that these packages be kept separate from the base or it makes more sense to do so  because they are large blocks of functionality. Core/Contributions are still regarded as system packages and will be distributed inside all end-user images.

2) Optional non-system packages are held in the separate [Contributions](https://github.com/dolphinsmalltalk/Contributions) repository and can be loaded on demand by the end-user.

I'll close this issue for now.

**Comment by bernhardkohlhaas** [comment]
So that means the IDB packages that aren't loaded into the image by default need to be moved into the [Contributions](https://github.com/dolphinsmalltalk/Contributions) repository, correct?

**Comment by objectarts** [comment]
Yes, ideally.
