### ISSUE TITLE
Unable to deploy when TestRunner is open

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#186]
Trying to deploy CommandLineHelloWorld yielded the following:

4:29:25 PM, Tuesday, April 05, 2016: Unhandled exception - a MessageNotUnderstood('ShellView does not understand #dispatchMessage:wParam:lParam:')

ShellView(Object)>>doesNotUnderstand:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
ProcessorScheduler>>callback:evaluate:
InputState>>wndProc:message:wParam:lParam:cookie:
InputState>>isInputReady:
[] in InputState>>pumpMessages
InputState>>loopWhile:
InputState>>pumpMessages
ImageStripperProgress>>progress:
ImageStripperProgress>>monitorProgress
[] in ImageStripperProgress>>forkProgressMonitor
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in BlockClosure>>newProcess
----------------------------------------------------------------------------------------------------

**Comment by blairmcg** [comment]
This is because the TestRunner sits directly under Shell, and the standard ImageStripper only closes what it recognises as IDE tools (see ImageStripper>>closeAllDevelopmentTools). It leaves all other windows open as it is possible to create a simple GUI app by opening the app window and deploying. Obviously this doesn't make sense when deploying a console app - it should close all the Shell windows.

**Comment by blairmcg** [comment]
Fixed - if deploying a console app, then all ShellViews are closed. If deploying a GUI app, then the TestRunner is considered to be a development tool and closed.
