### ISSUE TITLE
Chromium Embedded Framework support

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#205]
I wonder if it's possible to support https://bitbucket.org/chromiumembedded/cef without thinking on ActiveX controls. Is there some example or sample app in the image to get inspiration?

**Comment by blairmcg** [comment]
Certainly possible. It's written in C++, although mentions a C API. If there is a C API that can be wrapped up as a bunch of structs and external library calls, then it is standard FFI work. Working with C++ directly is harder - the best option is likely to be to create a series of COM objects to lightly wrap the underlying C++ objects. Although COM is essentially directly interoperable with C++, it uses a constrained set of conventions that are directly supported by Dolphin, and furthermore you can generate Dolphin wrappers automatically for COM APIs with type libraries. Glancing at it, it looks like a substantial undertaking to me though.
I don't think this issue belongs here though, since any wrapper of this magnitude ought to have a life of its own.

**Comment by fxgallego** [comment]
Ok, this could be labeled as a question more than a task to be done here. IMO this can be closed with your answer.
