### ISSUE TITLE
#queueInterrupt: and #resume: sometimes place calling process into #suspended state

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#229]
We've been having some problems with automated tests just inexplicably stopping--no errors, no VM crash, no waiting process in the Process Monitor, but one test just doesn't finish tearDown and the next one never starts. I traced the problem to terminating a background process in tearDown--sometimes doing this places the active process (the one running tests) into the #suspended state, where it is eventually garbage collected and terminated by the Finalizer.

I haven't been able to come up with a reproducible case for this--it happens some small fraction of the time when running any of a number of tests from our application, but I don't know what they might have in common or why it happens on some runs and not others. Let me know what I can do to help--I haven't tried to build the VM from source, but would be happy to try if there's debug info that you need.

I also _do_ have a closely-related case that _is_ reproducible. I noticed some time ago, in D6 as well as 7, that resuming a process being debugged can have the same effect. For instance, evaluate the following:

```
[[22 / 7 * 9 / 4] repeat] forkAt: Processor userBackgroundPriority.
```

Then open a process monitor, debug the forked process, and resume the debugger. On my machine, anyway, this hangs the image--the Main process becomes #suspended, but because the background process is running 100% of the time the Finalizer never gets to run and terminate it, and the Idler never gets to run and notice that `(main isAlive: inputSemaphore)` is in any case false and start a new one.

I was going to say that pressing Ctrl+F12 successfully interrupts the background process, and one way or another a new Main is started and all is well, but trying it now even that is not the case and I am forced to kill Dolphin with the Task Manager. That might have something to do with the tight inner loop in the forked process, since I'm pretty sure I was able to get out of trouble in a more realistic situation in the past.

**Comment by blairmcg** [comment]
Hi @daniels220, since you aren't building the VM, which version are you actually running?
You can find this out by displaying the result of the following expression: 
   VMLibrary default versionInfo productVersionString
The reason I ask is that the issue you describe sounds similar to issue #72. This was first fixed in VM version v7.0.3-0-g33f53f0. That was published a while ago, but depending how/when you acquired your VM, it may be rather out of date. Incidentally the one in the current setup installer seems to be v7.0.9 (which is also behind the times and is missing a number of important fixes).

The issue with debugging then resuming the main UI process while you are running a background hogging process is interesting. The main process should be unaffected by this - all that should happen is that the background process is pushed back onto the scheduling list again to run when the UI is idle. It does appear to be a bug in the resume primitive, although the debugger invokes this in a different way (passing a schedule list as an argument) so I can't be sure it is related. Still, since that is a repro-able case (even with the latest VM) so investigation may as well start with that, and perhaps the other issue will indeed turn out to be fixed. Otherwise if you don't have a reliable repro, we won't be able to get very far. 

I do find that Ctrl+F12 is reliably breaking into the expression. Although it is possible to write tight loops with #repeat that are not easy to interrupt, this one should be OK as it is performing fractional arithmetic which ends up running quite a lot of Smalltalk code. The interrupt key does seem to have become less reliable than it used to be years ago. I'm not sure why, but it may be due to the compiler generating fewer of the instruction that actually performs the intermittent check to see if an interrupt has been requested. It may be that changing the default from Ctrl+Break (which is represented by a single virtual key, VK_CANCEL), to a function key with modifier hasn't helped either.

**Comment by daniels220** [comment]
I'm running v7.0.20-0-gfcc9d40. (I ran the setup installer initially, and then updated by just copying the files from a newer DolphinVM.zip into the Program Files directory created by the installer.)

Thanks for looking into the debug-and-resume issue. I understand about needing a reliable repro for the suspend-on-terminate case—I'll look into coming up with one as I have time. Based on some comments it seems like it might be helpful to *me* to run a debug version of the VM, so I'll look into that as well.

Some further notes regarding the debug/resume issue:
* Worth noting that what I *meant* was, run that expression, debug *the background process*, then resume it. It turns out, though, that trying to debug the Main process in that circumstance actually hangs the image immediately—the debugger begins to appear but gets stuck as a white rectangle with no contents.
* Long story, but I'm pretty sure my inability to break out with Ctrl+F12 was due to another program—I can now break out of both the original case and debugging Main itself. (I intentionally wrote that loop to perform lots of fraction arithmetic, as I know that something simpler like `[1 + 1] repeat` would likely be impossible to interrupt.)
* I have an effective workaround, which may be useful in debugging the issue: In my images I've changed `process resume: list` to `[process resume: list] fork` in `Debugger>>resume`. This leaves the forked process stuck in the same way, but it's not important to the functioning of the image.
* Having applied the above workaround, it becomes possible to observe what happens to that stuck process. As far as I can tell it stays there without being garbage collected until the process on which #resume: was called terminates *or sleeps*. For instance, if I change the inner loop in the original case to `22 / 7 * 9 / 4. Processor sleep: 1.` and then debug and resume the background process as before, I find that the small `[] in Debugger>>resume` process appears in the Process Monitor in the #suspended state for one refresh, and is gone by the next one a second later. With the original inner loop, that process persists until I terminate the background process myself.

**Comment by blairmcg** [comment]
@daniels220, thanks for the info. I can see the problem with the debug-and-resume issue. It is specific to the case where the resume primitive is passed the "list" into which the resumed process should be placed (usually this is one of the lists owned by the ProcessorScheduler instance, Processor, but it could be a Semaphore, as it is possible to attach a debugger to a process waiting on a Semaphore). The bug in the code is very obvious, and would always mean that the active process at the time of the primitive call would become suspended and then die if unreferenced. I guess that this has gone unnoticed for so long because (a) the primitive is only called this way the debugger when you do a Go/Detach (or close the debugger, depending on whether that is configured to terminate-on-close, which is what I usually do), and (b) when called from the debugger the UI process will be making the call. Since the system is designed to allow the UI process to die and be replaced, the bug usually has no adverse effect. In the case where you are running a background process that starves the idle process, then the logic that detects that the UI process is not running will not itself get to run. Anyway, it is easily fixed and I will release a new VM with the fix over the weekend sometime.
Problem is, fixing that will not fix your original issue, and I cannot see an obvious way in which the normal Process>>resume call would cause similar behavior. That doesn't mean it isn't there, but it is not immediately evident by inspection. I might spot it yet, but if you can get your test down to a simple case that shows the behavior, even intermittently, then that would certainly help.

**Comment by daniels220** [comment]
Thanks, that's great—looking forward to removing my `[process resume: list] fork` workaround once the new VM is released. And yes, you are quite right about why this has gone unnoticed—I myself missed it for almost three years before finally encountering a situation where I had a background process that would run for long enough (at least several minutes) to make it clear that the UI would not unfreeze until it finished.

Another bit of clarification about the original issue: The problem there is not in `Process>>resume` but in (I believe) `#queueInterrupt:with:` (though I've only seen it specifically from the call in `#terminate`). In any case, I'm working on a test case but haven't had any success just yet—I'll let you know if/when I come up with something.

**Comment by blairmcg** [comment]
I'm closing this because without a repro it is not actionable. There have been changes in this area anyway, so it may even have been fixed.
