### ISSUE TITLE
Set up chat room for live communications

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/Dolphin#23]
There seem to be (at least) two instant messaging rooms that are popular for teams; [HipChat](hipchat.com) and [Slack](slack.com). There's a comparison between the two [here](http://slackvshipchat.com). Although Slack appears to come out on top, I think we should try [HipChat](hipchat.com) first for two reasons:

1. Guest access (i.e. not via invite) requires a paid account in Slack
2. Only the last 1000 messages are archived in a free Slack account, whereas HipChat saves everything (I think).

I've created a HipChat room with guest access that you can [sign up to here] XXXX - I've changed my mind - let's try [Gitter.im](https://gitter.im/objectarts/dolphinsmalltalk?utm_source=share-link&utm_medium=link&utm_campaign=share-link) first.. see below.

For the moment, while we are evaluating the room, let's only advertise it here or by inviting known developers who will be interested in expanding/contributing to the core product. Later on we can post it up to comp.lang.smalltalk.dolphin and I'll place a link on the website.

**Comment by krodelin** [comment]
There is also [gitter.im](https://gitter.im/) - not quite sure about the pros/cons though.

**Comment by objectarts** [comment]
@krodelin .. ah yes. And the advantage of that is not having to create another account but reusing an existing GitHub account I guess. Let's try that first. [Here's the link] (https://gitter.im/objectarts/dolphinsmalltalk?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

PS: Are you going to join.. I have a question to ask you?

**Comment by krodelin** [comment]
Of course I'm joining. I just bought a Windows 7 license today just to be able to do Dolphin again :-)

Can't wait for the installation to finish.

**Comment by rjsargent** [comment]
Since you're using github, why ignore gitter?



<div>-------- Original message --------</div><div>From: Object Arts <notifications@github.com> </div><div>Date:2016/01/07  12:28  (GMT-08:00) </div><div>To: dolphinsmalltalk/Dolphin <Dolphin@noreply.github.com> </div><div>Subject: [Dolphin] Set up chat room for live communications (#23) </div><div>
</div>There seem to be (at least) two instant messaging rooms that are popular for teams; HipChat and Slack. There's a comparison between the two here. Although Slack appears to come out on top, I think we should try HipChat first for two reasons:

Guest access (i.e. not via invite) requires a paid account in Slack
Only the last 1000 messages are archived in a free Slack account, whereas HipChat saves everything (I think).
I've created a HipChat room with guest access that you can sign up to here.

For the moment, while we are evaluating the room, let's only advertise it here or by inviting known developers who will be interested in expanding/contributing to the core product. Later on we can post it up to comp.lang.smalltalk.dolphin and I'll place a link on the website.

**Comment by objectarts** [comment]
Richard, if you re-read the above you'll see we are using Gitter!! [Here's the link] (https://gitter.im/objectarts/dolphinsmalltalk?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

**Comment by rjsargent** [comment]
Yeah. I noticed the rest of the conversation *after* throwing in my zero cents worth.

<div>-------- Original message --------</div><div>From: Object Arts <notifications@github.com> </div><div>Date:2016/01/07  13:37  (GMT-08:00) </div><div>To: dolphinsmalltalk/Dolphin <Dolphin@noreply.github.com> </div><div>Cc: Richard Sargent <rsargent@5x5.on.ca> </div><div>Subject: Re: [Dolphin] Set up chat room for live communications (#23) </div><div>
</div>Richard, if you re-read the above you'll see we are using Gitter!! Here's the link.

**Comment by objectarts** [comment]
### We are using [Gitter](https://gitter.im/objectarts/dolphinsmalltalk?utm_source=share-link&utm_medium=link&utm_campaign=share-link) for now.
