### ISSUE TITLE
Opening and closing <MessageBox>es is very slow when a background process is running

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#230]
Display the result of the following:

```
continue := true.
[[continue] whileTrue: [22 / 7 * 9 / 4]] forkAt: Processor userBackgroundPriority.
time := Time millisecondsToRun: [MessageBox notify: 'Why am I so slow?'].
continue := false.
time.
```

When the MessageBox appears, press Enter/Return immediately to dismiss it. For me, it takes about two seconds for the MessageBox to appear, and another three after I dismiss it for the expression to finish (so the value of `time` is somewhere around 5500). If I replace `MessageBox notify: ...` with e.g. `Prompter prompt: ...`, the prompter appears and completes immediately—`time` can easily be 250 or less. If I make the MessageBox task-modal, the problem goes away as well.

Putting some traces in the code, it appears that all the time is being spent in `#overlappedMessageBoxIndirect:`, but from within the image I cannot tell how much of this is in the MessageBoxIndirect() call itself, and how much might have to do with the overlapped-call mechanism or some other side-effect of opening the MessageBox from a separate thread. Opening two MessageBoxes in rapid succession shows no improvement for the second one, so it seems unlikely to be some kind of startup overhead for the first GUI call on a new thread.

**Comment by blairmcg** [comment]
@daniels220, there are two things at play here:

1. There is a bug in the process scheduling in relation to overlapped calls where sometimes the VM does not switch to a higher priority waiting process. This is shown by an assertion in the VM that fires when running some of the overlapped call tests in the VMTest class against a debug VM. This can be fixed.
2. Detection of a message being available to process when a background process is hogging the CPU is achieved by sampling the input queue. The interval at which this sampling is performed is a trade off between overhead and responsiveness. You can read more about this in the comment for the method InputState>>primSampleInterval:. You'll be able to observe the effect of varying this on your test expression by evaluating "SessionManager inputState setSamplingInterval: 10". You should find this makes things less sluggish on the test. The default value for this was chosen based on measurements made on much slower machines some years ago. The default may not be entirely appropriate today.

As a workaround you may want to try making your background process a bit more of a community citizen by inserting deliberate yields of control (i.e. like co-operative multi tasking). This could be by periodic short sleeping, or simply "Processor yield". The yield operation won't slow down your process much if there is no other work to do, although I wouldn't put it in a very tight loop like your example as the number of cycles required just for it to check whether a context switch is needed might be high in relation to the work you are doing.

**Comment by daniels220** [comment]
Interesting! My suspicion *was* that (1) was responsible for most of the delay—it's hard to see how sampling the input queue "only" every 60ms would cause delays of close to two seconds. And yet reducing that sampling interval as you suggest does speed things up—at 10 the whole example above takes about 1.75 seconds, at 5 I can get it under a second.

I'm curious to understand more—can you say more about how the lag can be proportional to, but orders of magnitude longer than, the sampling interval? And what is it about both Dialogs (both in-proc and normal) and *task-modal* message boxes that changes things so dramatically?

(Regarding the workaround of `#yield`—in my case the most common background process is STS comparing a large number of packages, which admittedly need not stop me from inserting strategic `#yield` calls, but has made me think twice about doing so willy-nilly. For the moment I think lowering the sample interval will work fine—this doesn't come up all that often, and the difference in annoyance between one second and five is huge.)

**Comment by blairmcg** [comment]
Well one would have to investigate with Spyxx and (probably) by inserting some tracing to see precisely what is going on, but a reasonable hypothesis would be that it is due to interaction of the OS context switching caused by launching the message box on a background thread with a parent window that is on the Dolphin thread (which causes message send traffic between the threads) and the way the InputState detects the UI being idle. When you are launching a dialog (or task modal message box) on the same thread, the message queue traffic will probably prevent the message loop from becoming empty, whereas this may be happening here.
This explanation is a theory that needs testing, but it does seem plausible given the numbers. If it takes two seconds to open or close with a sampling interval of 60ms, and if only one message is processed per sampling interval, that would mean around 33 messages were processed in total. That isn't an unreasonable number (try watching it with Spyxx to monitor the message traffic on all threads in the Dolphin process and you'll see what I mean). Now if you reduce the sampling interval to 10mS, those same 33 messages would be processed in 330mS.

**Comment by daniels220** [comment]
That makes total sense that inter-thread message traffic is the key. Thanks for the clear explanation! If I find the time, I'll try checking it out with Spyxx as you say, but I'm pretty sure you're right. As a result I'm thinking this isn't fixable beyond the workarounds already described—any mechanism that would work better here would probably be able to replacing the sampling entirely, and I'm sure you've looked quite thoroughly for such an alternative :).
