### ISSUE TITLE
Formulate a Dolphin workflow

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/Dolphin#27]
We need to come up with a workflow for D7 that caters easily for the  following:

* There will likely be two classes of users. Those who wish to work on the core Dolphin product (let's call them **coredevs**) and those who want to treat Dolphin as a tool to build other projects (called them **userdevs**).

* Users may be in both categories (**userdevs** may make changes to the core system during their project work that they can easily contribute back as **coredevs** into the Core).

* We can assume that **coredevs** will always use GitHub. **userdevs** may not. They may chose to use another source control system like STS, git, mercurial or something else.

## Workflow A - Emulate D6
One proposal is to emulate the Dolphin 6 workflow. D6 used a read-only "template" core image stored in _Program Files_ that could be duplicated (unlocked) into any **\User** directory. All core packages would exist in the image but when externalised from it (by package save) would appear as a directory structure under **\User**. Core Dolphin packages would appear under **\User\Dolphin** and user packages would be, say, under **\User\My Projects**. 

Typically the **userdev** would externalise packages from their image and manually place them into a SCCS. In such cases they would probably write a load script to install their project packages into a new image when required. The DPRO STS system would help greatly in this respect since it has the concept of **Projects** that can load versions of many packages to bring any project into the image.

A **userdev** working on multiple projects at once might choose to work in a single image, or multiple images in **\User** or maybe in multiple images in separate user directories (**\User1**, **\User2**).

### Workflow A - for D7

1) The Dolphin core is downloaded into **\Dolphin** (by **coredevs**) from GitHub or (by **userdevs**) as a ZIP with the images prebuilt. GitHub users will have to boot the images before use.

2) A working DPRO image is copied to **\User**. This effectively (as it stands now) makes Dolphin think that all the core packages actually live under **\User\Core**. The link with the original **\Dolphin\Core** directory where the Git information is held is lost.

3) A **userdev** creates a project and the package source is held in **\User\Projects**. This may be a Git directory if the **userdev** is using Git/GitHub or it might be held in STS. 

4) Any changes that are made to the Dolphin core will be saved to PAX files under **\User\Core**. If the Source Browser is used to write out changes only, then it is easy to see what is changed because only the changed packages will be present.

5) A **userdev** reloading a project will have to invent a loading scheme (ST fileIn?) to load all the changes into a virgin image. Of course, STS would make this significantly easier.

6) A **userdev** who is also a **coredev** will want to apply the changes saved under **\User\Core** back into the **\Dolphin\Core** directory (the GitHub repository) and then submit a pull request. This is the tricky and untidy bit. Two possibilities come to mind:

a) Copy the **\User\Core\** sub-directories to **\Dolphin\Core** and then commit them using Git as normal.

b) Copy a virgin DPRO image from **\Dolphin** to **\User**. Load the project contents under **\User\Core** into this image and then copy the DPRO image back to **\Dolphin**. The Source Browser can then save out the core changes, which can be committed as usual.

I think this flow will work, although the copying of core information back and forth between **\User** and **\Dolphin** directories is unpleasant. It also occurs to me that such a flow will probably work better using STS as a sort of intermediate repository between the image and GitHub (or any other SCCS). This is not ideal because it would be yet another tool barrier for a new user to learn when getting started. This might not be appreciated if the **userdev** just wants to use GitHub anyway. Some additional Git related features in STS might make this more palatable.

## Workflow B - Users never change Dolphin core

This workflow is identical to Workflow A above except it avoids the tricky moving of modification back from the **\Work** directory structure back to **\Dolphin** by _disallowing_ them. So as above except:

1) Whenever a **userdev** find that a change is needed to the Dolphin core files they must stop and return to the **\Dolphin** directory and make the changes in a (DPRO) image there.

2) The Source Browser is used to emit the core changes under **\Dolphin** and GitHub can then be used to commit them and submit a pull request (if the this is a **coredev** role).

3) A new core DPRO image is built using **BootDPRO** or **BootAll** and copied to the **\Work** folder.

4) From there, the **userdev** reloads projects and continues work with the new Dolphin core changes in place.

This is perhaps a neater workflow that A, especially as **userdev** changes to the Dolphin core should be rare. Remember, using Dolphin's package system and _loose methods_ it is still possible to extend the core classes without having to modify the core packages.

## Workflow C - Clone Dolphin Core for each project

The idea here is to have a full **\Dolphin** installation for each project (or set of projects).

1) The Dolphin core image is unzipped or cloned into **\User\Dolphin**. Again **coredevs** must use GitHub and will have to build the product images using BootAll.cmd.

2) User project packages are held under **\User\Dolphin\Projects** and sit alongside the **Core** directory. The _.gitignore_ file will have to be modified in **\User\Dolphin** to ignore files under **Projects** - these would be cloned from a separate user GitHub repository (if using GitHub).

3) During development the user makes changes to his/her own packages and possibly to core packages.

4) The Source Browser is used to write out source changes to PAX files under **\User\Dolphin\Projects** and **\User\Dolphin**. 

5) Git can then be used to push changes to the core and project repos separately.

**The above workflows are proposals. Comments and alternative proposals are welcome.**

Once we have one (or maybe two) definitive workflows we should publish them on the Wiki.

**Comment by fxgallego** [comment]
For me, the workflow C is OK. **coredevs** should not use prebuild images. In order to ensure this rule the git commit sha used to build the image should be stamped whenever possible (git installed and the build is running from a git initialized folder).

I think it's very convenient to have the facility to commit to both core or user repo from the same image. Maybe it's a little strange as a **userdev** to have this facility. The normal case (in other OS languages) is more like A or B. I'm actually using A (D7) and hate the duality and sometimes I get confused and close to lose core changes.

Another nice addition will be having details in the "Source Browser" about which repo impacts each change. I'd like to avoid anything related to sts. Yes, it was a great tool but git is a lot better and we only need to adapt our tools and workflows to have the sts functionality plus the benefits of git.

**Comment by jgfoster** [comment]
I'll describe the approach I'm taking so far (as a long-time **userdev** and less than a week as a **coredev**).
* Use Git to clone Dolphin to some place (in my case, ~\Documents\Dolphin) and use this for **coredev** work.
* Clone my project ([Jade](https://github.com/jgfoster/Jade)) to Dolphin\Jade and use this for **userdev** work. 
 * As this subdirectory is a Git checkout, it is ignored by Git when handling the Dolphin checkout. (There is no need to have an intermediate Projects directory that is explicitly ignored.)
 * All smalltalk images in the Dolphin directory except DBOOT are [ignored](https://github.com/dolphinsmalltalk/Dolphin/pull/26) so it is possible (with appropriate care) for this directory to be the root for not just **coredev** work, but **userdev** work as well (and the structure visible from within the image matchs that on the file system). 
 * By being in the Dolphin directory, finding and loading add-on libraries and frameworks will be quite natural.
 * With this approach the Dolphin directory can be parent of multiple projects, each sharing an STS repository in Dolphin\Repository (if desired) and/or their own Git checkout.
 * Because the boot script allows specification of a [non-Dolphin product](https://github.com/dolphinsmalltalk/Dolphin/pull/20), I can create a [boot script](https://github.com/jgfoster/Jade/blob/for_Dolphin_7/BootJade.cmd) that looks very much like the Dolphin boot script but instead builds my development image. Thus, rather than a custom .st script to build my development image, I let a [subclass](https://github.com/jgfoster/Jade/blob/for_Dolphin_7/sources/Jade.cls) of DolphinProduct do that for me.
 * I anticipate proposing some changes to DolphinProduct (and subclasses) to support better customization of **userdev** development images.
 * I'm not sure where things will go with building up a runtime image, but it could be from here as well.

The primary limitation (so far) of this approach is that I need to take care that my application work (as a **userdev**) avoids any interaction with the current working directory (Dolphin) because that would spill over into the **coredev** activity. This seems like a very minor issue cost for the benefit of having everything in one place with a natural layout (my project is adjacent to Core in the image and in the file system). Another benefit is that changes I make to Dolphin as **coredev** are immediately available to my application(s) as **userdev** (with a simple reboot of my development image).

**Comment by krodelin** [comment]
I'd go for **workflow C** with some additions: Instead of cloning **Dolphin core** for every Project I would have multiple  projects/folders under `Projects`.

If the **userdev** is willing to use `git` she/he could even keep different projects in different git branches.

Food for thought: I think using (symlinks) or `git` *branches* is something we could use to link **coredev**/**userdev** together. Although I'm not quite sure whether it's a good idea to *force* a **userdev** to use `git`. This is out of question for **coredevv**s though. Still (soft/hard) linking files might be an option. The advantage mit be space savings (no copying) and keeping git intact - even if linked into a **userdev** env.

This is based on the assumption that changing core packages (even third party ones) is not something a **userdev** will do on a regular basis.

**Comment by jgfoster** [comment]
A current limitation is that because things can't be put in the application's current working directory (Dolphin), the runtime will end up with a subdirectory where everything is based (including further subdirectories). So my development environment has the image in Dolphin with everything else in Jade:
- Documents\\**Dolphin**\Jade\bin

While my runtime environment has the executable in Jade and everything else in Jade\Jade:
- Program Files\\**Jade**\Jade\bin

I'd prefer to have my development image in my project directory (Dolphin\Jade). This would require some changes to the boot process and presentation in the System Browser. I can investigate this and contribute any refinements to the process I find useful. Until then I'll essentially follow *Workflow C* as I described above.

**Comment by jgfoster** [comment]
I've been able to make further refinements that address my issues (described above). With [this pull request](https://github.com/dolphinsmalltalk/Dolphin/pull/28) I'm able to boot a development image in a subdirectory that is under Git control. Thus, no need for the Projects directory and no need for **userdev** to work in the Dolphin root directory. The primary impact is that the Package Tree in the System Browser and in the Package Browser show two roots, one based on the image and the other based on the full path name to Dolphin.

**Comment by jgfoster** [comment]
After experimenting with some alternatives, I'm partial toward the approach of building a development image in a subdirectory (supported by [this pull request](https://github.com/dolphinsmalltalk/Dolphin/pull/28)). 

When Dolphin releases were rare, then treating the DPRO image as static was fine. While it was a good practice to be able to reload application code (packages) into a clean image, it wasn't a common part of my workflow (once a quarter or so). Most of my work was in the image with STS.

With Dolphin 7 being under active development and changes being immediately available, rebuilding my development image becomes much more common. With Dolphin introducing `git` into the process, it becomes attractive to rethink my source code management practices as well. To maintain consistency and reduce the cognitive load, I'd prefer to have one boot/build process that manages my development image and process. This gives me a way to build up *my* development image in one step.

**Comment by objectarts** [comment]
@krodelin, @jgfoster, I've been working on a variation of the workflow ideas proposed by @jgfoster to do with allowing images outside the Dolphin folder to share the GitHub core files. My current branch (which I think I shall check in) uses the command line as follows to allow the Dolphin core files to be shared:

dolphin7 DPRO.im7 -n \MyProjects\BatOutOfHell -d

This clones (-n="new") the DPRO image to \MyProjects\BatOutOfHell.img7 while at the same time making it share the current core system files (-d="Dolphin") under the installation directory. The -d option actually takes an optional path parameter (which is the location of the core files relative to the installation folder). Using -d on its own defaults to "." which means use the current Dolphin installation directory.

This works okay, but I thinkI've just realised that there is a fundamental problem with ANY sort of sharing of the Github source directories between multiple images. The problem is that if there are two or more images sharing the same core sources then it is very likely that one could overwrite changes to the core made by the others at an earlier. Hence, if there are any changes to the shared core then all sharing images must be immediately be rebooted to avoid potential problems, I think.

Unless I'm missing something, I think we have to disallow sharing of the core files between multiple images (if by convention if nothing else).

What do you guys think? And if you agree, should I leave the -d option in or remove it?

**Comment by jgfoster** [comment]
@objectarts, I appreciate the option to reset the path to the Dolphin directory. While you are correct that editing the sources from multiple images could be a problem, this problem is not created by allowing images to be in alternate directories. This problem would occur even if all the images were located in the Dolphin directory, so it isn't the -d option that creates the risk. The option has value and does not introduce (much) risk so I would like to see it preserved.

**Comment by fxgallego** [comment]
@objectarts about the -d option maybe we can add support in the package manager to show when a root is not clean (git status). Most IDE's does this in background. Another option would be a notification when a new image is cloned from a not clean root or maybe to require a -f (force) option to allow create new images when not clean (same as git when you try to delete a not merged branch, you must use -f option).

**Comment by brunobuzzi** [comment]
I will go with Workflow 3 the last mentioned by @objectarts or  @jgfoster. 
I do not think that changes in the Core are so frequent...may be in some special time it could be frequent but for now....

**Comment by FunctionPoint** [comment]
For me also a vote for a variation of Workflow C.
For coredevs a full clone of the github tree is OK, including prebuild VM exe, 
to be cloned as desired for new projects.

For userdevs, keep it as simple and userfriendly as possible:
Make a downloadable zip file with only:
- VM and needed executables and DLLs.
- Pre-build PRO image.
- Contribution packages (not loaded in image by default) in separate folder.
  Core packages can be expported from the image when needed.

For the userdevs ZIP file, modify the build / distribution process like this:
- Generate this ZIP file as part of the BootAll.cmd procedure.
- Make this ZIP file available on the Object Arts website *with a _stable_ version*.
  Prevents userdev disappointment with instability due to coredevs.
  Pharo Smalltalk provides the right example here, IMO.
- Keep it simple: Remove building of other then PRO image builds (e.g. Core and Community).
  Make the default name Dolphin.img7 (not DPRO.img7) that is loaded by default by the VM.
  A Dolphin image should be a well defined dependable entity. Contributions go in package folders.

That was it. Wat do you think?
Was going to implement this myself but cannot find the time soon...

Cheers, Richard

**Comment by objectarts** [comment]
@FunctionPoint, you know that the **userdevs** build is available here: https://github.com/dolphinsmalltalk/Dolphin/releases. This is the stable release (7.0.1). It will soon be linked off the website but some other changes to Getting Started are needed first. What you get is a Windows setup installer with pretty much what you're asking for. There will also be an "unstable" build available too at some point.

**Comment by FunctionPoint** [comment]
Hi Andy. Domewhat red-faced I have to say I did not know that.. :-0 :-). 
And with a nice Windows installer.
Please add the download link to it on object-arts.com soon.
Other points in my suggestion still apply.

**Comment by FunctionPoint** [comment]
Hi Andy / all, 
I've made a simple script called "BuildRedist.cmd" that creates a "Redist" subfolder and copies all needed redistributables to it, with the DPRO image renamed to "Dolphin.img7". It also creates a single ZIP file "Dolphin7.zip" with the contents of this folder for easy distribution.
This a handy for me to easily disribute an application based on a current GitHub branch. It does not create a windows installer. That is not desired because there may be modified VM versions. So it's a little tool for CoreDevs that also make UserDev applications.
Would it be desirable to integrate this into the Buid*.cmd scripts? Or would that be to "messy"?
