### ISSUE TITLE
Strange behaviour in #identityHash

### ISSUE THREAD

**Issue by Sergiomdf** [dolphinsmalltalk/Dolphin#289]
I've detected a strange behaviour in #identityHash that produces a performance problem for some classes of the software produced by the company I work for.
In both Dolphin 7.0.5 and 7.0.32 the problem can be reproduced using Announcer class.

The testing code requires [#groupBy: method](https://github.com/dolphinsmalltalk/Dolphin/files/682530/groupBy.st.txt) (I think this is the Pharo implementation but I've attached a fileout, just in case).

#identityHash comment says it answers a 16-bit Smallinteger, so it's easy to calculate the collisions for 150K objects, in the best case:

    (150000 / 65535) asFloat "2.288853284504463"

And here's the code to verify the collisions, using Object class:

    (((((1 to: 150000) collect: [:each | Object new])
                groupBy: [:each | each identityHash]
            ) values collect: [:each | each size]
        ) groupBy: [:each | each yourself]
    ) keys "a Set(2 3)"

So, in the case of Object, there's a good hash distribution.
Now let's try the same for Announcer:

    (((((1 to: 150000) collect: [:each | Announcer new])
                groupBy: [:each | each identityHash]
            ) values collect: [:each | each size]
        ) groupBy: [:each | each yourself]
    ) keys "a Set(10 9)"

Wow. Something is wrong here. If you evaluate the answer of #groupBy: (first 2 lines excluding some opening parenthesys), you can see one every four smallintegers are used as hash for this class, producing a big performance problem when using Sets.

I know we can avoid the problem redefining #= and #hash for our classes that have this problem (I think we can without getting into a worse problem for all, or most, of our classes), but is there something we can do to avoid new classes behave like this?

**Comment by blairmcg** [comment]
The identity hash is a 16-bit pseudo random number generated using a minimal standard LCG. It needs to be fast because in the current implementation the identity hash for an object is assigned when the object is created, even if never used. Given the prioritisation of speed over randomness one wouldn't necessarily expect it to give the best of distributions, but looking at it there is a fairly obvious bug in that it is a 32-bit generator but is using the low-order 16-bits:
```
inline hash_t ObjectMemory::nextIdentityHash()
{
	m_nNextIdHash = 1664525L * m_nNextIdHash + 1013904223L;
	return static_cast<hash_t>(m_nNextIdHash & 0xFFFF);
}
```
Presumably I put in a bit-and to avoid the slow integer division required to do the modulus operation of the LCG, but in hindsight this suffers from the fact that the low-order bits of LCGs are not very random, so it would be better to take the high bits, i.e.
```
inline hash_t ObjectMemory::nextIdentityHash()
{
	m_nNextIdHash = 1664525L * m_nNextIdHash + 1013904223L;
	return static_cast<hash_t>(m_nNextIdHash >> 16);
}
```
This should have about the same perf characteristics as well. It would be easy to try out if you are will to compile your own VM. Otherwise I will look at it at some point soon.
Another improvement would be to compute the identity hash lazily on first access, which might allow a slower but better generator to be used. Given the limitation of only 16-bits being available to store the hash, however, I'm not sure that this would be worthwhile from a hash distribution perspective, although it would avoid the (small) overhead of calculating the hash on every allocation.

**Comment by blairmcg** [comment]
I just typed a long explanation of why the perf is poor with Announcer (in summary, because you are actually allocating 600K objects, rather than 150K), and then closed the browser tab by mistake.
Try VM v7.0.35. This allocates an identityHash only to those objects that need it, which results in the same behaviour for Announcer as for Object, and in an IdentitySet gives an average number of probes per element <1.7, which is better than your theoretical best case (look at `IdentitySet>>hash:max: to understand why):
```
((1 to: 150000) collect: [:i | Announcer new]) asIdentitySet averageProbesPerElement	
```
Repeating the above experiment with `asSet` will clearly demonstrate why #identityHash is unsuitable as a hash function for very large Sets, Dictionaries and LookupTables. If you encounter that, either override #hash as you suggest, or use one of the pluggable collections that externalise the hash function and equality comparison.

**Comment by Sergiomdf** [comment]
For the company I work for, I've made a #hash redefinition in a single class (the one with lots of instances), but I've detected that the problem occurs for an entire hierarchy (588 classes).
Instead of waiting for performance trouble in another class or trying to make a custom hash for the entire hierarchy (that may not work in all cases), do you think it would be possible for the VM to provide a #hash32 [1]? Would this be safe or is there any known limitation that need 16-bit hashes for basic / primitive operations?

[1] So we can redefine #hash as «^self hash32» in company's objects.

**Comment by bernhardkohlhaas** [comment]
@Sergiomdf ,

I'm not @blairmcg , but from what I see in the VM code the 16-bit hash is actually stored in the Object table for every object (field m_idHash in template class TOTE, see: https://github.com/dolphinsmalltalk/DolphinVM/blob/75bbb944d785491a62803ec740fe9e005a7b1d42/ote.h )

So in order to boost the hash for all objects to 32-bit you have to increase the size of each entry object table. Not sure, if this is efficient, because it needs to be done for ALL objects, regardless of the class.

Would it work for you to store the 32-bit hash in an instance variable of your class hierarchy? You could then write a C-function with the32-bit hash and bind via a DLL (or perhaps coding in Smalltalk is good enough) and store the hash in that instance variable.

**Comment by blairmcg** [comment]
Yes, Bernhard is right. There are only 16-bits available to store the identity hash, and since it has to be temporally invariant (i.e. unchanging for the lifetime of the object), it has to be stored somewhere. 
If you need a general purpose solution and have an appropriate base class to implement it in, then generating a random integer using an appropriate random number generator and storing it in an inst var sounds like a good approach. Aside from Bernhard's suggestion some other options are:

1. Multiply up the identityHash to give the hash (i.e. as IdentitySet>>#hash:max: does). This will distribute the values, so although it will still result in collisions and probing, the number of probes won't get ridiculously long. e.g.
```
hash
    "Hmmm, maybe Object>>#hash should be implemented like this anyway"

    ^self identityHash bitShift: 12
```
2. Create a 30-bit hash by combining together (say) 14-bits of the identity hash of the class with the identity hash of the object itself. This would be easy to implement in Smalltalk and run fast - don't do it exactly as the comment in Object>>identityHash suggests, or you will get a LargeInteger value. In order to keep it small, you need to limit to <= SmallInteger maximum (30 bits). Something like this:
```
hash
    ^((self class identityHash bitAnd: 16rFFF8) bitShift: 14) bitOr: self identityHash
```
There are a couple of caveats relating to this, however: 
1. this hash value will change if you use #becomeA: to change an objects class. Probably not an issue, but worth bearing in mind if you have previously been relying on #identityHash, as that is guaranteed not to change (see above), 
2. it won't help if you have large monoculture collections as obviously only the bottom bits of the hash will vary, so it will be no different than just using the identityHash.

**Comment by blairmcg** [comment]
Fixed by recent changes in the VM and by commit f0bdf78, which multiplies up the 16-bit identity hash to achieve better distribution in large sets.
