### ISSUE TITLE
Translate stack dump to method source offset

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#352]
An error log provides a Smalltalk stack that includes the method being executed. It would be helpful to know where in the method we are currently executing. Yes, we know which message is being sent, but it might be sent in multiple places.

**Comment by blairmcg** [comment]
This could be added, but the VM "crash dump" already provides a far more useful log for debugging issues in deployed apps, including the method arguments, etc.

**Comment by jgfoster** [comment]
Is the "crash dump" the error log (see #353 for an example)? If so, then I need help interpreting cf, sp, bp, and ip. Is there a way to use the 'ip' to look into the CompiledMethod and figure out which message send is current? If this is something other than the error log, then how do I find it? Thanks!

**Comment by blairmcg** [comment]
Yes. For this purpose you can probably ignore everything except ip, which is an index into the method bytes. For completeness the other values are:
- cf =  the address of the calling frame in the stack.
- sp = saved stack pointer of the frame (i.e. points at top of stack for the frame)
- bp = base pointer for the frame (i.e. points at start of arguments)

 If you inspect a method (e.g. select a method in a browser and Ctrl+I), you can view the assembly and locate the send, which will be that immediately preceding the reported IP. Here's an example from that log:

`{1A040064: cf 1A040049, sp 1A04007C, bp 1A040064, ip 16, Process>>shutdown}`

And the disassembly of the `Process>>shutdown` method is:
```
Normal, 0 args, 8 literals

	1	Push Inst Var[13]: debugger
	2	Jump If Nil +4 to 8
...[snip]...
	13	Pop
	14	Push Self; Send[6]: #primTerminate with 0 args
	16	Push true
	17	Special Send #==
	18	Jump If False -6 to 14
	20	Return self
```
From this you can see that the instruction immediate preceeding ip 16 is the self send of `#primTerminate:`.

You may want to try the class browser DebugInfoPlugin. Find the class and run the expression in the class comment. This will add another tab to new (not existing) class browsers that will show the disassembly and a list of significant IP's on the left that the debugger uses to map back to source. As you select ip's from the list the plugin will show you the relevant range of source code and the corresponding send in the disassembly, e.g:
![image](https://cloud.githubusercontent.com/assets/15128107/24321038/914c32ca-113a-11e7-8043-67ca2593941c.png)

As to whether the dump could include source information, that probably isn't practical. The VM doesn't have this information currently, and neither is it available in a typical runtime image. More concretely mapping from IP to source requires the "text map" which only the compiler is able to provide - you can see the compiler text map in the inspector on a method, or in the DebugInfoPlugin as described. The textmaps could be stored, but that seems a heavyweight solution.

One could also write a tool to interpret the crash dump file, and now I think about it Chris Uppal did that some years ago. I believe the tool was called "Ghoul" (which is why I remembered it), and I can see there is a copy of it here: https://github.com/fxgallego/Chris-Uppal-Goodies/blob/master/CU%20Ghoul.pac

**Comment by jgfoster** [comment]
The DebugInfoPlugin is an excellent solution. I would be looking at any method in a code browser, and didn't really anticipate that the additional information would be added to the error log. Thanks for pointing me to this tool.
