### ISSUE TITLE
Cursor flash in scintilla editors

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#407]
There is a problem with the cursor in editors that are using scintilla.
The cursor changes from iBeam to arrow all time while the mouse pointer is over the client area of the control.
This is with the last image and Windows 10 insider edition. Have anyone noticed the same?

I think that it should be easily solved defining in the right place something like:
```
onGetCursor: aSymbol 
	"The named area of the view associated with the receiver has been hit. Answer the
	appropriate mouse cursor or nil to accept the default."

	^Cursor iBeam
```
But I don't know why this started to happen because previous versions doesn't requires anything special. Maybe the new scintilla requires this or a change made in somewhere causes this.

**Comment by rejurime** [comment]
I have the same problem in Windows 10 professional.

**Comment by blairmcg** [comment]
It's actually caused by the "SeeingTheObjectsInside" splash window, which sets the global cursor to the arrow when it is dismissed. This then causes the Dolphin cursor handling to continually try and override any other cursor that has been set back to the arrow.
You can temporarily fix this problem by clearing the global cursor - not entirely easy to do since it is set/restored when evaluating an expression. However this will work:
`[Cursor current: nil] postToInputQueue`
I'll send a PR to fix it properly.
