### ISSUE TITLE
Extra big icons in SmalltalkSystemShell

### ISSUE THREAD

**Issue by rejurime** [dolphinsmalltalk/Dolphin#411]
In SmalltalkSystemShell when you press the Views button the icons change the size but if you press one more time being in Details the following size of icons looks like this

![ds7](https://user-images.githubusercontent.com/7131403/28173890-398212c0-67c6-11e7-936b-2996bd20a954.PNG)

And if you open the list there is nothing selected, then if you press once again, the thumbnails will be selected.

**Comment by blairmcg** [comment]
It does that because its going into 256x256 icon mode (which has been removed from the dropdown, but is one of the standard view modes supported by IconicListAbstract, so it cycles through this when repeatedly pressing the view mode button), yet the system shell has had a fixed icon spacing of 120@120 set. Obviously that spacing is insufficient for 256x256 icons. 
If you use the visual object finder to find and inspect the list view in the system shell, and nil out the iconSpacing aspect, you should find it works as expected.
Obviously setting a fixed spacing isn't the ideal way to increase the margins around the icons, as it doesn't really work sensibly in any of the non-list modes than the default.
I'm not sure it is worth fixing though, other than by just removing the toolbar button so the mode cannot be changed.
