### ISSUE TITLE
New image command line option (-i) saves with pending UI events that error later

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#417]
I have a script that generate a DPRO image with various extra windows open (including an IdeaSpaceShell with a SystemBrowser). That script works fine and opening the saved image works fine. I have a second script that opens the DPRO image, saves it with a new name (-i JadeDev), and then exits (-x). That script finishes without error but subsequent attempts to open the second image almost always results in an error (that can be dismissed without further harm). 

The error is the same each time a particular image is reopened, but will often change when the second script is rerun. The stack shows a UI event sent to an invalid widget (e.g., a null or 16r0 handle) or an attempt to call a function in a library (DLL) that doesn't exist (see below for a Canvas with a null handle). Since the error is the same each time the same image is reopened, I suspect that the pending event is in the queue at the time of the image save. 

It seems that we should wait till the event queue is empty and the system is quiet before the save. We could also view this as a startup problem in which saved events should be treated with some skepticism. 

2:11:05 PM, Monday, July 17, 2017: 'The specified procedure could not be found. (16r7F: The specified procedure could not be found.)'
UserLibrary(ExternalLibrary)>>invalidCall
UserLibrary>>endPaint:lpPaint:
[] in TabViewXP(View)>>basicPaint:wParam:lParam:
[] in Win32Error(Exception)>>_evaluateHandler:in:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Win32Error(Exception)>>_evaluateHandler:in:
Win32Error(Exception)>>_propagateFrom:
Win32Error(Exception)>>_propagate
Win32Error(Exception)>>signal
Win32Error class(Exception class)>>signal
GDILibrary(ExternalLibrary)>>systemError
Canvas {16r0} >>textExtent:
TabViewXP>>paintVerticalLabel:on:in:
TabViewXP>>paintVerticalTabLabelsOn:
TabViewXP>>onPaintRequired:
[] in TabViewXP(View)>>basicPaint:wParam:lParam:
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
TabViewXP(View)>>basicPaint:wParam:lParam:
[] in TabViewXP>>wmPaint:wParam:lParam:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
TabViewXP(ControlView)>>withOldWndProc:
TabViewXP>>wmPaint:wParam:lParam:
TabViewXP(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
InputState>>wndProc:message:wParam:lParam:cookie:
InputState>>pumpMessage:
InputState>>loopWhile:
InputState>>mainLoop
[] in InputState>>forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in BlockClosure>>newProcess

**Comment by blairmcg** [comment]
This looks to me like it is probably an issue with the way the image save command line option has been added to the development session manager. It isn't safe to directly save the image during the startup processing (as this is doing) as at this point the startup process (which is the old main process) may be running alongside a new main UI process. When the saved image restarts you now have another UI process already running, since the startup interrupt is sent back to the process that was running when the image was saved.
The simplest fix is probably to defer the image save so that it gets processed by the new main UI process after the startup process (the old main process) has killed itself, e.g. with ``InputState>>queueDeferredAction:". The quit command would need to be deferred as well, as otherwise it will run before the image save has occurred.

**Comment by jgfoster** [comment]
Unfortunately, any save (-d or -i) with a pending quit (-x) will resulting on an immediate quit each time the saved image is launched (because the deferred actions are processed). Should an image save clear the entire deferredActions queue and restore it after the save? Are there deferredActions that should happen on image startup? If so, wouldn't it be more reliable to have them associated with a startup event?

Also, should the -d be deferred? Should it do an automatic save or should we have a new option to save? 

How about a file-in (-f)? Is it safe to do during a startup or should everything be deferred?

**Comment by blairmcg** [comment]
Hmm, yes, I can see that would be a problem. Clearing out the deferred actions doesn't seem like the right thing to do since it could be any arbitrary operation that somebody wanted to put there, and in general that will work fine over an image save. Perhaps the simplest thing to do is to make the save and exit a composite operation that can be deferred, either by always performing an exit after a save, or by assembling a composite operation in the command processing method, and then queuing that. It should be easy enough to do with blocks.
Another (perhaps easier) way would be to create a unique identifier for the session, stored in an instance variable of the SessionManager at some early stage of startup, e.g. from `Guid newUnique`. Then this can be "copied" into the exit block (i.e. assign it into a temp outside, and then reference that temp from the exit block, not the inst var). The exit block can then compare the current session guid against the one it has stored, and if they don't match, it can skip the exit.
