### ISSUE TITLE
Problem creating a ReferenceView

### ISSUE THREAD

**Issue by rejurime** [dolphinsmalltalk/Dolphin#452]
When I try to create a ReferenceView in the ViewComposer it gives me the following error:

![captura](https://user-images.githubusercontent.com/7131403/29221764-4c13b560-7e96-11e7-8e52-5e509c01aa1c.PNG)

**Comment by blairmcg** [comment]
@rejurime, what exactly are you trying to do? What are the repro steps?

ReferenceViews are only intended as a level of indirection to "link" another view definition for sharing purposes rather by taking a copy. One doesn't "create" a reference view directly, rather this is usually done by drag & drop from the view toolbox with the Alt key down so that the "link" drop-effect appears. This seems to work when I try it, but perhaps you are doing something different. Without the repro steps we are rather in the dark.

**Comment by rejurime** [comment]
Sorry my bad, if I try to create a ReferenceView of some "IDE Tools" (like Class Browser Shell or another shell) throws the error.

**Comment by blairmcg** [comment]
@rejurime, sorry for the delayed response. ReferenceViews are intended for sharing the definition of a composite view. It doesn't really make sense to use them to reference shell views, so this is not expected to work. Consequently this is "by design" (or at least as expected).
