### ISSUE TITLE
TreeView changed event happens too early

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#453]
Summary: If you make edits in a TextEdit, then click on a TreeView, the TreeView selectionChanged event happens before the TextEdit valueChanged event, allowing loss of the text change.

Detail: The attached TestShell.cls contains a TreeView, a ListBox, a TextEdit, and a PushButton. Each has a changed event that prints to the Transcript. 

The ListBox and the PushButton have correct behavior as follows: 
(1) Place focus in the TextEdit and make an edit
(2) Select an item in the ListBox or click the PushButton
The Transcript will show the TextEdit valueChanged event first (allowing the domain model to be updated), then show the ListBox or PushButton event (allowing a new model to be selected and placed in the TextEdit).

The TreeView has incorrect behavior as follows:
(1) Place focus in the TextEdit and make an edit
(2) Select an item in the TreeView
The Transcript will show the TreeView selectionChanged event first and the TextEdit valueChanged event second. If the TextEdit is displaying a selection from the TreeView, then the TreeView's selectionChanged event will update the TextEdit before the TextEdit's valueChanged event has an opportunity to update the previously-selected item.

[TestShell.cls.txt](https://github.com/dolphinsmalltalk/Dolphin/files/1219294/TestShell.cls.txt)

The problem may be how Microsoft Windows sequences the TVN_SELCHANGED and the EN_KILLFOCUS events. [This](http://www.virtualcmfc.info/CTreeCtrl_Focus_Problem_is_this_a_bug_.html) and [this](http://computer-programming-forum.com/82-mfc/b1eed804ca4aa522.htm) seems to describe a similar problem (as far back as 2003!).

**Comment by blairmcg** [comment]
Unfortunately I believe this is an issue with the TreeView control. Viewing the Windows event sequence with Spy++ confirms that the selection change notification is sent before the kill focus event. Frankly it is like swimming against the tide to try and correct these kind of issues in the framework. It is difficult to do correctly, requires extensive testing, and can be fragile, so we generally haven't done it. There is one exception where interceded in the mouse button processing for ListView in order to provide a suppressible `selectionChanging:` event, but even with the writing of extensive unit tests we still managed to mess up the multi-select case (recently fixed by a contributor).

I think your best bet in this case is to hook the `#selectionChanging:` event from the tree. When this is received the selection will not actually have changed (unlike #selectionChanged:). Then when you identify a forthcoming selection change in the tree when you have uncommitted edits you can either 

1. Refuse the selection change (by setting `SelectionChangingEvent>>value:` to false). This is what the class browsers do if you press "Yes" in response to the "There are unsaved source changes. Do you wish to retain them?" prompt.
1. Explicitly commit the pending changes in edit controls, etc, then allow the selection change to proceed. This can be done a variety of ways, e.g. send #apply to the TextEdit view, which can be done regardless of whether there are actually any pending changes, or send #updateModel when you know there are unsaved changes, or ask the presenter for its value (which will cause it to flush changes back to the model).

**Comment by jgfoster** [comment]
Thanks for the detailed response. I was investigating what it would take to have Dolphin work around the underlying OS problem but, based on your experience report and guidance, I'll abandon that effort.
