### ISSUE TITLE
UnicodeString is misnamed - it is a UTF16 encoded wide string

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#502]
`WideString` would be a better name, or `UTF16String` to be explicit.

**Comment by blairmcg** [comment]
Now renamed to Utf16String. The old UnicodeString name remains as an alias, but is deprecated.

**Comment by jgfoster** [comment]
Would there be any value in having a real UnicodeString (or CharacterCollection)? The comment for UtfEncodedString mentions "squaring the circle" in regards to having a collection that represents Character instances (where offset is meaningful) and a collection of bytes that is an encoded representation with variable length characters. 

Perhaps there should be a separation between Utf8EncodedString, Utf16EncodedString, and Utf32EncodedString (subclasses of ByteArray) and SingleByteString, DoubleByteString, and QuadByteString (subclasses of CharacterCollection). It seems that individual bytes in Utf* should not be represented as Character instances. In _most_ cases a TwoByteString would be equivalent to a Utf16EncodedString, but size would be off by a factor of 2 and indexing would produce the expected result in each case.

If you see value in this I'd be willing to try an implementation for your consideration. (Though I'm seeking your thoughts before starting since it would be a bit more than a trivial effort.)

**Comment by jgfoster** [comment]
Thanks very much for the thorough response. I particularly appreciated the UTF-8 manifesto and I've decided (for now) to see if I can live in the UTF-8 world.
