### ISSUE TITLE
New dependency on git-lfs

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#539]
Recent changes broke my checkout process and I've traced it down to what appears to be a new dependency on [git-lfs](https://git-lfs.github.com/). If this was intentional then this issue can be closed and at least we will have a record of the change.

**Comment by blairmcg** [comment]
Yes it was an intentional change for 7.1 to avoid adding to the bulk of the repository with the updates to the boot image that were required. The relevant commit is d05c0195fdb824a5b4cb174ec3bbdd66ca075108. The additional step was documented in the readme (5b21e05a9908ff14d33c3b76c61338c7f9b661ad).
The description of the AppVeyor build was moved into source with 0374cc41492d1195da1713d9d9601b7adfa30831, and updated for 7.1 in 23a969f2625536f3ee1e7eaf1dee493d2807380b, where a `git lfs pull` was added. The yaml file is a good reference source for the steps required in a build pipeline.
