### ISSUE TITLE
PositionableStream>>#basicUpTo: is being stripped

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#543]
It appears that this is because it sends #shouldNotImplement (see also SortedCollection>>#resize). This is under a comment of "development tools" and in 53f4727664807cda3f9b889f142932734e4df2a9 we removed some references to "non-distributable development tools." There is an option in the deployment tool to strip these senders and perhaps the correct thing is to rewrite a few methods that send this that shouldn't be stripped so that they call another method. I'm not sure why this recently broke.

**Comment by blairmcg** [comment]
It’s a new method related to the stream changes to allow streaming over UTF strings with variable length encodings. I think the issue here is that it shouldn’t be using shouldNotImplement, although the image stripper should also only remove methods that just send shoulNotImplement, not if there is a bunch of other code.
I don’t know if the SortedCollection method is similar, but will take a look.

**Comment by blairmcg** [comment]
I believe this is fixed, please reopen if not.
