### ISSUE TITLE
SessionManager>>quit: exit codes don't get back to the OS shell correctly.

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/Dolphin#57]
This seemed to surface with the VS2015 VM build but looks like it may have been a nascent issue all along. Initially the build and test scripts in AppVeyor were failing but these have now been changed to circumvent the issue (they can be revert when it is fixed).

**Comment by blairmcg** [comment]
There are actually two issues here. The most important problem (the CRT causing a failfast on shutdown due to a bug in the closing of the i/o descriptor/stream used to save the image) is fixed, and I've reverted the appveyor script change, and had green runs since. I'm going to close this one, and open another lower priority bug for the remaining problem (which is that if SessionManager>>quit is sent inside a callback, the exception the VM throws to initiate exit with an orderly shutdown is trapped at the user/kernel mode boundary and, depending on the host OS, either squashed or translated into a different exception).
