### ISSUE TITLE
Implement primitiveQuo in C++

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/Dolphin#573]
In the spirit of (64 bit) portability, and as an excercise, 
I chose a not-to-frequently-used primitve to convert to C++: "primitiveQuo". 
(Handy BTW, that the primitive table is now in C++. That saves handling of name mangling)
Below is the C++ source code with optimized (Release) assembly.
The x86 assembly looks OK to me, but I only have expericence in reading it, not writing it.
Are there any large optimizations missed?
Now that I'm writing this, I'll think I'll do a small performance test...

Comments welcome...

---

Oop* __fastcall Interpreter::primitiveQuo( Oop* const sp, unsigned argCount )
{
1000F3E1  push        ebx  
	Oop* arg = sp;

	ST::Integer* pDivider = reinterpret_cast< ST::Integer* >( *arg-- );
1000F3E2  mov         ebx,dword ptr [ecx]  
	if( ! ObjectMemoryIsIntegerObject( pDivider ) )
1000F3E4  test        bl,1  
1000F3E7  je          Interpreter::primitiveQuo+23h (1000F404h)  
		return NULL;
	int divider = ObjectMemoryIntegerValueOf( pDivider );

	ST::Integer* pReceiver = reinterpret_cast< ST::Integer* >( *arg );
1000F3E9  mov         eax,dword ptr [ecx-4]  
	if( ! ObjectMemoryIsIntegerObject( pReceiver ) )
1000F3EC  test        al,1  
1000F3EE  je          Interpreter::primitiveQuo+23h (1000F404h)  
	int receiver = ObjectMemoryIntegerValueOf( pReceiver );
1000F3F0  sar         eax,1  

	int quo = receiver / divider;
1000F3F2  cdq  
1000F3F3  sar         ebx,1  
1000F3F5  idiv        eax,ebx  
1000F3F7  pop         ebx  

	*arg = ObjectMemoryIntegerObjectOf( quo );
1000F3F8  add         eax,eax  
1000F3FA  or          eax,1  
1000F3FD  mov         dword ptr [ecx-4],eax  

	return arg;
1000F400  lea         eax,[ecx-4]  
}
1000F403  ret  
		return NULL;
1000F404  xor         eax,eax  
1000F406  pop         ebx  
}
1000F407  ret

**Comment by FunctionPoint** [comment]
Ha, that was interesting.
This code:
    Time millisecondsToRun: [ 1 to: 100000000 do: [ :i |  1234567 \\ i ]  ]
In the assembly version runs for 720 to 740 msec.
The C++ version runs in 700 msec, so actually a little quicker. 
Don't know which part of the execution time is the loop.
The difference seems negligable anyways.

**Comment by FunctionPoint** [comment]
PS In the current assembly, there is check of an overflow with max SmallInt quo -1, 
but I have not been able to reproduce this case.
0x3FFFFFFF quo -1 gives the correct output of 0.
0x3FFFFFFF + 1 becomes a LargeInteger, so will not overflow.

**Comment by blairmcg** [comment]
I'm a bit confused by your performance test since in the code you give you are measuring `\\` i.e. modulus (not the same as the C `%` operator either). If you are measuring and testing with `\\` you certainly won't be exercising primitiveQuo.  

The overflow case is `SmallInteger minimum quo: -1`. Its not so easy to detect that efficiently in C as it in assembler.

I don't think there is much to gain by reimplementing the SmallInteger arithmetic primiitives anyway. Most of them have bytecode instructions which shortcut the primitive (i.e. the primitive is hardly ever used, except for error cases or when perform'd). Since realistically those bytecodes have to remain in assembler in the current VM design, and the code is basically the same, reimplementing those in C++ would not contribute to a reduction in porting effort, probably the reverse. Although there is no bytecode for `SmallInteger>>quo:` (because, as you say, it isn't as commonly used as `SmallInteger>>//`), given that it is part of the same family of arithmetic primitives I think there would have to be a compelling reason not to leave it in the same form as the others.

There might be a minor perf win in switching the sign extend mov and shift pair to `cdq` in the assembler implementation now though. On the earlier Intel chips CDQ may have been slow, or I might have written in that way to open up an instruction pairing opportunity on the earlier Pentiums when that mattered. I don't recall, but the u and v pipeline comments in the code suggest probably the latter was the consideration. Either way it is probably not optimal on modern CPUs. It's quite difficult to measure the relative performance at that level in a repeatable and reliable way though.

**Comment by FunctionPoint** [comment]
Thanks as always for the thorough and informative answer.

Indeed, I confused quo and mod when quickly writing the performance test.
(The code for the primitive was written and tested a while back).

I also reproduced the overflow case (Smallinteger minimum quo: -1), 
and added a check for it, just to see how that would be done.

The C++ performance test code is now 10 - 15 percent slower than the asm code.
This is including the overhead of the loop. 
So the percentage difference for the quo function itself will be larger.

I concur that it's best to leave the asm code for the low-level arithmatic,
since there's an asm expert around... :)

As said in the start, this was more of an excercise for me. 
And I did indeed learn a few things. 
I'll close this now as an "issue" / feature request.

On to bigger things...
