### ISSUE TITLE
A better String>>unescapePercents

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#588]
I've been using `#unescapePercents` for url decoding before the changes introduced by the new wide string support. But for characters encoded using 2 hex digits the string returned by `#unescapePercents` is not the same as the original encoded string, for example the word "Cañón" urlEncoded produces "Ca%C3%B1%C3%B3n" and using `#unescapePercents` you get "CaÃ±Ã³n". I never paid attention before to this issue because from the internet browser side the unescaped characters were rendered ok, but not now.

I wrote a modified version that produces correct results for all the words I have tried. I named it `urlDecoded` as this is the same name that Pharo uses.

```
urlDecoded

	| bytes input pos oldPos |
	input := self asUtf8String.
	bytes := ByteArray writeStream: input size.
	oldPos := 1.
	
	[pos := input indexOfAnyOf: '+%' startingAt: oldPos.
	pos > 0] whileTrue: 
				[| char |
				bytes 
					next: pos - oldPos
					putAll: input
					startingAt: oldPos.
				char := input at: pos.
				char == $+ 
					ifTrue: [bytes nextPut: $\x20 codePoint]
					ifFalse: 
						[(char == $% and: [pos + 2 <= input size]) 
							ifTrue: 
								[| digit1 digit2 |
								digit1 := (input at: pos + 1) asUppercase.
								digit2 := (input at: pos + 2) asUppercase.
								(digit1 isHexDigit and: [digit2 isHexDigit]) ifFalse: [^input].	"not really an escaped string"
								bytes nextPut: digit1 digitValue * 16 + digit2 digitValue.
								pos := pos + 2]
							ifFalse: [bytes nextPut: char codePoint]].
				oldPos := pos + 1].
	bytes 
		next: input size - oldPos + 1
		putAll: input
		startingAt: oldPos.
	^Utf8String fromByteArray: bytes contents
```
I'm not sure if this implementation should replace `#unescapePercents`. The only one sender in the base image is processing an url. And I'm not sure about my implementation , specially about the first line converting the receiver to UTF8, that's because it's the only way it works for UTF16 strings.

**Comment by blairmcg** [comment]
Ironically String>>unescapePercents does have tests, but not covering any non-Ascii string cases (because that wouldn't have worked before), so I missed it becoming broken in 7.1, sorry. The reason it doesn't work for Utf16String input can be traced to the `#todo` comment in `String>>_indexOfAnyInString:startingAt:,`  (the double-dispatched implementation of `String>>indexOfAnyOf:startingAt:`), which explains that it only works for byte string instances. Converting to an AnsiString would be more correct, although it will make no difference.

Generally the best way to process strings now is to stream over the input string, and stream to an output string of the same species. The stream `next` family of methods over any type of `String` will always return a `Character` instance representing complete Unicode code point (which still isn't necessarily a "character" in the sense of a single recognisable visual unit on the page/screen, but the distinction is somewhat academic for most purposes), so it is usually the best way to process a string of any encoding on a character by character basis. However, in this case the URL encoded string you give as an example is actually representing the individual code units of the UTF-8, so processing it code-unit by code-unit is probably right. One needs to know that the underlying encoding of the escaped characters is always UTF-8 in order to decode it correctly without specifying the original encoding. I wasn't 100% sure that was the case, but this quote from RFC3986 suggest this can be relied on:

> When a new URI scheme defines a component that represents textual
>    data consisting of characters from the Universal Character Set [UCS],
>    the data should first be encoded as octets according to the UTF-8
>    character encoding [STD63]; then only those octets that do not
>    correspond to characters in the unreserved set should be percent-
>    encoded.  For example, the character A would be represented as "A",
>    the character LATIN CAPITAL LETTER A WITH GRAVE would be represented
>    as "%C3%80", and the character KATAKANA LETTER A would be represented
>    as "%E3%82%A2".

Ok, so we assume that the %-escaped values are UTF-8 code units. Given that, I think your modification will work. Strictly speakin you don't need to convert to a Utf8Sstring on input, rather a AnsiString, since a URI encoded string is guaranteed to be ASCII. However it won't make any practical difference, except where the input string is not actually a URL encoded string and contains non-ASCII characters. The intermediate ByteArray can be avoided by using #basicNextPut: into the output stream directly over a Utf8String.

I'd originally intended just to comment on this, but got rather drawn into it when I realised it wasn't broken in the way I'd assumed. So I ended up trying out some changes as outlined, and a few additions to the existing test, which I'll send as a PR.
