### ISSUE TITLE
New Method toolbar button missing?

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#607]
Just noticed the "New Method" button is missing from Toolbar.Class browser tools (it used to precede the "New Class" button).

It's still available from the menus but just wanted to check if the removal was intentional or a side-effect of the icon changes.

**Comment by blairmcg** [comment]
It was deliberate. I removed it because I didn’t think it very useful, mainly on the basis that all it does is clear the method selection and give one an empty source pane. That said I find myself missing it, and realise that subconsciously I must have pressed it quite a lot. 

If you are also missing it, I have no objection to restoring it.

**Comment by rko281** [comment]
Thanks Blair - mental note made.
