### ISSUE TITLE
Make Dolphin independent from Git tooling?

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/Dolphin#611]
When getting the Dolphin source through without Git tools (e.g. downloading the *.zip),
several files are now replaced with their Git LFS references, including DBOOT.*.
So it is not possible anymore to build a functioning Dolphin this way.
.
Also, building the VM depends on this Git command in Dolphin.targets to build a version header file:
"git describe --tag --always --long > "$(IntDir)version.txt"
Could the Dolphin version be stored in a *source* (text) file and let Git use that?
.
Besides Git independence, an additional advantage is that local playing-around copies of Dolphin to not have to drag around the sizable hidden, .git folder anymore.

**Comment by blairmcg** [comment]
I'm afraid I don't see why being independent of Git is net positive.

Git is designed for disconnected operation, and having done a clone, that's what you have subsequently. Why would you bother downloading a zip? It's not like Dolphin is a "library" you'd want to include in other builds, its an IDE.  Having an accurate git version in the build information is a benefit I wouldn't want to give up, and generating it on build is a superior solution to checking in a file with each change, or smudging one on checkout (which requires git anyway). If anything I'd like to see more git integration not less.
The Dolphin repo is not large, and the .git folder currently occupies ~120Mb on disk in a fresh clone.  The reason for adopting LFS was to stop that getting rapidly bigger due to large binary files that need to be updated fairly regularly. The Scintilla DLL is a case in point, being a 1Mb file. Earlier on this was downloaded at build time, but that causes a problem for people who want to build with no external dependencies except their git server.

**Comment by FunctionPoint** [comment]
Yes, for maintainers, the git integration is indeed handy. It's a choice.

It might be worth putting a note in the readme that the ZIP file does not contain buildable files,
and that Git tooling should be used to get the source.
This to guide casual visitors that are "browsing" Dolphin. 
I do that myself sometimes with other repo's...

**Comment by blairmcg** [comment]
Well the readme describes the steps required to build everything already in some detail, including the need to pull stuff from LFS (although a fresh clone with later git clients seems to do that anyway). The steps are relatively involved, and you can't just "build" and be done - not unusual for more complex repos. For casual examination, the pre-built installers are much the quickest and easiest way. 
If it were possible to avoid including those source archives in the releases I would, but GitHub insists on including them as far as I can tell.

**Comment by FunctionPoint** [comment]
It's a small thing, but something like the last line below in the first readme bullet:
(I'll shut up about it now :)
- First clone the Dolphin repo to a \Dolphin directory on your machine. It can actually be any location but for convenience we'll call it \Dolphin. Use a Git client tool to clone, downloading the ZIP file won't work due use of Git LFS.

**Comment by blairmcg** [comment]
Please feel free to submit a PR for the readme if you wish to change it.

**Comment by FunctionPoint** [comment]
Well, still good change, but a PR from a forked repo for one line of text seems a bit too much overhead.
Could you update it with your next code commit, in the wording of your choice?

**Comment by blairmcg** [comment]
There is no more overhead in submitting a PR from a forked repo than directly to the repo. In any case if it is something you care about (I'd assumed it was, since you raised the issue, and suggested the change), then you should make it. It is not something that I think important. If you don't care about it enough to make the change, then the issue may as well be closed as I won't be doing it.

**Comment by FunctionPoint** [comment]
All right then. I'll do a PR with with the wording suggested above.

**Comment by blairmcg** [comment]
Thank you, merged.
