### ISSUE TITLE
Fix RuntimeSessionManager>>deploy:

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/Dolphin#612]
Dolphin has a nice quick-deployment option of home made apps that does not require image stripping.

E.g.:  NotepadSessionManager deploy: 'MyNotepad.exe' 

But this command now fails just before closing the image because of a missing method "bootInfo".
To fix that, this methods can be added to SessionManager:

bootInfo
	^ nil.

MyNotePad.exe is generated, but when starting it Windows 10 gives the error message:
"This app cannot run on this PC". The usual option of "Run anyway" is not there.
Is some more version info needed in the *.exe? 
Maybe Windows thinks it's a 16-bit app?

**Comment by blairmcg** [comment]
The result is not an executable binary, its an image file, even though it is wrongly saved as a .exe. To quote from the comment: 

```
The image can be run by Dolphin.exe (e.g. by double-clicking the .img file).
Note that because the application is started by Dolphin.exe the first command
line argument will be the image path.
```

Judging from the fact that the examples refer to session manager classes that no longer exist, the image is saved with the wrong file extension, and the bootInfo problem (which can be safely ignored, since this occurs in the continuing session after the image ahs been saved to the file), I'd guess it hasn't been used/tested for a very long time. If one opens the resulting file with Dolphin.exe, it does appear to work though.

**Comment by FunctionPoint** [comment]
Ah yes, that was a bit of sloppy reading by me. :)
Indeed it works if it's saved as an image file.
I think the bootInfo method should still be added to SessionManager prevent the error message. 
I'll create a small PR.

On a side note:
The Notepad example chosen will try to open the first command line argument as a text file.
So it wil open the image name that must be the first argument, 
*if* the image is named anything else than then default "dpro.img7'.

I stumbled on the "deploy:" function while playing with SessionManager classes and an alternative startup method for them that does not require deployment. And indeed got the same behaviour. :)
More later.

**Comment by FunctionPoint** [comment]
That's fine with me too.
As said, I found this bug while experimenting with a *replacement* for this...

**Comment by blairmcg** [comment]
Closing this, since it is now obsolete as a bug. Any replacement can be a separate enhancement issue.

**Comment by FunctionPoint** [comment]
Thanks for the work-around suggestion.
Going to finish something similar first.
(But must admit coding time has been minimal, with long work hours and weekend festivities :)
