### ISSUE TITLE
Target Visual Studio 2019 and latest SDK

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/Dolphin#724]
Visual Studio 2019 is out, and it is good te have compatibility with it.
I've tested it by first deinstalling VS2017 and all SDKs.
Then installing VS2019 and targeting the latest SDK.
Only one line needed to be changed:
Str.h@57: Added cast to supported << overload.
	return stream << (char*) static_cast<LPCWSTR>(A2W(str.c_str()));
Added the (char*) to make it work, but am not sure about char* vs wchar_t*.
All regression tests ran fine after that.

**Comment by blairmcg** [comment]
This is blocked on AppVeyor making a VS2019 release build image available - at present only the preview builds are offered.

**Comment by FunctionPoint** [comment]
Ah well, that won't take too long, I guess...
Thanks for giving it a go.

**Comment by FunctionPoint** [comment]
An AppVeyor Visual Studio image is available:
https://github.com/appveyor/ci/issues/2907
It's still in a test phase though...

**Comment by blairmcg** [comment]
This still cannot be progressed because although a VS2019 images is available on appveyor, it doesn't work with vcxitems (shared library) projects. See https://help.appveyor.com/discussions/problems/24543-upgrading-to-visual-studio-2019-breaks-build, or https://ci.appveyor.com/project/dolphinsmalltalk/dolphin-db22v/builds/27347140
The manner in which appveyor is invoking msbuild must be incorrect. It should not be attempting to treat a vcxitems as a buildable project, it is more like a project include file.
