### ISSUE TITLE
Is it a good idea to have data associated to a process?

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#736]
I noted that Process has 2 reserved inst vars.
Is it a good idea to use it to put global data for that process only?
I there a better option?

Best use cases are mantaining db connections for process and currentUser or session while a http request is being executed.

**Comment by blairmcg** [comment]
Seems entirely reasonable to me. The simplest approach would be to put an IdentityDictionary in one of the unused slots. A better performance option would be to store an Array (like the ListView.moreParms variable) and have a mechanism to reserve slots by name so that it can be accessed more directly.

**Comment by fxgallego** [comment]
Thanks!
