### ISSUE TITLE
DBField converts to string using wrong encoding

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#740]
When you get data from a varchar database column and the data has some diacritics the resulting Dolphin String contains the diamond char instead of the diacritic one.

I've changed the DBField>>asString method this way and it worked OK. But I'm not sure if that's the best/right way.
```
asString
	"Private - Answer the receiver's buffer as a <String>."

	^buffer copy: AnsiString from: 1 to: self length
```
Also I've found the following article
https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-results/autotranslation-of-character-data?view=sql-server-2017
but seems that only applies to sql server.

and https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/programming-guidelines?view=sql-server-2017#character-set-support

Any thoughts?

**Comment by blairmcg** [comment]
I think that is the right fix for SQL_CHAR, SQL_VARCHAR, etc, columns. The #fromString: needs a fix for the reverse direction:.
```
fromString: aString
	"Private - Set the receiver's buffer from aString."

	(self shouldTranslate: aString class: String)
		ifTrue: 
			[| byteCount ansi |
			"This may be lossy; unrepresentable chars will be converted to the replacement char"
			ansi := aString asAnsiString. 
			byteCount := ansi size.
			byteCount > buffer size
				ifTrue: 
					[^self error: 'String too long. Max ' , buffer size displayString , ' got ' , byteCount displayString].
			buffer
				replaceFrom: 1
				to: byteCount
				with: ansi.
			self length: byteCount]
```

The SQL_WCHAR, SQL_WVARCHAR column types need #asUtf16String and #fromUtf16String: get/set methods added and then used appropriately in the initialization of the GetSelectors and SetSelectors maps in `DBField class>>initialize`.

There is a need for more work to convert the Database Connection packages to work with UTF-16 strings by default. At present it is still using the Ansi ODBC APIs.  I'm afraid I didn't give it much attention when I did the UTF work.

**Comment by fxgallego** [comment]
OK Thanks. I'll take a look at this, do some manual tests with my database and send a MR later.

[Here](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/unicode?view=sql-server-2017) is the documentation for unicode odbc.

**Comment by fxgallego** [comment]
I'm having trouble with `#fromUtf16String:`
I've implemented this way, note that I'm using `unicode size` instead of `unicode byteSize`. That's because using #byteSize results in a "size of replacement incorrect" error in the replaceFrom: .... method. I understand the problem but I didn't found how to solve it. Tried several things and I always end with incorrect results. I'm trying to insert into a nvarchar column using a DBParameterizedStatement.
This is my `#fromUtf16String:` version:
```
fromUtf16String: aString
	"Private - Set the receiver's buffer from aString. It could be an AnsiString or Utf8String too so we convert to Utf16."
	
	(self shouldTranslate: aString class: String)
		ifTrue: 
			[| byteCount unicode |
			"This may be lossy; unrepresentable chars will be converted to the replacement char"
			unicode := aString asUtf16String.
			byteCount := unicode size. "unicode byteSize ??"
			byteCount > buffer size
				ifTrue: 
					[^self error: 'String too long. Max ' , buffer size displayString , ' got ' , byteCount displayString].
			buffer
				replaceFrom: 1
				to: byteCount
				with: unicode.
			self length: byteCount]
```
I also had to change the SQL_C_WCHAR constant from -9 to -8 [See this](https://github.com/Microsoft/ODBC-Specification/blob/master/Windows/inc/sqlucode.h) because using the actual value results in a bind api call error. I'm currently reading OK Ansi and Unicode (with non latin chars) from the database. Only remains this problem with #fromUtf16String:

**Comment by blairmcg** [comment]
Ok, so the size reported by a `Utf16String` will be its size in code units, i.e. 16-bit words. In this case you should use the size in bytes (although not `#byteSize`, since this includes the null terminator which I think you probably don't want), although `#replaceFrom:to:with:` is confused by the mix of word and byte sized collections. I think the error check it contains is redundant since the method it calls will perform this check directly or indirectly anyway. I suggest:
```
fromUtf16String: aString
	"Private - Set the receiver's buffer from aString. It could be an AnsiString or Utf8String too so we convert to Utf16."
	
	(self shouldTranslate: aString class: String)
		ifTrue: 
			[| byteCount unicode |
			unicode := aString asUtf16String.
			byteCount := unicode size << 1.
			byteCount > buffer size
				ifTrue: 
					[^self error: 'String too long. Max ' , (buffer size >> 1) displayString , ' got ' , unicode size displayString].
			buffer
				replaceFrom: 1
				to: byteCount
				with: unicode 
				startingAt: 1.
			self length: byteCount]
```
I'm not surprised the constant definition is wrong. Originally these were defined by hand, and then they may not have been exercised so any error went unnoticed.

**Comment by blairmcg** [comment]
In case it isn't obvious, I suspect this won't work without migrating everything over onto the wide string APIs. I would assume that when using the ANSI APIs that the driver will be doing a WideCharToMultiByte on the contents of a WCHAR column on the assumption that the caller cannot handle UTF-16.
I would expect that to be quite a lot of work, and the nature of the API is such that it will be easy to crash Dolphin by unmodified parts of the old code passing in buffers that are sized for byte characters to an API expecting to write wide chars to that buffer.

**Comment by fxgallego** [comment]
Nope it didn't work :(
I'm using 'അ' as test string. The character has the code point 3333 and asByteArray #[5 13]. With the `fromUtf16String:` implementation provided by you the buffer is correctly written #[5 13] and the length set to 2. After insert, in the database side, the string isn't visible. When I query again that row I get in that column's buffer #[5 0 13 0] with length 4. Is that the problem you described before?

It's a pity because for reading nvarchar there isn't such a problem. Could you explain me why?
This is a picture with results from DB. The first 3 rows where inserted from sql management studio. The last one from Dolphin. The first column is always a varchar and the second nvarchar

![image](https://user-images.githubusercontent.com/2080171/56778764-605a1e80-67ae-11e9-9074-b7f9c6e0165b.png)

**Comment by blairmcg** [comment]
I'll take a look for you. #[5 13] is the correct encoded representation in UTF-16 as your test character requires only a single code point. However, it looks as if it is being interpreted by ODBC as if originating from a byte character buffer. In the original Dolphin implementation, which did not of course have any proper support for multi-byte strings, we just mapped the wide character column types to narrow character 'C' types, i.e. instructed ODBC to map SQL_WVARCHAR -> SQL_C_CHAR. You can see this in the map defined in `DBColAttr class>>initialize`. This is what defines what ODBC is expecting to find in the buffer, and has to match the conversions defined in `DBField class>>initialize`. There is a two stage conversion when sending data to SQL:
1. Dolphin converts from Object format to a byte buffer, e.g. a Utf16String to the byte encoding (a direct copy in this case)
1. The ODBC driver converts from the 'C' buffer to the representation required for the column. This would have performed a narrow to wide conversion in the original Database Connection configuration.
And on reading, there is similarly a conversion from the SQL data type to the specific SQL_C_xxx type that Dolphin has configured for the column, and then Dolphin constructs an object from the `C` bytes.
This will undoubtedly work when moving in a direction to/from an internal ANSI string on the same machine because the driver respects the current code page. It probably works even when the code page is different between the machine that wrote the data and the machine that reads it, because SQL probably stores sufficient information to be able to convert it to a different code page (e.g. it remembers the original code page, or it stores it in UTF-8 or UTF-16). Where this will break is if the character has no mapping in the code page of the machine on which it is being read. For example I'd be surprised if that Malayalam character would survive be stored to a SQL_WVARCHAR (nvarchar) column and retrieved as an ANSI string in most code pages.
Anyway, rather than talking about it in theory, I'd prefer to go and try it. I suspect there are going to be other issues than just matching up the DBField and DBColAttr mappings.

**Comment by fxgallego** [comment]
Thanks Blair, there's no hurry.
To be clear, I've changed the following methods:
`DBColAttr class>>initialize` (-8 is SQL_C_WCHAR, note that -9 is SQL_C_WVARCHAR but the bind fails with that value)
```smalltalk
initialize
	"Private - Initialize the receiver's class variables.
		self initialize
	"

	"The types to convert the result data to on loading into our buffers - normally these are the default conversions
	 because they are sensible for most things except GUIDs (where the default string conversion doesn't match 
	 the reported column length, which makes allocating an appropriately sized buffer tricky. We also let the ODBC 
	 driver(manager) convert wide character strings on our behalf"

	SQLToCTypes := (Array new: SQL_NUM_TYPES)
				at: SQL_GUID + TypeOffset put: SQL_C_GUID;
				at: SQL_WLONGVARCHAR + TypeOffset put: SQL_C_CHAR;
				at: SQL_WVARCHAR + TypeOffset put: -8;
				at: SQL_WCHAR + TypeOffset put: -8;
				at: SQL_BIT + TypeOffset put: SQL_C_BIT;
				at: SQL_TINYINT + TypeOffset put: SQL_C_TINYINT;
				at: SQL_BIGINT + TypeOffset put: SQL_C_SBIGINT;
				at: SQL_LONGVARBINARY + TypeOffset put: SQL_C_BINARY;
				at: SQL_VARBINARY + TypeOffset put: SQL_C_BINARY;
				at: SQL_BINARY + TypeOffset put: SQL_C_BINARY;
				at: SQL_LONGVARCHAR + TypeOffset put: SQL_C_CHAR;
				at: SQL_TYPE_NULL + TypeOffset put: SQL_C_DEFAULT;
				at: SQL_CHAR + TypeOffset put: SQL_C_CHAR;
				at: SQL_NUMERIC + TypeOffset put: SQL_C_CHAR;
				at: SQL_DECIMAL + TypeOffset put: SQL_C_CHAR;
				at: SQL_INTEGER + TypeOffset put: SQL_C_LONG;
				at: SQL_SMALLINT + TypeOffset put: SQL_C_SHORT;
				at: SQL_FLOAT + TypeOffset put: SQL_C_DOUBLE;
				at: SQL_REAL + TypeOffset put: SQL_C_FLOAT;
				at: SQL_DOUBLE + TypeOffset put: SQL_C_DOUBLE;
				at: SQL_DATE + TypeOffset put: SQL_C_DATE;
				at: SQL_TIME + TypeOffset put: SQL_C_TIME;
				at: SQL_TIMESTAMP + TypeOffset put: SQL_C_TIMESTAMP;
				at: SQL_VARCHAR + TypeOffset put: SQL_C_CHAR;
				yourself
```
`DBField class>>initialize`
```smalltalk
initialize
	"Initialize the dictionaries of to/from
	C Type/Smalltalk object converters.
		DBField initialize
	Note that the maps rely on the sequential numbering of the type enumerations.
	"

	self assert: [TypeOffset = (SQL_GUID abs + 1)].
	self assert: [SQL_NUM_TYPES = (TypeOffset + SQL_VARCHAR)].
	GetSelectors := (Array new: SQL_NUM_TYPES)
				at: SQL_GUID + TypeOffset put: #asGUID;
				at: SQL_WLONGVARCHAR + TypeOffset put: #asString;
				at: SQL_WVARCHAR + TypeOffset put: #asUtf16String;
				at: SQL_WCHAR + TypeOffset put: #asUtf16String;
				at: SQL_BIT + TypeOffset put: #asBoolean;
				at: SQL_TINYINT + TypeOffset put: #asByte;
				at: SQL_BIGINT + TypeOffset put: #asInt64;
				at: SQL_LONGVARBINARY + TypeOffset put: #asByteArray;
				at: SQL_VARBINARY + TypeOffset put: #asByteArray;
				at: SQL_BINARY + TypeOffset put: #asByteArray;
				at: SQL_LONGVARCHAR + TypeOffset put: #asString;
				at: SQL_CHAR + TypeOffset put: #asString;
				at: SQL_NUMERIC + TypeOffset put: #numberFromNumeric;
				at: SQL_DECIMAL + TypeOffset put: #numberFromNumeric;
				at: SQL_INTEGER + TypeOffset put: #asLong;
				at: SQL_SMALLINT + TypeOffset put: #asShort;
				at: SQL_FLOAT + TypeOffset put: #asDouble;
				at: SQL_REAL + TypeOffset put: #asFloat;
				at: SQL_DOUBLE + TypeOffset put: #asDouble;
				at: SQL_DATE + TypeOffset put: #asDate;
				at: SQL_TIME + TypeOffset put: #asTime;
				at: SQL_TIMESTAMP + TypeOffset put: #asTimeStamp;
				at: SQL_VARCHAR + TypeOffset put: #asString;
				yourself.
	SetSelectors := (Array new: SQL_NUM_TYPES)
				at: SQL_CHAR + TypeOffset put: #fromString:;
				at: SQL_NUMERIC + TypeOffset put: #numberToNumeric:;
				at: SQL_DECIMAL + TypeOffset put: #numberToNumeric:;
				at: SQL_INTEGER + TypeOffset put: #fromLong:;
				at: SQL_SMALLINT + TypeOffset put: #fromShort:;
				at: SQL_FLOAT + TypeOffset put: #fromDouble:;
				at: SQL_REAL + TypeOffset put: #fromFloat:;
				at: SQL_DOUBLE + TypeOffset put: #fromDouble:;
				at: SQL_DATE + TypeOffset put: #fromDate:;
				at: SQL_TIME + TypeOffset put: #fromTime:;
				at: SQL_TIMESTAMP + TypeOffset put: #fromTimeStamp:;
				at: SQL_VARCHAR + TypeOffset put: #fromString:;
				at: SQL_LONGVARCHAR + TypeOffset put: #fromString:;
				at: SQL_BINARY + TypeOffset put: #fromByteArray:;
				at: SQL_VARBINARY + TypeOffset put: #fromByteArray:;
				at: SQL_LONGVARBINARY + TypeOffset put: #fromByteArray:;
				at: SQL_BIGINT + TypeOffset put: #fromInt64:;
				at: SQL_TINYINT + TypeOffset put: #fromByte:;
				at: SQL_BIT + TypeOffset put: #fromBoolean:;
				at: SQL_WCHAR + TypeOffset put: #fromString:;
				at: SQL_WVARCHAR + TypeOffset put: #fromUtf16String:;
				at: SQL_WLONGVARCHAR + TypeOffset put: #fromUtf16String:;
				at: SQL_GUID + TypeOffset put: #fromGUID;
				yourself
```
`DBField>>asString` and `#fromString:`
```smalltalk
asString
	"Private - Answer the receiver's buffer as a <String>."

	^buffer copy: AnsiString from: 1 to: self length
```
```smalltalk
fromString: aString
	"Private - Set the receiver's buffer from aString."

	(self shouldTranslate: aString class: String)
		ifTrue: 
			[| byteCount ansi |
			"This may be lossy; unrepresentable chars will be converted to the replacement char"
			ansi := aString asAnsiString.
			byteCount := ansi size.
			byteCount > buffer size
				ifTrue: 
					[^self error: 'String too long. Max ' , buffer size displayString , ' got ' , byteCount displayString].
			buffer
				replaceFrom: 1
				to: byteCount
				with: ansi.
			self length: byteCount]
```
`DBField>>asUtf16String` and `fromUtf16String:` using your implementation.
```smalltalk
asUtf16String
	"Private - Answer the receiver's buffer as a <Utf16String>."

	^Utf16String fromByteArray: buffer length: self length // Utf16String elementSize
```

I ran the tests using MSSQLServer 2017 with the `SQL Server Native Client 11.0` driver.
I used the following tables and test data:
```sql
create table unicode_test
(
    string varchar(100),
    unicode_string nvarchar(100)
)
go

insert into unicode_test (string, unicode_string) values ('Camión', 'Camión');
insert into unicode_test (string, unicode_string) values ('Unicode', N'ღმერთსი შემვედრე, ნუთუ კვლა დამხსნას სოფლისა შრომასა');
insert into unicode_test (string, unicode_string) values ('Unicode', N'അ');
```

**Comment by blairmcg** [comment]
I eventually discovered the reason for the data being inserted with null bytes in your experiments, and it was because of specifying SQL_C_DEFAULT in the `DBParameterizedStatement>>setParams` method. Rather than specifying the actual buffer being passed, this was saying "assume it is the default for this column type". One would have thought that the default assumption for nvarchar would be SQL_C_WCHAR, but in fact it is SQL_C_CHAR. This is probably for backwards compatibility with old clients that are not Unicode aware.
Anyway, I worked through the whole thing doing a transformation on it to support UTF encoded strings (something I overlooked when I did that work last year). The issue with SQL_C_DEFAULT was one of the last things I discovered. I think I have it all covered in my new PR, however, if you'd like to try it out.

**Comment by fxgallego** [comment]
Thanks, I'm testing a bit now

**Comment by fxgallego** [comment]
Awesome! works perfect with my tiny tests. Maybe in some time we start to use master and do more serious tests because our app does a very intensive use of odbc.
If you have the snippet in #752 as a test I'd add this 2 lines

```smalltalk
c query: 'insert into 海豚 (Ansi, 編碼) values (''Inserted by sql 1'', N''അ'')'.
c query: 'insert into 海豚 (Ansi, 編碼) values (''Inserted by sql 2'', N''Camión'')'.
```

I have no more ways to say thank you, sorry, due to my limited english sometimes is difficult to express my gratitude.

**Comment by blairmcg** [comment]
No problem. I'll merge it.
