### ISSUE TITLE
Compiler produces AnsiString for method literals

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#761]
This is more like a doubt than a bug report but I think it has impact on how we write code.
Actually Utf8String doc says:

>`Utf8String` is the class of `Strings`s that use a the multi-byte UTF-8 encoding. UTF-8 is the defacto standard for text interchange, and is now the default representation in Dolphin.

But it appears that the compiler produces AnsiString and Utf8String when needed. I didn't pay attention to the compiler code but maybe it is better to clarify this in the doc.

**Comment by blairmcg** [comment]
This is a deliberate "internal" choice, but only because there is a marginal efficiency benefit in some circumstances, for example when calling an API that takes `lpstr` arguments, the VM will not need to perform a conversion via UTF-16 to get to ANSI, which is what it has to do with Utf8Strings. However the exact representation of the string literals should be transparent for most purposes. It's best to avoid blind conversions to bytes (e.g. `#asByteArray`) unless you are sure you have a string with the right encoding. Also streams should now always be used when enumerating over strings if it is necessary to access the individual characters. The class comment of `UtfEncodedString` discusses this in more detail. #502 also has some relevant discussion.

This isn't really contradictory to the Utf8String comment though - the default if one writes things like `String new` is indeed that one will get UTF-8 strings. The compiler is choosing not to follow the default as an internal implementation choice, but it is a choice that could be changed in the future. It would be better not to assume that String literals are any particular type of String, and in general to code without a dependency on particular encodings except at system boundaries like I/O to files. With that in mind the precise type of the compile strings should be not be important. If there are some scenarios you have where this is problematic, i.e. it is important, then it would help to know about them so we can consider if there are gaps that we can do something about, or whether the Compiler implementation choice is the right one.

**Comment by fxgallego** [comment]
Thanks for the explanation. Yes, my doubt is about working with windows APIs like the Http Server but I think now that's is better to relax about it and code without paying attention to this until a problem arises.
My worries were about if I would need to send `asUtf8String` message to each literal passed to the api, when it's needed or when it isn't.
Reading the UTF8 Manifesto would be a good idea thought.

**Comment by blairmcg** [comment]
> Thanks for the explanation. Yes, my doubt is about working with windows APIs like the Http Server but I think now that's is better to relax about it and code without paying attention to this until a problem arises.
> My worries were about if I would need to send asUtf8String message to each literal passed to the api, when it's needed or when it isn't.
> Reading the UTF8 Manifesto would be a good idea thought.

One thing to remember is that the Compiler will only generate ANSI strings for a subset of strings that could theoretically be represented as ANSI strings for a particular code page. It will only use ANSI strings when the characters are all ASCII (i.e. code units between 0 and 127). It wouldn't be safe for the compiler to use ANSI strings for characters that might have different code points on different code pages, because then the literal string could mean something different when used on a machine with a different default code page to that of the machine where the code was written, so it will always use UTF-8 for characters with code values > 127. e.g.
`
'abc' class. "AnsiString"
'abc' asUtf8String = 'abc'. "true"
'abc' asUtf8String asByteArray = 'abc' asByteArray. "true"
"But"
'€' class.	"Utf8String"
'€' asAnsiString = '€' "true"
'€' asAnsiString asByteArray = '€' asByteArray "false"
```
Because the Compiler will not create potentially ambiguous AnsiString instances they will always have the exact same binary representation as the UTF-8 equivalent, so even if you were to treat the contents as bytes, they would look the same. 

If you are serving up UTF-8 from Http Server, as long as you build it by writing to a stream over a Utf8String, then the stream will take care of any conversion for you. If you are building into a byte array buffer, you'll need to be a little more careful, but the literal strings direct from the compiler should still not be a problem.
