### ISSUE TITLE
Utf8String incorrectly reports its size

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#763]
**Describe the bug**
Utf8String is reporting its size in bytes (without null terminator) instead of visible characters.
Examples:
```smalltalk
'Camión' byteSize -> 8
'Camión' size -> 7
'Camión' asUtf8String size -> 7
'Camión' asAnsiString size -> 6
'Camión' asUtf16String size -> 6

'ᚠ' byteSize -> 4
'ᚠ' size -> 3
'ᚠ' asUtf16String size -> 1
```

**Expected behavior**
`#size` should report the number of visible or user-perceived characters or at least return the same as Utf16String does.
Also the same incorrect results are being returned using `countElements` and `strlen`

**Additional context**
Found this problem while reading the UTF8 Manifesto and trying to understand how Dolphin counts characters. Sorry if this is currently known or by design.

**Comment by blairmcg** [comment]
It is, in fact, by design. I'll give a detailed explanation of why as a record for the future.

Quoting from the comment of `UtfEncodedString`:

> Like AnsiString and (as yet hypothetical) Utf32String, the elements of a UtfEncodedString are represented by Character instances when enumerating or accessing by index, but unlike those fixed-width encodings the values of the elements are really code units rather than whole code points. Consequently the Character instances may represent surrogate (partial) characters from the encoding. This is a compromise required to represent the variable-width UTF encodings within the Smalltalk SequenceableCollection hierarchy, which was designed  for fixed-width elements long before UTF-8 and UTF-16 were imagined, yet which also requires that the elements of Strings be Characters.

So sending `size` to a `Utf8String` is correctly reporting the number of code units, not the number of "whole characters" (code points). The same is actually true for `Utf16String`, it is just that the majority of code points require only a single code unit. But try:
```
Character dolphin asUtf16String size "=> 2"
```
The Utf8 Manifesto talks a lot about the issues arising from treating a string as if it is an array of characters and why this is a bad idea. Relating that to Smalltalk context:

- We could implement `size` by counting the characters. Maybe counting them once isn't too bad, although we'd need to count them again if the string were mutated (since unfortunately Smalltalk's strings are not immutable in general).
- And to be consistent with that, we need to be sure that `do:`, `collect:`, `select:` etc all behave consistently with this "array of characters" model. That's probably not too bad, since these are effectively streaming operations anyway, and we could just implement #do: as a loop over a read stream.
- But then we come to `at:`. This is a bit trickier, since now we have indexed random access into a collection of variable length elements. We can either count from the beginning each time and pay the cost, or perhaps calculate and cache an index, or use an alternate data structure instead of storing an array of code units. If we do the latter, then suddenly our representation is a lot larger, and maybe not worth it - perhaps there wouldn't be much gain over the very wasteful UTF-32 representation. If we use an alternate data structure, then we have to perform a translation every time we want to call an API (which Dolphin, as part of its raison d'être, does rather a lot and we wouldn't want to slow that down too much)
- There are various other collection protocols that require indexed access (e.g. `indexOf:`), but we've either decided to count, or built some clever index or data structure for `at:`, so it's not getting any worse yet.
- But then we have to consider indexed mutation, starting with `at:put:`. Now we are potentially inserting a different length character into the middle of a string, so we might need to shrink it or expand it, and shuffle the elements after it. Hmmm....
- And then there are various other indexed mutators; `replaceFrom:to:with:startingAt:`, etc.

My (rather belaboured) point is that it quickly gets out of hand. There has to be a complete and consistent abstraction that the UTF encoded strings are fixed length arrays of elements. As we've seen, going down the route of providing an illusion that those elements are whole characters is expensive to implement, and likely comes with significant runtime cost. Alternatively, we can maintain the abstraction of fixed length elements by deciding that the elements should be code units. This is what the UTF8 Manifesto argues for. We now have a complete and consistent abstraction, that has low implementation cost, and no runtime overhead in most scenarios. Much of the time it doesn't even impinge on the coding experience, because for things like slicing up strings by searching for start and end characters, everything will work fine - if it isn't clear what I mean, try debugging through the following expression into the `Character` method that does the actual slicing up of a string by finding instances of itself:
```
'Ḽơᶉëᶆ ȋṕšᶙṁ ḍỡḽǭᵳ ʂǐť ӓṁệẗ, ĉṓɲṩḙċťᶒțûɾ ấɖḯƥĭṩčįɳġ ḝłįʈ, șếᶑ ᶁⱺ ẽḭŭŝḿꝋď ṫĕᶆᶈṓɍ ỉñḉīḑȋᵭṵńť ṷŧ ḹẩḇőꝛế éȶ đꝍꞎôꝛȇ ᵯáꞡᶇā ąⱡîɋṹẵ' subStrings: $\x20
```

This demonstrates that using indexed access to copy out chunks of a string can still work well and doesn't require code any different from that you might write to copy out sub-sequences of other collections. It works because the actual positions don't really matter - they are opaque to the algorithm. It wouldn't work where this is not the case, for example indexing over a string by index and then treating what you get back as characters that can be inserted into a string with a different encoding.

Another (useless) example: 
```
 ('Ḽơᶉëᶆ' collect: [:each | each ])
```
That works even using the `collect:` implementation inherited from `SequenceableCollection` because it pushes the code units back into another instance of the same type of string.

However, if you try to evaluate the following expression you will get an error:
```
 ('Ḽơᶉëᶆ' collect: [:each | each asUppercase ])
```

It is BTW possible to tell when a Character is representing a UTF-8 lead or trail byte, or a UTF-16 surrogate, as there are testing methods on Character for this purpose. Also:

```
a := ('Ḽơᶉëᶆ' at: 1).
b := (Character codePoint: 225).
a codeUnit = b codeUnit. "both are 225"
"...but..."
a = b. "=>false"
"...because..."
a isUtf8Surrogate. "=> true"
b isUtf8Surrogate. "=> false"
```

This is why in almost all circumstances where enumeration over individual characters is required, a stream should be used. Using streams it is also safe to mix strings of different encodings, as the streams will automatically convert to the target encoding. As an aside it would be useful if `ReadStream`'s understood collection messages like `collect:`, `select:`, etc.

So yes, it is a compromise, but I think it is the right one. What is missing, however, is the `Utf32String` that I'd always intended to add to support situations where there is a need to index over fixed length characters. There is provision for this in the design, and I added support in some of the primitives, and had a `Utf32String` class for a while, but I cut it to get the Unicode string work finished. I just added #764 to go back and finish it off.

**Comment by fxgallego** [comment]
I completely agree with you and the manifesto is pretty clear about the issue of counting characters and all of its implications with the different ways we can "see" a character. Maybe my "Expected Behavior" paragraph in the bug report isn't accurate with the manifesto.

I more interested in a practical and pragmatic solution like counting, providing a message with an intention revealing name, for example, `#countCharacters`, `#codePointSize`, `#length`, others....

Currently sending `asArray size` works like a charm (or at least seems to work well) so having a new message that counts using a stream should be enough. Maybe you can decide after if it's better to cache the result somewhere or not. But having this decided for us in the base Dolphin will be better for us, also documenting or pointing to this in the `#size` method comment.

**Comment by blairmcg** [comment]
I'm curious to know the scenarios in which you need the character count, e.g. to understand how efficient it would need to be.

**Comment by fxgallego** [comment]
>I'm curious to know the scenarios in which you need the character count, e.g. to understand how efficient >it would need to be.

Sincerely I don't know right now. That's why I don't care how efficient it would be :)
But maybe calculations related to presentation things, centering strings, aligning, but really doesn't come to my mind something specific. The manifesto mentions some things related to cursor movement and selections. BTW ('🐬' halt asArray size) shows the debugger with the right selection. The case of counting characters to inform the user like the twitter example.

Another thing that comes to my mind is compatibility between Smalltalks.
Pharo 6.1 seems to be consistent with `size` returning the number of characters but I didn't test extensively.
The 8.3 section in the manifesto shows the following example:
Приве́т नमस्ते שָׁלוֹם  it consists of 22 code points. Pharo returns 22 as its size. I don't have other smalltalks to check at hand. But I do have Ruby and it also reports 22. In dolphin, converting to Array first also returns 22. JavaScript in the browser also reports 22 and it has some problems in the chrome console when you try to delete it with backspace 😄 

I don't know if this difference could be a source of problems porting code. Probably not. But it would be strange to behave different to others. Not something that worries me but worth to mention here.

**Comment by blairmcg** [comment]
> Sincerely I don't know right now. That's why I don't care how efficient it would be :)

😊. As I'm sure you guessed, the main reason I asked the question was that I couldn't really think of any scenarios where a count of the code points is really needed or useful, and so I strongly suspect that You Ain't Gonna Need It applies here.

> But maybe calculations related to presentation things, centering strings, aligning, but really doesn't come to my mind something specific. The manifesto mentions some things related to cursor movement and selections. BTW ('🐬' halt asArray size) shows the debugger with the right selection.

Both the UTF-8 Manifesto and the various Wikipedia pages for Unicode and UTF encodings do caution on considering code points to equate to characters, because it is not the case that one Unicode code point necessarily maps to one distinct character displayed on screen. Editors and other text renderers cannot rely on mapping Unicode code points 1:1 to user-perceived characters, because some such user-perceived characters (aka grapheme cluster) are actually composites. For example although there are specific accented characters for European languages in Unicode, there are also general purpose overlay characters (diacritics) that can be combined with others to add umlauts, accents, etc, and this is a perfectly valid form for a Unicode representation of some particular user-perceived character even when there is a shorter form. Here is an example:
```
(String with: $o with: $\x308)	"=>'ö'"
```
And another example from Thai that is supposed to be a single grapheme cluster composed of two Unicode character code points:

	'กำ'

Try pasting this into a Dolphin workspace and then seeing how Scintilla treats it. Note that although this is visually one character, each of the components can be selected and deleted individually (which makes sense, as it is an editor and should allow the editing of composite characters). If the first "character" is deleted, however, there is no actual reduction in space occuppied, so if the code point count were used to calculate geometry for strings containing these code points, the results would be wrong.

> The case of counting characters to inform the user like the twitter example.

Maybe, but I wonder what they really count? It wouldn't particularly make any more sense to count code points over (say) UTF-16 code units, as the discussion above applies here too - code points are still a technical concept and don't necessarily map 1:1 to user-perceived characters. Where this is a concern, it doesn't seem like it would matter to convert to an array of characters to get that count.

>Another thing that comes to my mind is compatibility between Smalltalks.
Pharo 6.1 seems to be consistent with size returning the number of characters but I didn't test extensively.
The 8.3 section in the manifesto shows the following example:
Приве́т नमस्ते שָׁלוֹם it consists of 22 code points. Pharo returns 22 as its size. I don't have other smalltalks to check at hand. But I do have Ruby and it also reports 22. In dolphin, converting to Array first also returns 22. JavaScript in the browser also reports 22 and it has some problems in the chrome console when you try to delete it with backspace 😄

The example you give will report 22 code units in any implementation that is using UTF-16 as the underlying representation (I think BTW they chose that example precisely because it does not contain 22 user-perceivable characters, so 22 isn't really the "character" length):
```
	'Приве́т नमस्ते שָׁלוֹם' asUtf16String size "=> 22"
```
Another test would be to use a string that contains a mix of code points including some that require two UTF-16 code units, e.g. with any emoji such as U+1F37A or the Dolphin character I like to use for testing, and throw in some of the composite characters too for good measure:

```
doubles := Utf16String with: Character dolphin with: $\x1F37A with: $o with: $\x308.  "=>'🐬🍺ö'"
doubles size "=> 6"
```
I'd be interested to know what JavaScript and Ruby report for those, although it is only an academic interest. I'm not really sure why it would matter.

Pharo uses either ByteStrings when all the characters are in the Latin-1 character set, or 32-bit characters for strings containing even a single character outside Latin-1. I don't know if Pharo's wide strings are completely UTF-32 compliant or not, but probably the stored code is just the Unicode code point and UTF-32 is basically that with some restrictions as to the allowable code points. I can see the attractions of this approach, as its simple and continues to work reasonably well with what I consider to be a historic mistake in the design of the Smalltalk class library in putting String into the Collection hierarchy. However, it's very very wasteful of space. If you put one emoji in an string which would otherwise be Latin-1, you've suddenly made it 4 times as large, and anybody using Eastern languages is going to be using about twice as much memory for strings as is necessary. It is also a pretty poor choice for efficiently interfacing with external APIs, especially on Windows which simply doesn't use UTF-32 at all. That doesn't matter terribly much for Pharo/Squeak, because its design philosophy has historically emphasised doing everything in Smalltalk, but Dolphin is based on completely the opposite philosophy. For Dolphin the "compatibility" that matters much more is interfacing to the largely C-family APIs of Windows and libraries that Microsoft and others write for Windows, and of all the examples I've seen of these they are always working in code units. If you need to a counted UTF-16 string to an external API you can almost guarantee that it will be expecting to be told the size in code units, not code points.

I did wonder whether it might be relevant to the length of columns in a SQL database, but that is also a count of code units for nvarchar columns, and not code points. 

My overall conclusion is that for technical use, the number of code units is more relevant as this is the size needed for buffers, database columns, etc. For interchange with a user, the number of grapheme clusters may be important, but in general this is not the same as the number of code points anyway, so when would one ever need the number of code points? I did think of one case, which was that it would be useful for sizing a buffer for conversion to UTF-32, but other than that I can't think of anything.

> I don't know if this difference could be a source of problems porting code. Probably not. But it would be strange to behave different to others. Not something that worries me but worth to mention here.

Well is a choice to make as there is really no standard behaviour to be compatible with, so I opted for "elements = code units" because it allows for a consistent model of Strings as sequenceable collections at reasonable implementation cost and efficiency, and it works well with external APIs. I'd care more about compatibility with Pharo if I thought compatibility with other Smalltalk systems was a priority for Pharo, but it simply isn't, and that is their choice to make. In this case my experience is that some code one might import that treats Strings as collections will not work, but it is easy to fix in a way that would work in either and which is probably a neater solution anyway. I found one case of this in importing the STON code recently, but it was in the tests, not in STON itself, and it was not an especially elegant piece of code so I was happy to "adjust" it anyway.

We could still decide to use UTF-16 as the default string representation in Dolphin. The swap could be made with very little impact. This would have some advantages in reducing the need for conversion on calling typical wide string APIs, and also make it much rarer to encounter strings where one code unit would not be equal to one character. I'm not so sure tha last quality is a good thing though, as it just hides the problem away and my general experience is that rarely occurring problems are the worst ones to have.

**Comment by fxgallego** [comment]
Thanks for your elaborated comments. They're really educational!

As you were curious about '🐬🍺ö' size in Ruby and JavaScript I made some tests and found:
JavasScript returns 6, I'm sure that is because [JavasCript uses internally UTF-16 ](https://stackoverflow.com/questions/11141136/default-javascript-character-encoding)
Ruby returns 4 and its default encoding is UTF-8
Ruby recently added a String method: `grapheme_clusters` which is a shortcut for [`each_grapheme_cluster`](https://ruby-doc.org/core-2.6.3/String.html#method-i-each_grapheme_cluster) Also see this http://unicode.org/reports/tr29
`grapheme_clusters` returns 3 for the test 😄 
I didn't know about that method before and I found it in this [interesting page](https://idiosyncratic-ruby.com/66-ruby-has-character.html)

**Comment by fxgallego** [comment]
BTW here is an implementation of a [grapheme_splitter in JavaScript](https://github.com/orling/grapheme-splitter/blob/master/index.js)

I think that this issue can be closed, did you?

**Comment by blairmcg** [comment]
That is interesting - so Ruby is the only one that is counting the actual code points (and Pharo/Squeak,  implicitly because the wide strings are 32-bit so code-unit = code-point). If you wanted to write an editor (and in Javascript, why not) then you'd need something to work with grapheme clusters. If someone had a need for it in Dolphin,  I think it would be better to bind to an external C library to do something as complex and low-level as that.
I have thought of one reason it might be useful to have a count of code points, which is for diagnostic purposes. It would be useful occasionally when inspecting a string to know the number of code points, particularly where the string contains more code points than grapheme clusters (such as where there are diacritic overlays). Having such methods also reveals information about the Dolphin string implementation and so helps with understanding. Let's leave the issue open and I'll code something up. I'll also add to the class comments a bit to try and make it clearer how strings in Dolphin behave.

**Comment by blairmcg** [comment]
BTW: I love the example of the 4 code point grapheme cluster for '👨🏻‍🍳' on your interesting page. That rather brings home that some methods, such as `String>>reverse` don't currently work correctly (although that is also true for the simpler examples above). I guess the grapheme cluster enumeration is really needed.
```
'a 👨🏻‍🍳' reverse "=> '🍳‍🏻👨 a' Wrong!"
```
