### ISSUE TITLE
RichText with Utf8 make Dolphin crash

### ISSUE THREAD

**Issue by brunobuzzi** [dolphinsmalltalk/Dolphin#769]
**Describe the bug**
Open some RichTextPresenter with Utf8 string make Dolphin crash (see attached workspace). But it do not crash with every string. In the attached workspace there is a Spanish string that make Dolphin crash (tested in 3 differente images).

**To Reproduce**
Open attached workspace select all Text and press evaluate.
[dolphin-crash-rtf-utf8.txt](https://github.com/dolphinsmalltalk/Dolphin/files/3167398/dolphin-crash-rtf-utf8.txt)

**Expected behavior**
It should not crash and show changes in the Presenter

**Please complete the following information):**
 - OS: Windows 8
 - Dolphin 7.1.2

**Additional context**

**Comment by brunobuzzi** [comment]
I forgot to mention i tracked to problem upto:
`RichTextEdit>>displayValue:`
Dolphin crash after: `newValue := aRichString ?? ''.`

**Comment by blairmcg** [comment]
I can see the issue. The text streaming is overwriting the end of the buffer because it reads a number of characters from the stream based on the supplied buffer byte size. This will only work correctly for ANSI strings. A workaround, in this particular case (since your RTF is not actually Unicode - you can see from the header that it is ANSI code page 1252), would be to ensure you pass it over as an AnsiString. You're getting a Utf8String because you are passing it through the compiler, which will automatically create a Utf8String if it sees any characters in the compiled input with code units > 127 - i.e. it assumes that the text it is being asked to compile is UTF-8. Depending on the source of the data, you might need to convert it or ensure it is read into an AnsiString in the first case (if reading from a file, for example). In this case if you add a `asAnsiString` to convert the literal string, it will work.
