### ISSUE TITLE
[Wine] bug displaying Workspace right hand toolbars after Dolphin 7.1.1

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#799]
**Le Bug, c'est mal**
Vertical toolbars on the east side of a Workspace window fail to render properly after Dolphin-7.1.1 under Wine.

**Do that to me one more time**
Steps to reproduce the behaviour:
1. Start Dolphin-7.1.2 or later
2. Click on 'Workspace' in the System Folder (first blue window to show)
3. Toolbar off to the right hand side will have icons that overlap each other, or don't show. Layout may or may not be vertical. Text area won't show until window is moved off to the right hand side until the text area reappears (usually the toolbar will have been moved offscreen).  All other Dolphin windows will appear to freeze until this is done.

**Dolphin Done Right**
Workspace window should look like it does under Windows or like 7.1.1 but without the gradients.

**A clear shot of the valley**
_Image of 7.1.1 Workspace with comctl32.dll (6.0.6000-16383) from dotnet35_
![Image of 7.1.1 Workspace](https://user-images.githubusercontent.com/62885/62286693-5716d700-b4ac-11e9-9797-fc8fb96c16c1.png)

_An overlay of Vista and Fedora 27 workspaces showing affected toolbars. comctl32 (5.8) came from 'winetricks comctl32'_
![An overlay of Vista and Fedora 27 workspaces showing affected toolbars](https://user-images.githubusercontent.com/62885/51424078-cb370f00-1c2d-11e9-94ce-94032de6fc2e.png)

_Image of 7.1.2 Workspace with comctl32.dll (6.0.6000-16383) from dotnet35_
![Image of 7.1.2 Workspace with comctl32.dll (6.0.6000-16383) from dotnet35](https://user-images.githubusercontent.com/62885/62284149-35ffb780-b4a7-11e9-9660-dfc16aada9c8.png)

**What's in the backpack**
 - OS/wine: 64-bit Fedora 28, wine-4.8-staging with 32-bit .wine/
 - winetricks packages:  gdiplus dotnet35 vcrun2017 cambria trebuchet

**Extra diary notes**
Top search bar becomes visible once the icon size is increased to 40x40, but this doesn't correct the east side layout. Depending on the installed version of comctl32.dll, toolbars that are meant to be vertical may or may not lay out vertically.

I noticed a decent amount of graphics work happen between these two releases in particular, the whole tileset appears to have been replaced. In addition, I've no idea what external library gets called when these toolbars are drawn.

I also think that some of the corruption present in the Fedora 27/Vista composite image above is related to issue #693, though the layout at least happens vertically, it's like the library doesn't assign enough space to hold all the things it's supposed to. In that particular circumstance, the text area rendered properly without the need to drag the window off to the right hand side.

**Comment by blairmcg** [comment]
Those versions of comctl32 may be or certainly are too old. Version 5.8 was originally released in Internet Explorer 5 in Windows 98 (!). Microsoft did keep releasing updated versions of until (I think) Windows 7 in order to support older apps because it has some different APIs and predates Windows XP so does not support visual styles. However, Dolphin has expected CommCtrl v6 for many many years, and I'm surprised 5.8 works at all as the structure sizes are different in some cases and there are missing messages and notifications.

Even 6.10.6000.16386 dates from 2006. I wouldn't be particularly surprised if there were issues with anything pre Windows 7 (6.10.7600.16385), even without injecting Wine into the mix. 

The commit that introduced the flat toolbar look between 7.1.1 and 7.1.2 was 08dca933467c2bfbc076fd7b2456f15a59b6e034. The flat look relies on the toolbars being "transparent" so that the background colour shows through. The commit did also remove some support for layout bugs in older versions of the CommCtrls. See `Toolbar>>calculateExtent:`, which was modified again in 0abf7127a31448620d0c4712d33fa5dd2b868483.

Space for the search box used to reserved by the hack of inserting a wide separator over which the box was then positioned. The separator itself left some visual evidence of its presence if one looked carefully, as it still drew underneath the search box. This was changed to use the proper mechanism provided to reserved space in a toolbar, i.e. `TB_SETINDENT`,  in 3dd27766ec3c9c6bbd2c7207e918b95ec6782319. `TB_SETINDENT` wasn't in the wasn't in the common controls when the Dolphin's Toolbar wrapper was originally written, but it has been present since at least Vista.

I notice also the bug of the 2nd (vertical) toolbar not changing bitmap size to follow the option setting. This is because `SmalltalkSystem>>applyOptionsToTool:` is expecting to find only one toolbar with a well-known name. I'll push in a fix for that, but it isn't going to address the problem of the sub-toolbars in the vertical toolbar laying themselves out horizontally in your case.

**Comment by blairmcg** [comment]
I'm closing this because it is going nowhere and I have no means to fix it or intent to do so.
