### ISSUE TITLE
[Wine] "Error: UndefinedObject>>doIt: at line 1: illegal number" while building image

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#816]
**It can't count**
When I'm building an image (say, DPRO), I get the error mentioned in the title, directly before the message about Reloading DolphinMessageBox. It doesn't appear to prevent me building the remainder of the image.

**Let's do it again**
Steps to reproduce the behaviour:
Start Terminal under Linux. Check out git tree, add contents of relevant DolphinVM to tree. Run the following command from within the tree:
```
Dolphin$ wine ./Dolphin7.exe DBOOT.img7 DolphinProfessional
...
```
Output from above job on my computer looks roughly like this (wine messages in ***italics***):
> _000b:fixme:winediag:start_process Wine Staging 4.8 is a testing version containing experimental patches._
_000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org._
_000d:err:menubuilder:init_xdg error looking up the desktop directory_
_000f:err:service:process_send_command receiving command result timed out_
_000f:fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 1053_
*0009:fixme:msvcrt:_configure_wide_argv (1) stub*
*0009:fixme:msvcrt:_initialize_wide_environment stub*
_0009:fixme:heap:RtlCompactHeap (0x1160000, 0x0) stub_
_0009:fixme:ntdll:NtQueryTimerResolution (0x1435588,0x1435590,0x1435598), stub!_
Dolphin Smalltalk Boot
Copyright (c) Object Arts Ltd, 1997-2018.
Loading boot script...
_0009:err:ole:CoGetClassObject class {f27d15bd-b8eb-488c-9932-c7fa0c598640} not registered_
_0009:err:ole:CoGetClassObject no class object {f27d15bd-b8eb-488c-9932-c7fa0c598640} could be created for context 0x1_
Reloading BCL constants pools...
Updating ClassBuilder...
Reloading BCL class definitions...
Reloading BCL classes...
**Error: UndefinedObject>>doIt at line 1: illegal number**
Reloading Dolphin Message Box ...
Loading source package 'Dolphin Message Box' from: Z:\home\viking\src\smalltalk\Dolphin\Core\Object Arts\Dolphin\Base\Dolphin Message Box.pax
Reloading Dolphin Source Fileout ...
Loading source package 'Dolphin Source Fileout' from: Z:\home\viking\src\smalltalk\Dolphin\Core\Object Arts\Dolphin\Base\Dolphin Source Fileout.pax
Deleting obsolete boot image methods...
Removing obsolete boot image method Context>>at:
Removing obsolete boot image method Context>>at:put:
Loading source package 'Dolphin Registry Access' from: Z:\home\viking\src\smalltalk\Dolphin\Core\Object Arts\Dolphin\Registry\Dolphin Registry Access.pax
Loading source package 'Dolphin Base64' from: Z:\home\viking\src\smalltalk\Dolphin\Core\Object Arts\Dolphin\System\Base64\Dolphin Base64.pax
Loading source package 'Dolphin Products' from: Z:\home\viking\src\smalltalk\Dolphin\Core\Object Arts\Dolphin\Installation Manager\Dolphin Products.pax
Booting DolphinProfessional
...

I'm also wondering if that's why I don't get a git version in the title bar of my DPRO images when generated under Linux, even though images generated under Windows run fine on both Linux and Vista.

**Operating System and Wine versions:**
 - OS: 64-bit Fedora 28
 - wine: wine-staging-4.8, WINEARCH=win32

**Comment by brickviking** [comment]
Further to the initial report, I ran the following in both a Linux-generated and a Vista-generated image:

Linux:
> SessionManager current productDetails
**#('Dolphin Smalltalk Professional' 'Professional' 7.1 '' 0 'DPRO' nil nil)**

Windows:
> SessionManager current productDetails
**#('Dolphin Smalltalk Professional' 'Professional' 7.1 '' 0 'DPRO' nil 'v7.1.8-15-g571a6ef8
')**

**Comment by blairmcg** [comment]
Building the image on Wine was never an expected scenario, although running Dolphin at all on Wine was never an expected scenario originally so perhaps that point is moot. The reason to make it is just to emphasise that you are free to fix it, but you are largely on your own. I don't have the facilities or inclination to reproduce any of the Wine issues myself.

The symptoms suggest that the following operation in boot.st is failing, so you can try debugging through it to find out why:
```
SessionManager current stashBootInfo
```
This works by running an external git command, so some possible reasons are:

1. Related to the git version (unlikely)
2. Specific problem running the git command (like not being on the path at that point, which again seems unlikely if you are running this from the same terminal that you've pulled the repo).
3. General problem with launching external processes
4. Your local git repo doesn't have any tags for some reason. You might think this unlikely, but it is possible to clone without them, or to fail to push them if copying a repo into a fork. Easily verified by running `git describe --tags` from the command line, which will just fail if there are none.

My guess would be (3), but debugging through will be needed to find out.

**Comment by blairmcg** [comment]
Oh, one other thing that occurred to me. You might find a DBOOT.ERRORS or DPRO.ERRORS file with more details of the error, including a stack. Deleting these files, if present, and running the boot again will produce an error log with just the relevant error(s) as they are appended to in normal use and you may have a long history getting in the way.

The location of the error in the console output suggests it might not be related to the git version problem, but hopefully the error log file will throw more light on it.

**Comment by brickviking** [comment]
As it turns out, I've found out how the issue happened. Even though Linux has git installed, Wine effectively tries to pretend there's a Windows commandline and path in place when it runs commands; as I never installed a windows version of git into the wine folder, it never gets run. Sorry to have wasted your time on this one. But someone else had the same symptoms as I did (git version never showed in their title), and it was for the same reason, which is why I remember it.

As for these wine bugs, I'll keep collecting them. I'm not too sure how I'll fix them but I'll try.

**Comment by brickviking** [comment]
Seems I fired a little prematurely. I can get the git version to not show on the title bar of the System Folder under Windows, simply by removing or "hiding" the git command when building the image. However, that hasn't proven to be the reason for the Illegal Number error under wine. And as I can't get git working properly under wine, there's no way to prove or disprove that that's causing the issue. 

Given that the image isn't even up yet when I'm building, I'm not sure how I'd find out how to cough up a "Illegal Number" consistently. Like you said, I'll have to walk through the SessionManager code in an already built image, or check out what the DBOOT.errors says. All I know is that it happens before MessageBox is even read in, but after the BCL class definitions and classes are reloaded. What does BCL stand for, anyhow?

**Comment by blairmcg** [comment]
> What does BCL stand for, anyhow?

Base Class Library

> I just ran a new Dolphin7.exe DBOOT.img7 DolphinProfessional, I got no .errors file. Where does this leave me?

Now I think about it, that is a compiler error - see the `CompilerNotification` class method `initialize`.

So, as a temporary change add a method like this to `CompilerErrorNotification`
```
defaultAction
	^SessionManager current logError: self
```
This may not be terribly informative since it seems to be evaluating an expression. The stack trace might give you some pointers as to the origin, but if not you may want to create copies of the `_descriptionArguments` and `_descriptionFormat`  methods from `CompilerNotification` and modify them to include the actual source code (which is available from the `source` method).

**Comment by brickviking** [comment]
And I'm assuming at this stage that I modify the .cls directly, and not within the DPRO image?

I had another question about just how the DBOOT source can be browsed with an existing open image, but that can wait until another time.

(OT) I'm also making pretty good strides towards getting the  documentation sorted. I've already got a way to go from XML into HTML (using xsltproc), I'm just working with some of the other data files now. It's starting to shape up.

**Comment by blairmcg** [comment]
One thing you could try that might yield a result is to browse the `*-compilation failures` category in the booted image. To do this just open a class browser on any class, expand the `*` in the tree in the categories tree, and then right click on the compilation failures child node and choose `Browse`. The compilation failure could be in a static expression (i.e. one of those that begins `##(…`) and should cause the containing method to fail to compile, in which case it should appear in the compilation failures category. Worth a try anyway.

> I'm assuming at this stage that I modify the .cls directly, which I did. 

Yes, in this case. It needs to be in chunk source format, which ought to be fairly easy to work out from the existing content. Sometimes you can put the chunk into the preboot.st file as a patch, but in this case it might get deleted by the code that removes methods that are in the boot image but not the sources files before the error is encountered.

> I'm a bit lost as to your next suggestions regarding the two methods _descriptionArguments and _descriptionFormat. I'm new enough to be able to read them, but not to know what to do with them to get the results you're asking.

The first returns an array of arguments that will be passed to a printf-style format which is described by the string returned by the second. The formatter is not actually sprintf, but rather the Windows [FormatMessage](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage) API. This uses a slightly odd format if you are used to C, but it does allow for positional parameters. Probably best to look at the existing definitions of `_descriptionFormat`.

> The other question I've got is: how on earth do I generate a stack trace? About the best I've been able to do within the image so far is to insert "self halt." into a method to call up the debugger, what I haven't been able to do is to figure out how to get the values out to the outside world as well as the method names being called.

In normal circumstances every error that occurs will automatically cause a stack trace to be written to the error log. If the image crashes, or if you explicitly request it, then the VM will dump a more detailed log to the same file. If you just want to copy a stack to paste somewhere you can do this by pressing the Copy button in the walkback dialog

![image](https://user-images.githubusercontent.com/15128107/64195675-f8ad9180-ce79-11e9-9c74-40dd3d9918ff.png)

or by just selecting all the text and using normal Copy & Paste commands.

> I had another question about just how the DBOOT source can be browsed with an existing open image, but that can wait until another time.

There is no specific tool for browsing unloaded source that presents it as a class browser might (creating one would be an interest project, and possibly not that difficult using the code modelling objects in the Refactory packages), but you can use the Chunk Browser to see them sequentially.

![image](https://user-images.githubusercontent.com/15128107/64196086-f566d580-ce7a-11e9-9623-40b57893bded.png)

BTW I notice that the toolbar of the Chunk Browser does not work correctly in any image size mode other than 16x16 - another bug.

**Comment by brickviking** [comment]
>One thing you could try that might yield a result is to browse the *-compilation failures category in the booted image. ... Worth a try anyway.

Hm, no compilation failures in there. Ah well, was worth a try.

**Comment by brickviking** [comment]
One more thing to add. If the value had been added where I think it should have been, it would have been somewhere near item 25917 in DBOOT.chg (Category: Other), when I view the changelogs using the Chunk Browser. This would all of course depend upon the DBOOT.chg not getting erased near the end of the process of building the image from Boot.st.

**Comment by blairmcg** [comment]
That is a denormalized value. Depending on the behaviour of the C-runtime library routine _atodbl_l and the CPU floating point exception mask setting, it might fail to compile. It's interesting that you can compile it normally later, and that suggests it is due to the default exception mask settings being different between the two environments. Once the image is up and running normally the exception mask will have been set to its default which will be allowing the use of denormals. On Windows IIRC the default is for all FP exceptions to be masked by the CRT on startup, but perhaps this isn't the case under Wine. It should get set by the call to `Float>>onStartup` even in a boot session, but its possible that something is amiss there.

**Comment by brickviking** [comment]
I did a little investigation. So far I've found the smallest value to get accepted is 2.2250738585072012e-308, something seems ... suspiciously familiar about that figure. It's the same as FMin 2.2250738585072014e-308, within a ULP. No way it's a denormalised value. I'll do some investigation on the Linux platform, and find out how compliant it is with IEEE 754.

**Comment by blairmcg** [comment]
5.0e-324 is definitely the smallest representable denormalised value. Parsing smaller values is not of any real use as they'll get rounded anyway. Depending on how the parsing code is written, and the settings of the FP control flags, the point at which an error occurs (or indeed if it occurs at all) may differ. There are two sets of flags within the control word that are relevant here - the exception mask, and the denormal control flags. Depending on the former you may or may not get an exception for denormals, and depending on the latter the denormals might be retained or alternately flushed to zero. Actually maybe even the precision control setting might come into play, depending on how the parsing is written. It doesn't particularly make sense to try and reason about the behaviour of the number parsing without knowing the value to which the VM or image is setting the fp control word. In Dolphin this is a per process setting stored in the fpControl instance variable. It is typically inherited when a process is forked, but can be set to something else (with care, since some choices will cause repeating errors that will effectively kill the image if set permanently in the UI process). The VM switches the fp control word as it switches processes.

Some reasonable explanations for the behaviour you are seeing are:

1.  the default FP control word setting established by the CRT is different, and that the boot image either has the wrong fpControl value stored down in the boot process, or it does not set this on startup (although it looks to me that it does). I think this fairly unlikely as I would expect there might also be issues on Windows since I seem to remember that the Dolphin default setting is different than the default CRT setting.
2.  the implementation underlying the function in the CRT (_atodbl_l) that the Dolphin compiler is calling is itself changing the fp control word, or is unable to parse denormals for some other reason.
3. the implementation underlying _control87 is deliberately not letting certain exceptions be masked. Interesting the alternate _controlfp function in the Microsoft C runtime library (described in the documentation as "a platform-independent, portable version of _control87") does not allow the denormal exception mask to be altered.

Given that you are saying that the you are unable to evaluate an expression containing the string representation of the minimum denormal value in a workspace in a booted image, I would think the 2nd or 3rd reasons the more likely.

It may be that the only way around this would be to change the initialisation of Float.FminDenormalized to use a calculation rather than initialize it to a constant, e.g. `(2 raisedToInteger: -1074) asFloat`

Alternatively, just ignore it. For most purposes this is unimportant.

---
To investigate the fp control work setting you would add the following to the PreBoot.st file in your repo.
```
SessionManager current stdout nextPutAll: 'Current fp control mask is '; print: Processor activeProcess fpControl; cr!
```
I would expect this to say:

```
Current fp control mask is 524295
```

This is the default fp control word in a running image after booting - it masks exceptions for denormals, underflow, overflow, and inexact results, leaving zero divide and invalid operation exceptions unmasked. Assuming the value is the same, you could try ensuring that the fp control word has definitely been updates as follows:

```
Processor activeProcess resetFloatingPoint!
```

Or if the value is different:
```
Processor activeProcess fpControl: 16r80007; resetFloatingPoint
```

Be careful not to unmask the inexact result exception in a running image.

**Comment by brickviking** [comment]
Yep, it does say 524295, so that much at least works. Where would I put "Processor activeProcess resetFloatingPoint"? In PreBoot? Or inside Boot.st just before I start reading in BCL? Or check that value again after I've read in BCL?
