### ISSUE TITLE
Followed the instruction 

### ISSUE THREAD

**Issue by FDominicus** [dolphinsmalltalk/Dolphin#850]
**Describe the bug**
git clone the_Dolphin_repository

**To Reproduce**
run bootDPro.cmd

**Expected behavior**
a booting o the system

What happened?
Boot failed, Code = -1

That's it.
Windows 10 64-bit

**Comment by blairmcg** [comment]
Unfortunately this bug isn't very actionable as it does not contain information to allow the issue to be either diagnosed or reproduced. Following the instructions of cloning the repo, building or fetching the VM, and running the boot script will work in general. It worked just now when I tried it with a fresh clone and fetching (rather than building) the VM. It works in the regular AppVeyor builds that build the VM.
You will need to do some more diagnosis yourself to either establish the nature of the issue, or at least provide some clue for someone else to either reproduce it or reason about it. If you can find some further information and/or detail the precise steps you took, then by all means re-open the issue. The kind of information required would be the exact tool and/or command you used to close the clone the repo (some ways you won't get the LFS objects, and then it won't work). Then did you fetch/build the VM? If you didn't build it, perhaps because you don't have VS2019 installed, do you have the C runtime library distribution from Microsoft installed? What happened when you tried running the dolphin7 command that is in the script? Is there any kind of error log or other output generated (look for the .errors file, look in the Windows application event log)? Does it crash?

If you are unwilling or unable to do that, then please use the installable release.
