### ISSUE TITLE
Use of BOM in files

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#859]
I notice that about half of the Smalltalk source files in the repository now start with a UTF-8 BOM, and investigating this, it looks like all new files created by Dolphin (or files entirely rewritten, i.e. `#truncate` mode) will be encoded as UTF-8 with a BOM. This seems...potentially a little heavy-handed? Based on my admittedly-limited reading, including a BOM is of questionable value, especially for UTF-8, and certainly having no option to *not* do so while still supporting Unicode characters isn't great. What was the rationale at the time? Any plans for more flexibility in the future?

That said, my immediate concern is eliminating noise from diff//merge output, so if the plan is to proceed with including a BOM in all source files, I would go ahead and make a PR to add it to all the files that don't yet have it.

**Comment by blairmcg** [comment]
I'm surprised you find there are a lot of files with the wrong encoding. They were updated en-masse by the large commit ee03eaaaf0fb7d9648c340e45892b59a1d2b95aa, which changed 2006 files to add the BOM and rewrite any characters with code points > 127 that might have existed in the source before. In fact if I file everything out now from a freshly booted image then `git status` shows me only only one modified file and it  Perhaps you are loading some code that isn't in the standard image, as if so that wouldn't have been update. In any case, by all means submit a PR to fix any files that don't have the correct encoding.

The reason to add the UTF-8 BOM was a combination of the fact that historically in Dolphin text streams were always "ANSI" (single-byte characters mapped by the current OS code page), which would have made opening them in UTF-8 by default a significant compatibility break, and because my experience was that using heuristic tests (i.e. sniffing the files) very often failed to detect UTF-8. I guess results would vary depending on ones sample set, but with files that largely contain English text (like Dolphin's Smalltalk source files), very few of them contain any characters at all with code points outside the 7-bit ASCII range, and even fewer within the initial bytes that are typically examined. I can appreciate the argument against the BOM that it is not needed as a "byte order mark" because byte ordering is not relevant to UTF-8 as the byte ordering is fixed by the encoding. In a green field situation (and especially on Linux) one could also tend to assume UTF-8 by default for files that didn't sniff as some other encoding. However, there is significant advantage in having an initial marker sequence that with near certainty identifies a UTF-8 encoded file from other single-byte text. Anything that processes UTF-8 text is required to handle the BOM correctly, so there doesn't seem any significant downside that would outweigh the advantage of very simple and deterministic identification of the text file encoding. If there is a real need to do things differently we can consider changing it, but if not I'd rather keep it simple.

**Comment by daniels220** [comment]
Aha! I believe the files without the BOM are largely ones that are not loaded in a default image or by RegressionTestsLoad.st. So that explains what's going on there. I'll make a separate issue for cleaning up these files—deleting them or moving them to external contrib repositories as appropriate.

Re: the justification—that makes sense for Dolphin source files. It *does* bother me a bit that this means it is no longer possible to write a UTF-8 encoded file *without* a BOM—which means it is no longer possible to write a file that is still UTF-8, but degrades gracefully in clients that are not UTF8-aware. You can create an ANSI-encoded file, and it won't have a BOM, but it also won't be UTF-8. I see how the implementation makes it difficult to handle this—you'd be using a Utf8String as the buffer in either case—so...I guess I'll see if it becomes an issue for me and what I can come up with for a solution if it does.

**Comment by blairmcg** [comment]
I don't know that there really is such a thing as UTF-8 degrading gracefully in non-UTF8 aware tools. Yes that would be the case if the text only contains ascii characters, but anything else is going to be corrupted and you'll get moji-bakes at best. If you have a BOM, you'll just get a moji-bake at the start of the file. Arguably this is a useful indication that there might be others in the document that would otherwise go unnoticed.
Obviously a solution is possible, but I'd be surprised if you need it.

**Comment by daniels220** [comment]
Yeah, fair enough. I guess if you *do* have only ASCII, now you'll get a moji-bake at the beginning, but in that case telling the file to encode as ANSI is a viable workaround.

**Comment by brickviking** [comment]
I was rather wondering how the STS would work. By the way, how do I "create" a repository? I saw no functionality for doing so through the exposed interfaces (i.e. the buttons and things) unless I simply wasn't looking in the right spot (quite usual for me I'm afraid to say).

**Comment by daniels220** [comment]
@brickviking I'm thinking you meant to respond elsewhere, but in any case—I don't know if/where you can create a repository from the UI, but if you evaluate `StsManager install` in a workspace that should get you started. Unfortunately, with the removal of the STS code from the default image, all the menu items for interacting with it are gone as well. One important step for publishing a version of STS as a contribution would be to create an IDE extension class (see the OA IDE Extensions sample package) that programmatically adds them in as appropriate.
