### ISSUE TITLE
Packages should allow loading with warning when loose methods clash

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/Dolphin#90]

**Comment by brunobuzzi** [comment]
We should present a GUI with clashing objects or just load the package ?
If not GUI needed then i think is simple and there a couple of places where do this.
PackageManager>>loadCompatibilityCheck:
comment to the following code:
"	overlappingObjects notEmpty 
		ifTrue: [self errorFileInCompatibilityCheck: aPackage overlap: overlappingObjects]."
By comment this we will avoid the Package clashSignal.
It also can be done in (by removing on:do: of Package clashSignal):
SmalltalkSystem>>installPackage:
I will further research in this issue. But a more detailed specification is need because it can be done in various places.
It will nice to present a GUI to the user...

**Comment by objectarts** [comment]
@brunobuzzi personally I think as a first pass (The Simplest Thing That Could Possibly Work) that no GUI is needed. However, the main complexity is what happens when a package is uninstalled. It must know that the clashing methods that have not been installed should not be removed.

**Comment by brunobuzzi** [comment]
@objectarts maybe the package that re-wrote the existing methods should store the "old methods" and when uninstalled must restore old methods. Of course this will require change the structure of Package class. I do not have enough knowldege in this area to know the consequences of this change. I have to do more research...

**Comment by blairmcg** [comment]
Providing good support for this is complex. The simplest thing that could possibly work is to not do it, which has worked well enough for many years after all.

**Comment by blairmcg** [comment]
I'm closing this because the suggestion is undesirable - if anything is to be done, it should be to save/restore the clashing extensions.
