### ISSUE TITLE
Inconsistency with matched values in Regular Expressions 

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#908]
**Describe the bug**
There is a problem with `IMatch>>value` method returning the value as an Utf8String where the property Value contains an Utf16String.
The resulting IMatch range and length indicates positions in an Utf16String so I think `IMatch>>#value` should return the same type.
Also it's a bit confusing what happens with an input in Utf8 as in the following examples:
```
input := 'This is a 🐬'.
regex := IRegExp2 pattern: '.*'.
matches := regex execute: input.
range := matches first range.
input copyFrom: range start to: range stop -> This is a 
matches first value copyFrom: range start to: range stop -> This is a 
(matches first getPropertyId: 0) copyFrom: range start to: range stop -> This is a 🐬

input := 'This is a 🐬' asUtf16String.
regex := IRegExp2 pattern: '.*'.
matches := regex execute: input.
range := matches first range.
input copyFrom: range start to: range stop -> This is a 🐬
matches first value copyFrom: range start to: range stop -> This is a 
(matches first getPropertyId: 0) copyFrom: range start to: range stop -> This is a 🐬
```

**Comment by blairmcg** [comment]
Yes, it would probably be better if `BSTR`s were converted to UTF-16 strings by default to avoid any similar problems. Conversion to byte strings was done in the original Dolphin COM wrapper because we had no useful representation of UTF-16 strings, but this should have been changed when the Unicode work was done.
In other words, `BSTR>>value` should be:

```smalltalk
value
	"Answer the receiver's value as a Smalltalk <String>."

	^self asUtf16String
```

Or maybe the `asString` method should just invoke `asUtf16String`.

**Comment by blairmcg** [comment]
I didn't comment on the 2nd point, about the confusion with mixing different encodings, particularly with code-unit ranges. There isn't really anything that can be done about that other than working with UTF-32 all the time. Aside from being very profligate with memory, that 
As the UTF-8 manifesto argues, it is best not to think of Strings as collections of characters, but rather as code unit arrays. With that in mind you have to make sure that any indices you have are for the encoding you are working with. The framework can avoid gratuitously creating mismatches (like not returning a Utf8String from `IMatch>>value` because the IMatch>>range indices are in terms of UTF-16 code units), but it can't handle cases like the one you outline, not in general anyway.
Different design choices would make these incompabilities surface up in different ways. For a system running on Windows defaulting to UTF-16 strings may be a better choice. I preferred not to do that because I think that UTF-8 is a better default encoding for most kinds of interop, and also because I was concerned that pervasive UTF-16 would hide issues with mixing up code points and code units and make them difficult to detect and find.

**Comment by fxgallego** [comment]
Thank for your detailed explanation. We need to get used to this stuff, mainly when interfacing with external libraries. I do a lot of Ruby these days and I never have to think about encodings with the exception of file handling, again, something external.
