### ISSUE TITLE
Fraction and Float equality returns false for the same Number

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#915]
**Describe the bug**
I can reproduce this in release 7.1.11 but not in 7.1.6 for instance.
(157/10) = 15.7 -> false
15.7 = (157/10) -> false

**Comment by blairmcg** [comment]
Intuitively the earlier result may seem correct, but in fact it isn't. The current result is more precise. Most decimal fractions cannot be represented precisely in IEEE doubles. If you said (1/4) = 0.25, then that would be true because 1/<power of 2> can be represented precisely (within precision limits). The literal floating point number 15.7 isn't actually 15.7 because 15.7 cannot be represented precisely. To see the real value try:

```smalltalk
15.7 asTrueFraction "(4419157134357299/281474976710656)"
```
Floats are printed imprecisely, but equality comparisons will be exact. I'm fairly sure you will get exactly the same result in Pharo.

Comparing FP numbers by equality is not generally useful, especially with other numeric types. You'll need to decide what level of precision is appropriate in any particular situation and compare to that level of precision, e.g. see Number>>closeTo:. You can also get something like the earlier imprecise behaviour by converting the `Float` explicitly with `asApproximateFraction`.
Or use ScaledDecimals.

**Comment by fxgallego** [comment]
Yes, I understand the problem.
Pharo has the same problem. Ruby doesn't (I didn't test it extensively).
Is there and example where the previous implementation also fails to compare `=` ?

I detected this on tests where the result was hardcoded into a Float so I don't really know right now how this could affect. At least other tests non comparing in this way ran ok.

**Comment by blairmcg** [comment]
Pharo doesn't have a problem. It is correctly using all the precision of the FP number and declaring it not to be equal to a Fraction of approximately the same value, because it isn't. Implementations that provide comparison operations between different types of number have to decide which way to convert before performing the comparison. To get the comparison as correct as it is possible to be (i.e. using all available bits of precision) the conversion has to be from the lower precision form (Float) to the precise form (Fraction) so that the comparison can be made with maximum precision. If the Fraction is converted to a Float before comparison then precision will be lost. That is what Dolphin used to do, and it was convenient/fast, but wrong. There are very many cases beyond the bounds of precision of a Float that such a comparison will be objectively wrong. #772 was the issue associated with the fix.
The problem here is in assuming that compiling up 15.7 gives you that exact value. It doesn't. It gives you a Float that is approximately 15.7. 
It really is best to avoid comparing Floats directly with `=` unless you know that you have a precise result (the same bits), or the same imprecision in your comparison. Nicholas Cellier gives a nice example in [his chapter of the Pharo By Example book](http://pharobooks.gforge.inria.fr/PharoByExampleTwo-Eng/latest/Float.pdf):

(0.1 + 0.2) = 0.3 "false"
