### ISSUE TITLE
FileSaveDialog fails to open with UTF8String as value

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#916]
**Describe the bug**
Evaluate in a workspace:
FileSaveDialog showModalOn: 'Camión'

This works ok:
FileSaveDialog showModalOn: 'Camión' asUtf16String

One coworker solved this implementing in `FileDialog`
```
value: aString
    super value: aString asUtf16String
```
I'm not sure if it's correct or enough in all cases.

**Comment by blairmcg** [comment]
Yes, it hasn't updated correctly for Unicode. It's copying the supplied string into the buffer using a string block copy operation, (replaceFrom:to:with:startingAt:) which doesn't work between different encodings because the number of code units to represent the same string could be different - i.e. the range will be wrong. It needs to be converted to UTF-16 as your co-worker has done, although I would put it in `prepareStruct` method because that is closer to the external interfacing that requires it. It looks like the file type filters are already handled correctly.
