### ISSUE TITLE
MultipleFileOpenDialog showModal returns +1 entries than selected ones

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#921]
**Describe the bug**
MultipleFileOpenDialog showModal returns +1 entries than selected ones due to new `subStrings:` implementation in #877

**To Reproduce**
Inspect the result of `MultipleFileOpenDialog showModal` selecting several files

**Comment by fxgallego** [comment]
In a fresh image without tests there are only 2 senders of `subStrings:`. A half was affected by the #877 change . Also in #877 there are 2 external packages affected.
In our application we have 140 senders and not all covered by tests. Also looking at the usage pattern seems that it probably will broke most of them.
I'll probably change the code for `subStrings:` in my patches package because I feel it's safe to do it and I believe it would be "more" useful that way.
Is there no possibility to reconsider this change?

**Comment by blairmcg** [comment]
Aside from the fact that 2 would be a very small sample set to be making a judgement that half of all cases would be affected, there were many more cases than 2 at the time I made the change. In fact there were at least 10 times than number, about the same as the 20 odd uses of `Character>>split:` to which I subsequently changed them and which there are now. Of these 3 were affected and fixed by me at the time:

1. `Symbol>>keywords` was directly relying on the old behaviour since it just split on `$:`
1. `ClassDescription>>instVarNames` was incorrectly defined and needed to ignore all empty tokens (or it should have used `subStrings` which behaves differently in another inconsistency)
1. `RegKeyAbstract>>decodeMultiSz:size:`, which was really misusing `subStrings:` for the same external interface pattern that is at issue with the `MultipleFileOpenDialog` contributed by Ian Bartholomew many years ago, whereby a list of strings is represented as null terminated strings packed into a single string with a double null to terminate the list.

So even if it were 3 cases out of 20 (and actually it is arguably just 1), that sample suggested it was rarely an issue and so correctness and consistency should trump compatibility. I not sure whether I overlooked `MultipleFileOpenDialog` because it is a contribution and I avoid changing these unless necessary (although it was necessary in this case) or because I didn't pick up the 3rd case until the CI build ran the tests. A further opportunity would have arisen when I was subsequently replacing the uses with `split:`, but I overlooked it again.

I'll comment a little more on the reasons behind the change of behaviour. Aside from the consistency argument, I don't like the old implementation because it loses data. Consider the case where you have a .csv file that contains entries which are empty. This is not uncommon and the empty elements are still part of the tabular data, but treated as zero or empty. For example '100,,300,", which is expressing values for 4 columns, not 3. It would be incorrect to drop the final empty element. Another case is String>>lines. This used `#subStrings:` (and now `Character>>split:`. If the a trailing newline is not treated in the same way as intermediate new lines, then it means that no distinction is made between input data that has a trailing newline, and that which does not. In some cases this may not matter (or be desirable), but in others it is lost information. You can apply a further transformation to remove the extra data you don't want, but you can't so easily get back the information you lost.

I really don't want to revert this change, but I think there are three ways forward to help you:
1) You patch it, as you suggest. This probably is safe as the base system prefers to use `split:` directly (which behaves the new way) so won't be affected. BTW I don't think this is a good argument to change `subStrings:` back, because then `subStrings:` would be inconsistent with `split:`, creating more cognitive dissonance.
2) I change it back in 7.1 because I really shouldn't have made a breaking change like this in a minor revision. It will still be in 7.2 however, so that is only temporary respite. I plan to go further in in 7.2 and change it to behave per the ANSI definition (such as it is) to resolve the longstanding todo, but that would only affect the behaviour with a string parameter.
3) Define a method that does exactly what you want, and then perform a scoped rename references refactoring to that across your code. Good luck choosing a short name for the method that expresses its behaviour of trimming the last empty element only.

```smalltalk
corePackages := Package manager packages select: [:each | each packagePathname asLowercase beginsWith: PackageFolder dolphinRootPathname].
"A BrowserEnvironment with all code not in Dolphin core except the String class - try Ctrl+B on it to see what is in it. You might prefer to construct an env with just your packages in it, rather than not core packages + String"
env :=  (BrowserEnvironment new forPackages: corePackages) not | (BrowserEnvironment new forClasses: {String}).
model := RBNamespace onEnvironment: env.
refactoring := RenameMethodReferencesRefactoring 
			model: model
			renameMethod: #subStrings:
			in: String
			to: #mySubStrings:
			permutation: #(1).
model name: refactoring displayString.
"This will fail on a precondition if you have not already added #mySubStrings: to strings"
refactoring
	execute;
	yourself
```

**Comment by fxgallego** [comment]
@blairmcg Thanks for taking care of this. I think that we'll be on 7.1 for a while. I understand the change and we should prepare for that in next versions.

As you suggested my first approach was to add `mySubStrings:` but we have a complex scenario here with product versions 4 years old, with developers merging code upstream from the oldest to the newest versions so we need to do it with care trough the versions because some patch in the older one could be merged using the wrong `subStrings:`method.

Thanks for wishing us good luck choosing the name, it was really challenging, and we are Spanish native speakers, something that doesn't helps. We ended up with `subStringsWithoutEmptyEnding:` not short, ugly, and probably wrong in meaning but at least self-explanatory 😄 
Also a guy in the Buenos Aires Smalltalk slack group ended with `subStringsTrimmingTrailingEmptyElement:` .

**Comment by blairmcg** [comment]
So was that a vote for option 2, or are you happy with option 1?

At least the long names are clear. Clarity is more important than brevity. Both together is sublime, but often difficult to achieve.

BTW: I notice that the remaining non-test use in the base image of `subStrings:`, which is in `CommandLine>>parseLongOption:`, would have failed with an index out of bounds error with the original implementation if the command line argument was expressed as 'option=', whereas now it does not.

**Comment by fxgallego** [comment]
Oh sorry, for me I'm OK with option 2 if that doesn't means a lot of work for you. Anyway I have patched that in my image right now so if you do option 2 and a 7.1.12 is going to be available I'll remove my patch.

**Comment by blairmcg** [comment]
It should be fine. I'll reinstate the old `_separateSubStringsIn:` method in `Character` and `String`, and revert `subStrings:`. The new `split:` methods will remain as they are (which is why it is not troublesome).
