### ISSUE TITLE
Send initialize to new instances by default

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#948]
An issue I've hit when porting code from Pharo to Dolphin is that Pharo implements `Behavior>>new` as 
```
^ self basicNew initialize
```
Dolphin on the other hand does what I think most other Smalltalk implementations do and just returns the new instance with no initialization (the same as `basicNew`).

This is something that has appeared wrong to me ever since I started using Smalltalk. If I'm subclassing an existing class and implement `initialize` in my new class I have to check through the parent hierarchy to see if any of the superclasses also implement `initialize` and therefore have added 
```
new
	^super new initialize
```
If they have, I don't do anything else. If they haven't, I add it. In addition to being a (slightly) annoying additional step this is a point of brittleness since if a superclass adds/removes their `initialize` and `new` implementations this can break my subclass. 

On this occcasion I think Pharo has taken the right approach and would like to suggest that Dolphin considers doing the same.

In support I'll quote the comment for `new` in the `instantiator` and `Object class` protocols in the Draft ANSI spec:

> Return a newly created object initialized to a standard initial state. 

(I'll admit it's unclear if the "standard initial state" is a general one or specific to the implementing class - possibly the final spec clarifies this?)

**Comment by blairmcg** [comment]
Having had the experience of trying to move a lot of code out of one of those traditional Smalltalk systems into Pharo, that decision is a major compatibility headache. It is a problem in either direction, but running code that is not expecting the initialize is more problematic than the direct failures one sees from not running the initialize. Double-initialization can create all sorts of subtle issues that generally don't show up immediately. Based on that reason alone I don't intend to change it, sorry.

I'm afraid the ANSI standard doesn't support the argument "for" either, since since the `initialize` method is not part of the spec, and the implementation of methods in the spec are not supposed to call methods not in the spec because it creates a fragile subclassing problem.  The words in the spec are referring to the general initialization to the standard initial state of nils or zeros.
Of course that can all be taken with a pinch of salt since there are so many pre-existing cases of the fragile subclassing problem that none of the existing implementations could comply without breaking everything. The standard was really in need of a V2 to iron out the issues in the first version. My favourite (though much smaller) issue is that DateAndTime instances are supposed to be able to tell you the name of the timezone in which they are specifying a point of time, which is impossible since they only know the offset from UTC, and one can't determine a unique timezone from that.

**Comment by rko281** [comment]
No problem; I prefer the Pharo approach but appreciate the counter-viewpoint and experience.

I now run a script after porting code to pick up any classes implementing an `initialize` that won't be sent and add a corresponding `new` implementation, so it's a manageable issue.

Thanks for the explanation.
