### ISSUE TITLE
Inconsistent handling of Strings as characters vs bytes

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#957]
`'abc°def' copyWithout: $°` yields an unmodified string—the degree symbol is not removed. If I convert the string to ANSI first it works as expected. Looking at the implementation of `copyWithout:` and tracing from there, it seems clear that `String>>do:` is a byte-wise iteration, and ends up comparing the ° to each of the two bytes that make it up in UTF-8, which it doesn't match, and so nothing is removed.

ReadStream, by contrast, handles strings character-wise, so if I replace `self do:` with `self readStream do:` in `SequenceableCollection>>copyWithout:` (or add an override that behaves this way on `String`), the problem goes away. This seems like a more general issue of inconsistency/lack of clarity about when a String is treated as an array of bytes-that-are-accessed-as-characters, and when it is treated as an array of Characters-that-may-not-all-be-the-same-size.

**Comment by blairmcg** [comment]
That is rather blunt. I'm not particularly sorry for the perceived inconsistencies - there is a consistent philosophy, but certainly there are mistakes and incompleteness in application and that is to be expected from something I do largely by myself in my spare time as an unpaid hobby.  I am sorry for the lack of clarity though. The class comment of UtfEncodingString does explain the overall philosophy to some extent, but it should include some detail and resources that I have referred to here before. In particular see https://github.com/dolphinsmalltalk/Dolphin/issues/763#issuecomment-488769976. I spent a long time thinking about how to best integrate strings with variable length character encodings into the Smalltalk collection hierarchy, until eventually I read [UTF-8 manifesto](http://utf8everywhere.org) and realised that there was no completely adequate solution because Strings should never have been in the collection hierarchy. They are not in Ruby, for example, a system with especially good support for international language strings. The outcome was a decision that any SequenceableCollection protocol that operates with indices should be expected to be operating on code units, not code points (and certainly not visible characters, which are not the same as even code points). It would perhaps be better if most of these indexing operations were not available at all, but moving String out of the collection hierarchy seems like just too much of a break for Dolphin, and in any case they have some utility as low-level manipulations to implement higher level operations on strings. For enumerating, though, streams should generally be used.
There are then some collection operations that appear on SequenceableCollection that aren't using indices, and in some cases (like `copyWith:` and `copyWithout:`), that don't even depend on the collection being a sequence. For these it may make sense to work with code-points rather than code-units, as long as that does not itself create more inconsistency. Each needs considering individually (or as a closely related group). I decided to leave them alone rather than make the wrong choice in a hurry and revert it later.
If `copyWith:` and `copyWithout:` operate on code points, then the similarly named `copyWithoutIndex:` will behave differently, but that can be understood as an application of the rule that indexed operations operate on code units. Also these promise operations on the collection has a whole. Therefore I would agree that naturally these should operate on code points and it doesn't create too many inconsistencies with other operations. The right choice for `do:` is considerably harder.

**Comment by daniels220** [comment]
My apologies, I didn't mean to be bluntly critical, and I can see how it came across that way. I wrote this in a bit of a hurry, and kinda wasn't sure exactly what I was suggesting or asking for, I just wanted to bring the issue up. I clearly could have done a better job expressing that uncertainty and keeping things in a spirit of exploration/curiosity.

So, thank you for your comprehensive response—that all makes a great deal of sense. I admit I am not used to reading class comments—so often the code itself, with the occasional method comment (some of which do a _brilliant_ job clarifying a tricky bit of behavior, by the way—nice work!), does such a good job explaining itself that I never think to look further. I guess I'm a bit spoiled by Smalltalk 😄 .

Looking at things, `copyWith:` does in fact operate on codepoints—that is, `'abc' asUtf8String copyWith: $°` answers the correctly-formed Utf8String `'abc°'`. So certainly for my own purposes I'm comfortable overriding `#copyWithout:` to behave similarly—is that a contribution you would like/accept in core?

----

While we're on the subject of UTF-8, I'm curious about the decision of what encoding to use for string literals. It seems like ASCII-only string literals are still represented as `AnsiString`s, while those that contain non-ASCII characters, yet are still representable in the ANSI encoding, become UTF-8. (e.g. `'abc' class` -> `AnsiString`, `'abc°' class` -> `Utf8String`) My naive expectation was that they would always be UTF-8—of course for ASCII data there's no difference, but then if you try to concatenate, it's a little weird that e.g. `'abc' , 'Ӓ'` throws an error rather than happily returning `'abcӒ'`—yet `'abc°' , 'Ӓ'` works fine. Of course it would also work to have strings "negotiate" the most capable encoding when concatenating rather than going with the left operand, but that's more work...

**Comment by blairmcg** [comment]
> Looking at things, `copyWith:` does in fact operate on codepoints—that is, `'abc' asUtf8String copyWith: $°` answers the correctly-formed Utf8String `'abc°'`. 

Yes, `UtfEncodedString` does have an override of #copyWith: already, and just uses the concatenation operator. Looking back it was added as part of the first version in 76d1c8697b3e14e410603a5f3591eaac4dda20b9. 

It's wrong that it doesn't work for AnsiString receiver's though. They should just promote. That is objectively a bug. Probably the method should just be pushed up to String.

> So certainly for my own purposes I'm comfortable overriding `#copyWithout:` to behave similarly—is that a contribution you would like/accept in core?

Certainly. Implementing it by streaming over the content to read/write as you suggest makes sense. Unfortunately it lacks tests currently but should have something as this issue demonstrates. Adding tests in the current `SequenceableCollectionTest` hierarchy is a bit tedious and limiting as they have to be coded to work for all the various types. If would be easier to implement it just for strings in either `StringTest` or `MultiByteStringTest` if you decided to put the implementation in either `String` or `UtfEncodedString` respectively.

> While we're on the subject of UTF-8, I'm curious about the decision of what encoding to use for string literals. It seems like ASCII-only string literals are still represented as `AnsiString`s, while those that contain non-ASCII characters, yet are still representable in the ANSI encoding, become UTF-8. (e.g. `'abc' class` -> `AnsiString`, `'abc°' class` -> `Utf8String`) My naive expectation was that they would always be UTF-8

#761 explains that choice. At the time I was concerned about the overhead on Win32 'A' (Ansi) API calls of the double translation from UTF-8 to Ansi via UTF-16. The relevant Windows APIs provide one-shot conversion to/from any code page (including the pseudo code page, `CP_UTF8`) to/from UTF-16, but not directly between code pages. However, there are only a handful of such API calls left in the image - the wide string APIs are used for almost everything. From that perspective defaulting to UTF-16 Strings might be a better choice, but there are other reasons to prefer UTF-8. As it happens I've already changed the compiler in the 7.2-dev branch to always generate `Utf8String`s for literal strings.

> —of course for ASCII data there's no difference, but then if you try to concatenate, it's a little weird that e.g. `'abc' , 'Ӓ'` throws an error rather than happily returning `'abcӒ'`—yet `'abc°' , 'Ӓ'` works fine. Of course it would also work to have strings "negotiate" the most capable encoding when concatenating rather than going with the left operand, but that's more work...

Actually the concatenate primitive does do that anyway, so I'm surprised you find that throws an error. It seems to work when I try it. It is [coded](https://github.com/dolphinsmalltalk/Dolphin/blob/36a946943e0863993b20bdb0c8195c8a7e40f989/Core/DolphinVM/strgprim.cpp#L1271) to do the following:

Receiver | Argument | Answer
------------ | -------------|-------------
AnsiString | AnsiString | AnsiString
AnsiString | Utf8String | Utf8String
AnsiString | Utf16String | Utf16String
Utf8String | AnsiString | Utf8String
Utf8String | Utf8String | Utf8String 
Utf8String | Utf16String | Utf8String
Utf16String | AnsiString | Utf16String
Utf16String | Utf8String | Utf16String 
Utf16String | Utf16String | Utf16String

There is a common pattern in many of the String and Stream primitives of handling these nine permutations.
