### ISSUE TITLE
Literal value nodes should distinguish between Strings and Symbols

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#978]
`RBLiteralValueNode value: 'foo'` should clearly be distinguished from `RBLiteralValueNode value: #foo`, even though `'foo' = #foo`. Right now the implementation of `RBLiteralValueNode>>=` depends on `species`, which has overloaded meanings—because it is used by e.g. `select:`, `Symbol>>species` cannot be `Symbol`.

Ultimately the best solution may be to clean up the usage of `species` in the `Collection` hierarchy so that it can be more true to its intended meaning, thus all Strings would answer String and Symbol would answer Symbol, fixing this problem. (It's worth noting that literal nodes containing the same string in different encodings should also be considered equal, currently would not be, and would also be fixed by cleaning up the usage of `species`.)

**Comment by blairmcg** [comment]
Has been fixed in master (Dolphin 8) for a while. I won't be backporting the change to release/7.1 myself, but someone else can do so if they wish. See 933381a5c11d26927ffeec1c96bb8263cb11d708 for details, but bear in mind it may be difficult to apply without breaking the image.
29373d4 adds a specific regression test for the issue as described.

**Comment by daniels220** [comment]
Neat, thank you. The whole question of what `species` means, and how to handle the various collection operations appropriately for different collections (SortedCollection, pluggable collections, weak collections, Symbol vs. String as here, external/proxy collections like RegKey, etc) is surprisingly thorny, but this seems like a step in the right direction.
