### ISSUE TITLE
Incorrectly categorized ***compiled accessors*** methods 

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#986]
Whilst deploying a Seaside application I ran into an issue with missing header fields in the generated response (the issue did not exist when running in the development environment). 

I eventually tracked the problem down to the recompilation of ExternalStructure methods during deployment. In my specific case it was the recompilation of HTTP_KNOWN_HEADER>>pRawValue:

```
pRawValue: aString
	"Set the receiver's 'pRawValue' field to the value of the argument, aString"

	bytes uintPtrAtOffset: _OffsetOf_pRawValue put: aString yourAddress.
	self RawValueLength: aString size
```

The recompiled version of this removes the last line, causing the header to effectively be an empty String. 

I'm aware this recompilation can be disabled using the "Compile External Structures" option in Step 5 of the Deployment Wizard, however I've never needed to change this setting before. Also recompilation is automatically skipped for methods which are not in the `***compiled accessors***` method category (see ExternalStructure class methods `shouldCompile:forField:` and `hasHandCodedMethodFor:`) - pRawValue: is currently in this category. Therefore I think the correct solution would be to move the method to a different category. 

The following script demonstrates there are a number of other `***compiled accessors***` methods where recompilation changes the definition (mostly in the Windows HTTP Server and Dolphin Metafile Records packages ). Note the script destructively modifies the image.

```
oldMethods := Dictionary new.
category := ExternalStructure autoGenCategory asMethodCategory.
category methods do: 
	[ :each | 
	(oldMethods at: each methodClass ifAbsentPut: [Dictionary new]) at: each selector put: each].

ExternalStructure allSubclassesDo: [ :each | each fullyCompileDefinition].

diffs := SortedCollection new.
category methods do: 
	[ :each || oldMethod |
	oldMethod := (oldMethods at: each methodClass ifAbsent: [Dictionary new]) at: each selector ifAbsent: [nil].
	(oldMethod notNil and: [oldMethod byteCodes ~= each byteCodes]) ifTrue: [diffs add: (oldMethod -> each)]].
diffs
```

**Comment by blairmcg** [comment]
Removing the methods from the category would workaround the issue, but the HTTP_KNOWN_HEADER one at least has not been manually edited. It's the result of generating from a type library, but for some reason the #defineTemplate does not match up with the method. That is possibly because at the time I was building the package I decided to enhance the type library analyzer to be able to generate some common patterns that appeared in the library, rather than writing methods by hand. This is an example of one common pattern it uses where there is a size_is attribute one an array field referencing another field in the structure that specifies the length of the array. I tried regenerating it, but although the analyzer attempted to generated the correct field definition, there are some errors in the method so it wasn't compilable. Perhaps I lost some changes and as I failed to write any tests, didn't pick it up, but whatever it shouldn't be difficult to fix.
