### ISSUE TITLE
Windows XP Link

### ISSUE THREAD

**Issue by sjzara** [dolphinsmalltalk/Dolphin#988]
I came to this repository via the Dolphin Smalltalk website, where it mentions Windows XP compatibility.  I have tried building for Windows XP using Visual Studio versions 2015 and 2019, but it fails.  Could a link be put up to an older version of the source that does build for XP, for those of us who sadly have clients still stuck on that system?
Thanks
Steve

**Comment by blairmcg** [comment]
The short answer is no, sorry. The website is not being updated, so it is historic. The earliest available open source version of Dolphin is 7.0 and that won't be changing because it is would be far too much effort, especially for a target system for which there has been no support for many years. As far as I recall the original 7.0 releases may have worked with XP, but that would never have been tested because by then it was unsafe to run XP. Going back to one of the earliest tags in the history might work for you, but I'm afraid if it doesn't you are out of luck with the OSS version.
