### ISSUE TITLE
Improve Method History Browser performance

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#999]
The Method History Browser is very slow in my current working image (around 60MB changes file) - 10 seconds to open, then another 10 seconds as it refreshes when I reinstall an earlier method version (this wasn't the case in D7.0). The core of the slowdown appears to be the send of `nextAvailable:` in `ChunkFileMethodScanner>>positionsOf:in:firstOnly:` as it reads and decodes the requested number of UTF8 characters.

I initially implemented a modification whereby ChunkFileMethodScanner instead reads a specified number of bytes via `basicNextAvailable:` plus any trailing UTF8 character units (the exact number of characters read is unimportant; it's just part of the local paging scheme). The result is a String of valid character points <= the requested number, and a much improved performance.

However a much simpler solution with similar performance is to remove the local paging scheme and simply read the entire file in one hit. I'm wondering whether this would be acceptable - the likely maximum size of a changes file (100MB?) isn't _that_ large for current machines.

**Comment by blairmcg** [comment]
I'd noticed that myself of late, although more the impact of leaving open a method history browser on subsequent editing. It is quite a heavyweight operation to rescan the entire change file every time some new stuff is added to the end!

I think just changing the `nextAvailable:` to `basicNextAvailable:` is probably fine as a short term fix. It probably doesn't matter (or at least should not make any worse) the fact that this is potentially going to return partial characters at start and end. The statement that adjusts the position at the start of the loop could (in theory) cause that to happen anyway, at least at the start of the string. Without testing it to be sure, it looks to me like it would never be an issue because of the nature of the content of the file and what is being searched for - Smalltalk identifiers can't contain multi-byte characters because the lexicon doesn't allow it. An example search string would be `!Object methodsFor!`. I think this means we can only start searching for the string in the middle of a character which cannot be in the string, so there is no negative impact from having a start position that isn't on a code-point boundary. 

Theoretically the code that adjusts the start position could fail to move back far enough if the current stream position is in the middle of a multi-byte character that follows immediately after the search string. Again in practice I don't think this can happen because the immediately following characters will be a pair of CR/LFs, and then the start of a method selector, all of which must be ASCII characters. For correctness, it should probably step back until `Utf8String>>isLeadCodeUnit:` is true for the current position, and only then step back by the length of the search text.

Another simple improvement to the history browser itself would be to avoid re-scanning on method update. The method history browser knows which method it is viewing the history for, and it already ignores all method changes apart from those for the method in question. However it doesn't need to scan the change log to get the updated source since it is passed the new method in the compilation result and could grab the source directly.

As a longer term fix I think two things should be done in the categories of optimization and choosing a different algorithm. As usual the 2nd approach is the one that carries by far the biggest win, although the optimization would benefit many other scenarios too:

1. The performance of `PositionableStream>>nextAvailable:` (or certainly the operation on `FileStream`) should be improved. When doing the UTF work I added an implementation that is functionally correct, but it could be optimised in some way. The request is expressed in "number of code points" rather than "number of code units", so it will probably require primitive support  as there is no way to tell the number of code points between two code unit positions in a variable length UTF encoding, except by enumerating through them.
1. Adopt a scheme of writing the source descriptor integer of the previous edition of the method as part of the chunk header for an individual method update in the log. This would then allow the string search for existing methods to be replaced by a massively faster linked list style traversal.

**Comment by rko281** [comment]
Assuming you started from the current method's source descriptor, (2) wouldn't work when using the Method History Browser to recover changes after exiting an image without snapshotting. Though I guess you could do a short forward scan to check for any unsaved versions and append these to the list. 

A related idea which I implemented in D5 was to not re-log the method source when loading a previous method version but to just recompile and point the new method to the previous source descriptor. This kept things a bit cleaner and allowed something akin to an Envy-style history view:

![d5_method_history](https://user-images.githubusercontent.com/16988710/90640723-40aefb00-e228-11ea-8121-1615255daed6.png)

The method "timestamps" are picked up from the nearest previous image start/snapshot marker. If this is of interest I can look at a port to D7.

**Comment by blairmcg** [comment]
Yes, that's true. If you wanted to see the forward but unsaved history, it would also be necessary to scan ahead.

I like the idea of restoring the original source pointer when a old version is reloaded. That would stop the rather unfortunate behaviour of loading an old version then adding another copy to the end of the list.

Personally I don't think I would find a time-based list terribly useful as my images tend not to be very long lived, and unlike Envy it's unlikely to be useful for going very far back. I would tend to look at the git history for that. For recent changes I prefer to just scroll back quickly through the version until I find the one I want as I can generally remember the shape better than when I did things, but that doesn't mean it wouldn't be useful for others.
